import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { REQUIRED_CATALOG_KINDS } from "../scripts/check-catalog-manifest.ts";
import { promoteLiveBaselineCatalog } from "../scripts/promote-live-baseline-catalog.ts";

const sha256=value=>createHash("sha256").update(value).digest("hex");
const rows=REQUIRED_CATALOG_KINDS.map((kind,index)=>({kind,identity:`nearyou.${kind}.${index}`,definition:kind==="policy"?"nearyou_policy_owner|SELECT|true|":`definition-${index}`}));
const ledger=[
  ["0001_nearyou_tenant_foundation","2be7deca257891ce0921cbe7d9ca8ee233fbf44def1121b8464d73e9e1ad6e58"],
  ["0002_release_evidence_trust","9f9cefc8b93caa147e165d9694bf5fc9bdcf65286f7898836ac4a9b12a45f547"],
  ["0003_cutover_runtime","cbc434cf484a75b9cb5601e3867d8bb0fbec8fc960aa98d42e0db19385549b34"],
  ["0004_product_readiness_evidence","3bed1f97de8fdc558cf22f75bf0da979cb9abdd8a4bfb102e7b2f2c61b61d4a0"],
  ["0005_operational_evidence","c8a30cc75d0bfb0debb2a0295d93cd3a47a42b88f738be18f00a5ecbbd10f824"],
  ["0006_private_canary_observation","c0cfafb21767040dca10511c756bbdfdd4373a84cd6f3e2184310be9e7748500"],
].map(([id,checksum])=>({id,checksum}));
const authority={expectedCommitSha:"a".repeat(40),expectedImageDigest:`sha256:${"b".repeat(64)}`,expectedRelease:"rel_20260817_private_01",expectedOperationId:`op_${"d".repeat(64)}`,expectedOperationStartedAt:1786993200000,expectedDatabaseName:"nearyou",expectedDatabaseUser:"nearyou_migration_admin"};

function candidate(){const provenance={database:{name:"nearyou",serverVersion:160011,migrationAdmin:"nearyou_migration_admin"},source:{commitSha:authority.expectedCommitSha,imageDigest:authority.expectedImageDigest},release:authority.expectedRelease,operationId:authority.expectedOperationId,operationStartedAt:authority.expectedOperationStartedAt,migrationLedger:ledger,migrationLedgerChecksum:sha256(ledger.map(row=>`${row.id}:${row.checksum}`).join("\n"))};return{version:1,reviewRequired:true,generatedFrom:"live-production-postgresql-16",migrationHead:"0006_private_canary_observation",schema:"nearyou",catalogChecksum:sha256(JSON.stringify(rows)),requiredKinds:REQUIRED_CATALOG_KINDS,requireForcedRls:["household_members","tenant_records"],forbidPublicExecute:true,security:{forcedRls:["household_members","tenant_records"],publicExecuteCount:0},provenance,provenanceChecksum:sha256(JSON.stringify(provenance)),rows}}

test("promotes only an exact immutable live-production 0006 baseline",async()=>{const directory=await mkdtemp(join(tmpdir(),"baseline-promotion-"));try{const candidatePath=join(directory,"catalog-manifest.baseline.candidate.json"),receiptPath=join(directory,"catalog-manifest.baseline.receipt.json"),output=join(directory,"catalog-manifest.baseline.reviewed.json"),body=`${JSON.stringify(candidate(),null,2)}\n`,receipt={uri:"gs://nearyou-private-evidence/catalog/catalog-manifest.baseline.candidate.json",generation:"123",contentSha256:sha256(body)},receiptAuthority={expectedReceiptUri:receipt.uri,expectedReceiptGeneration:receipt.generation,expectedReceiptContentSha256:receipt.contentSha256};await writeFile(candidatePath,body);await writeFile(receiptPath,`${JSON.stringify(receipt)}\n`);const reviewed=await promoteLiveBaselineCatalog({candidate:candidatePath,receipt:receiptPath,output,...authority,...receiptAuthority});assert.equal(reviewed.generatedFrom,"reviewed-live-production-postgresql-16");assert.equal(reviewed.migrationHead,"0006_private_canary_observation");assert.equal(reviewed.catalogChecksum,candidate().catalogChecksum);assert.deepEqual(JSON.parse(await readFile(output,"utf8")),reviewed);await assert.rejects(()=>promoteLiveBaselineCatalog({candidate:candidatePath,receipt:receiptPath,output,...authority,...receiptAuthority}),/EEXIST/)}finally{await rm(directory,{recursive:true,force:true})}});

test("rejects candidate, receipt, and authoritative fact tampering",async()=>{const directory=await mkdtemp(join(tmpdir(),"baseline-reject-"));try{const base=candidate(),policyIndex=base.rows.findIndex(row=>row.kind==="policy");for(const [name,value,override={}] of [["rows",{...base,rows:[...base.rows,{...base.rows[0]}]}],["legacy-policy",{...base,rows:base.rows.map((row,index)=>index===policyIndex?{...row,definition:"SELECT|true"}:row)}],["arbitrary-policy",{...base,rows:base.rows.map((row,index)=>index===policyIndex?{...row,definition:"definition-6"}:row)}],["head",{...base,migrationHead:"0007_private_tester_deployment_manifest"}],["source",base,{expectedCommitSha:"c".repeat(40)}]]){const candidatePath=join(directory,`${name}-catalog-manifest.baseline.candidate.json`),receiptPath=join(directory,`${name}-catalog-manifest.baseline.receipt.json`),body=`${JSON.stringify(value,null,2)}\n`,receipt={uri:`gs://nearyou-private-evidence/catalog/${name}-catalog-manifest.baseline.candidate.json`,generation:"123",contentSha256:sha256(body)},receiptAuthority={expectedReceiptUri:receipt.uri,expectedReceiptGeneration:receipt.generation,expectedReceiptContentSha256:receipt.contentSha256};await writeFile(candidatePath,body);await writeFile(receiptPath,`${JSON.stringify(receipt)}\n`);await assert.rejects(()=>promoteLiveBaselineCatalog({candidate:candidatePath,receipt:receiptPath,output:join(directory,`${name}-catalog-manifest.baseline.reviewed.json`),...authority,...receiptAuthority,...override}),/baseline catalog promotion invalid/)}const baseBody=`${JSON.stringify(base,null,2)}\n`,path=join(directory,"replacement-catalog-manifest.baseline.candidate.json"),receiptPath=join(directory,"replacement-catalog-manifest.baseline.receipt.json"),replacement={uri:"gs://nearyou-private-evidence/catalog/replacement-catalog-manifest.baseline.candidate.json",generation:"999",contentSha256:sha256(baseBody)};await writeFile(path,baseBody);await writeFile(receiptPath,JSON.stringify(replacement));await assert.rejects(()=>promoteLiveBaselineCatalog({candidate:path,receipt:receiptPath,output:join(directory,"replacement-catalog-manifest.baseline.reviewed.json"),...authority,expectedReceiptUri:replacement.uri,expectedReceiptGeneration:"123",expectedReceiptContentSha256:replacement.contentSha256}),/baseline catalog promotion invalid/)}finally{await rm(directory,{recursive:true,force:true})}});

test("structurally rejects otherwise self-consistent legacy policy rows and receipt replacement",async()=>{const directory=await mkdtemp(join(tmpdir(),"baseline-structural-"));try{for(const definition of ["SELECT|true","definition-6","|SELECT|true|"]){const base=candidate(),changed=base.rows.map(row=>row.kind==="policy"?{...row,definition}:row),value={...base,rows:changed,catalogChecksum:sha256(JSON.stringify(changed))},body=`${JSON.stringify(value,null,2)}\n`,candidatePath=join(directory,`${Math.random()}-catalog-manifest.baseline.candidate.json`),receiptPath=join(directory,`${Math.random()}-catalog-manifest.baseline.receipt.json`),receipt={uri:`gs://nearyou-private-evidence/catalog/${Math.random()}-catalog-manifest.baseline.candidate.json`,generation:"123",contentSha256:sha256(body)};await writeFile(candidatePath,body);await writeFile(receiptPath,JSON.stringify(receipt));await assert.rejects(()=>promoteLiveBaselineCatalog({candidate:candidatePath,receipt:receiptPath,output:join(directory,`${Math.random()}-catalog-manifest.baseline.reviewed.json`),...authority,expectedReceiptUri:receipt.uri,expectedReceiptGeneration:receipt.generation,expectedReceiptContentSha256:receipt.contentSha256}),/baseline catalog promotion invalid/)}const value=candidate(),body=`${JSON.stringify(value,null,2)}\n`,candidatePath=join(directory,"replace-catalog-manifest.baseline.candidate.json"),receiptPath=join(directory,"replace-catalog-manifest.baseline.receipt.json"),receipt={uri:"gs://nearyou-private-evidence/catalog/replace-catalog-manifest.baseline.candidate.json",generation:"999",contentSha256:sha256(body)};await writeFile(candidatePath,body);await writeFile(receiptPath,JSON.stringify(receipt));await assert.rejects(()=>promoteLiveBaselineCatalog({candidate:candidatePath,receipt:receiptPath,output:join(directory,"replace-catalog-manifest.baseline.reviewed.json"),...authority,expectedReceiptUri:receipt.uri,expectedReceiptGeneration:"123",expectedReceiptContentSha256:receipt.contentSha256}),/baseline catalog promotion invalid/)}finally{await rm(directory,{recursive:true,force:true})}});

test("promotes exact allowlisted retired lineage while rejecting arbitrary and 0007 ledgers",async()=>{const directory=await mkdtemp(join(tmpdir(),"baseline-lineage-"));try{const retired=["ae9a5e8f26190063382d76eae25565a6a991523edf6ceefa1abd74b1fd88a194","7ec295cb252f9d8cf54d951e899a59ddb834a1204de951a7d967eeeaf67c11f8","ed449236853519c58fabbd13eca2587c515447bdff81b3a6153d9afe0436aede","481c48d0b1ca224decdf5b049325ec44c048b7dcc90572c24a66dd2d1e5301c9"],base=candidate(),retiredLedger=base.provenance.migrationLedger.map((row,index)=>index<4?{...row,checksum:retired[index]}:row),makeValue=actual=>{const provenance={...base.provenance,migrationLedger:actual,migrationLedgerChecksum:sha256(actual.map(row=>`${row.id}:${row.checksum}`).join("\n"))};return{...base,provenance,provenanceChecksum:sha256(JSON.stringify(provenance))}},attempt=async(name,value,shouldPass)=>{const body=`${JSON.stringify(value,null,2)}\n`,candidatePath=join(directory,`${name}-catalog-manifest.baseline.candidate.json`),receiptPath=join(directory,`${name}-catalog-manifest.baseline.receipt.json`),output=join(directory,`${name}-catalog-manifest.baseline.reviewed.json`),receipt={uri:`gs://nearyou-private-evidence/catalog/${name}-catalog-manifest.baseline.candidate.json`,generation:"123",contentSha256:sha256(body)},input={candidate:candidatePath,receipt:receiptPath,output,...authority,expectedReceiptUri:receipt.uri,expectedReceiptGeneration:receipt.generation,expectedReceiptContentSha256:receipt.contentSha256};await writeFile(candidatePath,body);await writeFile(receiptPath,JSON.stringify(receipt));if(shouldPass)assert.equal((await promoteLiveBaselineCatalog(input)).migrationHead,"0006_private_canary_observation");else await assert.rejects(()=>promoteLiveBaselineCatalog(input),/baseline catalog promotion invalid/)};await attempt("retired",makeValue(retiredLedger),true);await attempt("arbitrary",makeValue(retiredLedger.map((row,index)=>index===0?{...row,checksum:"f".repeat(64)}:row)),false);await attempt("with-0007",makeValue([...retiredLedger,{id:"0007_private_tester_deployment_manifest",checksum:"e".repeat(64)}]),false)}finally{await rm(directory,{recursive:true,force:true})}});
