import assert from "node:assert/strict";
import test from "node:test";
import {createPkceSession,readClaimedMobileCallback} from "../mobile/src/auth.ts";
import {createOfflineCache,purgeOfflineSession} from "../mobile/src/offline-cache.ts";
import {applyRevenueCatEvent,offlineEntitlementDecision,parseRevenueCatEnvelope,reconcileRevenueCatClaim} from "../lib/revenuecat-worker.ts";
import {readFileSync} from "node:fs";
import {DatabaseSync} from "node:sqlite";
import {parseRevenueCatEntitlementEvent} from "../lib/platform-release.ts";

test("mobile auth binds PKCE state nonce provider and claimed HTTPS callback",async()=>{let seed=6;const random=n=>new Uint8Array(n).fill(++seed),session=await createPkceSession("apple",random);assert.equal(session.challengeMethod,"S256");assert.notEqual(session.verifier,session.challenge);assert.equal(readClaimedMobileCallback(new URL(`https://nearyou.example/mobile/auth/callback?state=${session.state}&code=opaque`),{host:"nearyou.example",path:"/mobile/auth/callback"}).code,"opaque");assert.throws(()=>readClaimedMobileCallback(new URL(`nearyou://mobile/auth/callback?state=${session.state}&code=x`),{host:"nearyou.example",path:"/mobile/auth/callback"}),/link/);assert.throws(()=>readClaimedMobileCallback(new URL(`https://evil.example/mobile/auth/callback?state=${session.state}&code=x`),{host:"nearyou.example",path:"/mobile/auth/callback"}),/link/);});

test("offline cache production entrypoint does not accept structural device keys",()=>{const key={alias:"native",hardwareBacked:true,accountBinding:"a".repeat(64),encrypt:async()=>({iv:new Uint8Array(12),ciphertext:new Uint8Array(16)}),decrypt:async()=>new Uint8Array(),delete:async()=>{}};const files={write:async()=>{},read:async()=>null,deleteAll:async()=>{}};assert.throws(()=>createOfflineCache(key,files,{verifyRights:async()=>true,purgeJournal:{load:async()=>null,save:async()=>{},clear:async()=>{}}}),/attested/);assert.equal(typeof purgeOfflineSession,"function")});

test("offline cache rejects structural keys and missing durable security",()=>{const fake={alias:"native",hardwareBacked:true,accountBinding:"a".repeat(64),encrypt:async()=>({iv:new Uint8Array(12),ciphertext:new Uint8Array(16)}),decrypt:async()=>new Uint8Array(),delete:async()=>{}};const files={write:async()=>{},read:async()=>null,deleteAll:async()=>{}};assert.throws(()=>createOfflineCache(fake,files),/attested|security/);});

test("mobile runtime stays dark and durable entitlement schema separates claims from projection",()=>{const route=readFileSync(new URL("../app/api/webhooks/revenuecat/route.ts",import.meta.url),"utf8"),sql=readFileSync(new URL("../drizzle/0019_mobile_entitlement_runtime.sql",import.meta.url),"utf8");assert.match(route,/MOBILE_REVENUECAT_ENABLED=false as const/);assert.ok(route.indexOf("verifyRevenueCatAuthorization")<route.indexOf("JSON.parse"));assert.match(sql,/mobile_entitlement_event_claims/);assert.match(sql,/mobile_entitlement_projection/);assert.match(sql,/payload_checksum/);});

test("offline restore fails closed on revocation, expiry, and stale verification",()=>{assert.deepEqual(offlineEntitlementDecision({status:"revoked",validUntil:null,now:10,lastVerifiedAt:9}),{allowed:false,purge:true});assert.deepEqual(offlineEntitlementDecision({status:"active",validUntil:9,now:10,lastVerifiedAt:9}),{allowed:false,purge:true});assert.deepEqual(offlineEntitlementDecision({status:"grace",validUntil:1000000000,now:90000000,lastVerifiedAt:1}),{allowed:false,purge:false,reason:"online_verification_required"});});
test("RevenueCat parser rejects envelope drift",()=>{const event={id:"evt",appId:"app",appUserId:"user",environment:"PRODUCTION",productId:"plus",entitlementId:"plus",eventType:"RENEWAL",occurredAtMs:1,expiresAtMs:2};assert.deepEqual(parseRevenueCatEnvelope(JSON.stringify(event)),event);assert.throws(()=>parseRevenueCatEnvelope(JSON.stringify({...event,extra:true})),/invalid/);});
test("nested provider body is parsed before durable canonical replay",()=>{const provider={event:{id:"rc_nested",app_id:"app_nearyou",environment:"SANDBOX",product_id:"plus",entitlement_ids:["plus"],app_user_id:"rcusr_0123456789abcdef0123456789abcdef",event_timestamp_ms:200,type:"INITIAL_PURCHASE",expiration_at_ms:999}},raw=JSON.stringify(provider),event=parseRevenueCatEntitlementEvent(provider,{appIds:["app_nearyou"],productIds:["plus"],entitlementIds:["plus"],environment:"SANDBOX"});assert.notEqual(raw,JSON.stringify(event));assert.deepEqual(parseRevenueCatEnvelope(JSON.stringify(event)),event);});

test("RevenueCat unbound retry reaches dead letter without a lingering lease",async()=>{const sqlite=new DatabaseSync(":memory:");sqlite.exec("CREATE TABLE mobile_account_bindings(app_user_id_hash TEXT PRIMARY KEY,household_id TEXT,revoked_at INTEGER,app_id TEXT,environment TEXT,status TEXT);CREATE TABLE mobile_entitlement_events(id TEXT PRIMARY KEY,household_id TEXT,app_id TEXT,environment TEXT,product_id TEXT,entitlement_id TEXT,app_user_id_hash TEXT,event_type TEXT,occurred_at INTEGER,payload_checksum TEXT,processed_at INTEGER);CREATE TABLE mobile_entitlement_projection(household_id TEXT,entitlement_id TEXT,status TEXT,product_id TEXT,environment TEXT,last_occurred_at INTEGER,last_event_id TEXT,rights_version INTEGER,valid_until INTEGER,updated_at INTEGER,PRIMARY KEY(household_id,entitlement_id));CREATE TABLE mobile_entitlement_event_claims(id TEXT PRIMARY KEY,payload_checksum TEXT,canonical_payload TEXT,canonical_payload_checksum TEXT,status TEXT,attempt_token TEXT,attempts INTEGER,lease_expires_at INTEGER,next_attempt_at INTEGER,error_code TEXT,created_at INTEGER,updated_at INTEGER)");const event={id:"rc_unbound",appId:"app_nearyou",appUserId:"rcusr_0123456789abcdef0123456789abcdef",environment:"SANDBOX",productId:"plus",entitlementId:"plus",eventType:"INITIAL_PURCHASE",occurredAtMs:100,expiresAtMs:1000},db=new D1(sqlite),clock={now:async()=>1000};assert.deepEqual(await applyRevenueCatEvent(db,event,JSON.stringify({event}),clock),{status:"retry_wait"});sqlite.prepare("UPDATE mobile_entitlement_event_claims SET attempts=7,next_attempt_at=999").run();assert.deepEqual(await reconcileRevenueCatClaim(db,clock),{status:"dead_letter"});assert.deepEqual({...sqlite.prepare("SELECT status,attempts,attempt_token,next_attempt_at FROM mobile_entitlement_event_claims").get()},{status:"dead_letter",attempts:8,attempt_token:null,next_attempt_at:null});});

class Bound{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args}bind(...args){return new Bound(this.db,this.sql,args)}async all(){return{results:this.db.prepare(this.sql).all(...this.args)}}async run(){const result=this.db.prepare(this.sql).run(...this.args);return{meta:{changes:Number(result.changes)}}}}
class D1{constructor(db,lose=false){this.db=db;this.lose=lose}prepare(sql){return new Bound(this.db,sql)}async batch(items){this.db.exec("BEGIN");try{const results=[];for(const item of items)results.push(await item.run());this.db.exec("COMMIT");if(this.lose){this.lose=false;throw new Error("lost response")}return results}catch(error){if(this.db.isTransaction)this.db.exec("ROLLBACK");throw error}}}
test("RevenueCat transition is atomic, ordered, and recovers a committed lost response",async()=>{const sqlite=new DatabaseSync(":memory:");sqlite.exec("CREATE TABLE mobile_account_bindings(app_user_id_hash TEXT PRIMARY KEY,household_id TEXT,revoked_at INTEGER,app_id TEXT,environment TEXT,status TEXT);CREATE TABLE mobile_entitlement_events(id TEXT PRIMARY KEY,household_id TEXT,app_id TEXT,environment TEXT,product_id TEXT,entitlement_id TEXT,app_user_id_hash TEXT,event_type TEXT,occurred_at INTEGER,payload_checksum TEXT,processed_at INTEGER);CREATE TABLE mobile_entitlement_projection(household_id TEXT,entitlement_id TEXT,status TEXT,product_id TEXT,environment TEXT,last_occurred_at INTEGER,last_event_id TEXT,rights_version INTEGER,valid_until INTEGER,updated_at INTEGER,PRIMARY KEY(household_id,entitlement_id));CREATE TABLE mobile_entitlement_event_claims(id TEXT PRIMARY KEY,payload_checksum TEXT,canonical_payload TEXT,canonical_payload_checksum TEXT,status TEXT,attempt_token TEXT,attempts INTEGER,lease_expires_at INTEGER,next_attempt_at INTEGER,error_code TEXT,created_at INTEGER,updated_at INTEGER)");const appUser="rcusr_0123456789abcdef0123456789abcdef",hex=Buffer.from(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(appUser))).toString("hex");sqlite.prepare("INSERT INTO mobile_account_bindings VALUES(?,?,?,?,?,?)").run(hex,"hh_1",null,"app_nearyou","SANDBOX","active");const event={id:"rc_one",appId:"app_nearyou",appUserId:appUser,environment:"SANDBOX",productId:"plus",entitlementId:"plus",eventType:"INITIAL_PURCHASE",occurredAtMs:100,expiresAtMs:1000};await assert.rejects(()=>applyRevenueCatEvent(new D1(sqlite,true),event,JSON.stringify(event)),/lost response/);assert.deepEqual(await applyRevenueCatEvent(new D1(sqlite),event,JSON.stringify(event)),{status:"replayed"});assert.equal(sqlite.prepare("SELECT count(*) n FROM mobile_entitlement_events").get().n,1);await applyRevenueCatEvent(new D1(sqlite),{...event,id:"rc_two",eventType:"CANCELLATION"},JSON.stringify({...event,id:"rc_two",eventType:"CANCELLATION"}));assert.deepEqual({...sqlite.prepare("SELECT last_event_id,status FROM mobile_entitlement_projection").get()},{last_event_id:"rc_two",status:"canceled"});});
