import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PRIVATE_CANARY_D1_OBSERVATION_SQL } from "../lib/private-canary-d1-query.ts";

test("deployment CLI uses production trust, PG nonce, authenticated D1 and exclusive output",async()=>{const source=await readFile(new URL("../scripts/private-canary-live.ts",import.meta.url),"utf8");for(const required of ["verifyReleaseEvidence","CloudKmsPublicKeyClient","PostgresNonceStore","metadata.google.internal","authorization:`Bearer ${token}`","flag:\"wx\"","READINESS_CONTROL_DATABASE_URL","D1_CANARY_SMOKE_URL"])assert.match(source,new RegExp(required.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(source,/runPrivateCanarySmoke|GOOGLE_OAUTH_ACCESS_TOKEN/)});

test("rollback claim is exact-release, household, interval and nonce bound before signed artifact acceptance",async()=>{const source=await readFile(new URL("../scripts/private-canary-live.ts",import.meta.url),"utf8");for(const required of ["invitedHouseholdHash","deniedHouseholdHash","startedAt","endedAt","nonce","rollbackArtifactDigest"])assert.match(source,new RegExp(required));});

test("concrete D1 and PostgreSQL loaders are narrow, authenticated and server-time based",async()=>{const route=await readFile(new URL("../app/api/internal/private-canary-observation/route.ts",import.meta.url),"utf8"),sql=await readFile(new URL("../postgres/migrations/0006_private_canary_observation.sql",import.meta.url),"utf8");assert.match(route,/EVIDENCE_COLLECTION_APPROVED!=="true"/);assert.match(route,/createServiceOidcAuthenticator/);assert.match(PRIVATE_CANARY_D1_OBSERVATION_SQL,/d1_migrations/);assert.match(PRIVATE_CANARY_D1_OBSERVATION_SQL,/operational_outcome_outbox/);for(const required of ["SECURITY DEFINER","statement_timestamp()","REVOKE ALL","nearyou_release_verifier","p_denied_hash"])assert.match(sql,new RegExp(required.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});

test("live wrapper unwraps scalar JSONB and rejects stale or mismatched clocks and malicious endpoints",async()=>{const source=await readFile(new URL("../scripts/private-canary-live.ts",import.meta.url),"utf8");for(const invariant of [/ AS rollout/,/ AS provider/,/unwrapPrivateCanaryJsonb/,/Number\(rollout\.observedAt\)!==observedAt/,/Number\(provider\.observedAt\)!==observedAt/,/rollback\.startedAt<envelope\.claims\.notBefore/,/rollback\.endedAt>envelope\.claims\.issuedAt/,/observedAt-rollback\.endedAt>300000/,/url\.username\|\|url\.password\|\|url\.search\|\|url\.hash/,/url\.origin!==aud\.origin/,/CLOUD_SQL_IAM_CONNECTOR/,/cloud-sql-auth-proxy/])assert.match(source,invariant)});

test("Story readiness is exact active-release evidence and proxy configuration is reviewed",async()=>{const sql=await readFile(new URL("../postgres/migrations/0006_private_canary_observation.sql",import.meta.url),"utf8"),cli=await readFile(new URL("../scripts/private-canary-live.ts",import.meta.url),"utf8"),args=await readFile(new URL("../infra/production/cloud-sql-auth-proxy.args",import.meta.url),"utf8");for(const value of ["product_rollout_state","e.evidence_digest=s.evidence_digest","worker","scheduler","processor","provider","s.mode='canary'","NOT s.kill_switch"])assert.match(sql,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(args,/--auto-iam-authn/);assert.match(cli,/url\.password/);assert.match(cli,/CLOUD_SQL_PROXY_ARGS_CHECKSUM/)});

test("canary observation remains unavailable while its Sites schema is deferred",async()=>{await assert.rejects(readFile(new URL("../drizzle/0026_canary_entitlements.sql",import.meta.url),"utf8"),/ENOENT/);const route=await readFile(new URL("../app/api/internal/canary-entitlement/route.ts",import.meta.url),"utf8");assert.match(route,/ROUTE_ENABLED = false as const/)});
