import assert from "node:assert/strict";
import test from "node:test";
import {DatabaseSync} from "node:sqlite";
import {execFileSync} from "node:child_process";
import {readFileSync,readdirSync} from "node:fs";
import {SITES_D1_FORWARD_ARTIFACT} from "../lib/sites-d1-forward-artifact.generated.ts";
import {SITES_D1_OPERATION_BOOTSTRAP,SitesD1ForwardOperation,splitD1Migration} from "../lib/sites-d1-forward-operation.ts";

class Bound{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args}bind(...args){return new Bound(this.db,this.sql,args)}async all(){return{results:this.db.prepare(this.sql).all(...this.args)}}async first(){return this.db.prepare(this.sql).get(...this.args)??null}async run(){const r=this.db.prepare(this.sql).run(...this.args);return{meta:{changes:Number(r.changes)}}}}
class D1{constructor(db,loseAt=-1){this.db=db;this.loseAt=loseAt;this.calls=0}prepare(sql){return new Bound(this.db,sql)}async batch(statements){this.db.exec("BEGIN");try{const out=[];for(const s of statements)out.push(await s.run());this.db.exec("COMMIT");this.calls++;if(this.calls===this.loseAt)throw new Error("lost response");return out}catch(e){if(this.db.isTransaction)this.db.exec("ROLLBACK");throw e}}}
const digest=async value=>Buffer.from(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))).toString("hex");
const migrationSources=[{id:"0017_a",sql:"CREATE TABLE a(id TEXT PRIMARY KEY);\n--> statement-breakpoint\nCREATE INDEX a_id ON a(id);"},{id:"0018_b",sql:"CREATE TABLE b(id TEXT PRIMARY KEY);"}],migrations=await Promise.all(migrationSources.map(async m=>({...m,sha256:await digest(m.sql)})));
function fixture(loseAt=-1){const sqlite=new DatabaseSync(":memory:");sqlite.exec("CREATE TABLE d1_migrations(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,applied_at TEXT NOT NULL);INSERT INTO d1_migrations VALUES(1,'0016_live','2026-08-17 00:00:00')");return{sqlite,db:new D1(sqlite,loseAt)}}
const input={operationId:"d1-forward:rel_test_20260817",releaseId:"rel_test_20260817",phase:"0017-0025",issuedAt:1787000000000,migrations,reviewedMigrations:migrations};
async function testCheckpoints(){const {sqlite}=fixture(),values=[],capture=async head=>{const rows=sqlite.prepare("SELECT type,name,tbl_name AS tableName,sql FROM sqlite_schema WHERE type IN ('table','index','trigger','view') ORDER BY type,name,tbl_name").all().map(row=>({...row}));values.push({head,objectCount:rows.length,definitionsSha256:await digest(JSON.stringify(rows)),providerObjects:[]})};await capture("0016");for(const sql of SITES_D1_OPERATION_BOOTSTRAP)sqlite.exec(sql);await capture("0016+operation");for(const migration of migrations){for(const sql of splitD1Migration(migration.sql))sqlite.exec(sql);await capture(migration.id.slice(0,4))}return values}const safeInput={...input,schemaCheckpoints:await testCheckpoints()};

test("splits only explicit breakpoints and rejects transaction control",()=>{assert.equal(splitD1Migration(migrations[0].sql).length,2);assert.throws(()=>splitD1Migration("BEGIN; CREATE TABLE x(a); COMMIT;"),/transaction control/)});
test("applies each exact migration and immutable evidence in one atomic D1 batch",async()=>{const {sqlite,db}=fixture();const result=await new SitesD1ForwardOperation(db).run(safeInput);assert.equal(result.status,"complete");assert.deepEqual(sqlite.prepare("SELECT migration_id,source_sha256 FROM nearyou_sites_d1_operation_migrations ORDER BY ordinal").all().map(row=>({...row})),migrations.map(m=>({migration_id:m.id,source_sha256:m.sha256})));assert.equal(sqlite.prepare("SELECT status FROM nearyou_sites_d1_operations").get().status,"complete");assert.throws(()=>sqlite.prepare("DELETE FROM nearyou_sites_d1_operation_migrations").run(),/immutable/)});
test("lost bootstrap, any migration, or completion response resumes from exact durable state",async()=>{for(const lost of [1,2,3,4]){const {sqlite,db}=fixture(lost);await assert.rejects(()=>new SitesD1ForwardOperation(db).run(safeInput),/lost response/);const recovered=await new SitesD1ForwardOperation(db).run(safeInput);assert.equal(recovered.status,"complete");assert.equal(sqlite.prepare("SELECT count(*) n FROM nearyou_sites_d1_operation_migrations").get().n,2)}});
test("fails closed on concurrent or substituted operation",async()=>{const first=fixture();await new SitesD1ForwardOperation(first.db).run(safeInput);await assert.rejects(()=>new SitesD1ForwardOperation(first.db).run({...safeInput,operationId:"d1-forward:other"}),/operation conflict/);const swapped=fixture();await assert.rejects(()=>new SitesD1ForwardOperation(swapped.db).run({...safeInput,migrations:[{...migrations[0],sql:"CREATE TABLE evil(id TEXT)"},migrations[1]]}),/source checksum/)});
test("uses exact schema truth and hashes same-name rogue schema objects without reading provider ledger rows",async()=>{
  const rogue=fixture();
  rogue.sqlite.exec("CREATE TRIGGER d1_migrations BEFORE INSERT ON d1_migrations BEGIN SELECT 1; END");
  await assert.rejects(()=>new SitesD1ForwardOperation(rogue.db).run(safeInput),/schema checkpoint drift/);
});
test("0017-0025 operation cannot include 0026 and 0026 requires a separate exact authorization",async()=>{const f=fixture(),sql="CREATE TABLE c(id TEXT)",sha256=await digest(sql),reviewedMigrations=[...SITES_D1_FORWARD_ARTIFACT.migrations];await assert.rejects(()=>new SitesD1ForwardOperation(f.db).run({...safeInput,reviewedMigrations,migrations:[...migrations,{id:"0026_canary",sha256,sql}]}),/phase boundary/);await assert.rejects(()=>new SitesD1ForwardOperation(f.db).run({...safeInput,reviewedMigrations,phase:"0026",migrations:[{id:"0026_canary",sha256,sql}]}),/authorization/)});
test("generated production statements and every 0016-0026 schema checkpoint are reproducible",()=>{execFileSync(process.execPath,["--import","tsx","scripts/generate-sites-d1-forward-artifact.ts","--check"],{cwd:new URL("..",import.meta.url)});const artifact=readFileSync(new URL("../lib/sites-d1-forward-artifact.generated.ts",import.meta.url),"utf8");for(let head=16;head<=26;head++)assert.match(artifact,new RegExp(`\\"head\\":\\"00${head}[^\\"]*\\"`));assert.match(artifact,/canary_entitlement_audit_update_guard/);assert.match(artifact,/canary_entitlement_audit_delete_guard/)});
test("production artifact applies the exact 0017-0025 and separately authorized 0026 phases",async()=>{
  const sqlite=new DatabaseSync(":memory:");
  const prefix=readdirSync(new URL("../drizzle",import.meta.url)).filter(file=>/^00(?:0[0-9]|1[0-6])_.*\.sql$/.test(file)).sort();
  for(const file of prefix)sqlite.exec(readFileSync(new URL(`../drizzle/${file}`,import.meta.url),"utf8"));
  sqlite.exec("CREATE TABLE d1_migrations(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,applied_at TEXT NOT NULL);CREATE TABLE _cf_METADATA(key TEXT,value TEXT);CREATE TABLE seq_seed(id INTEGER PRIMARY KEY AUTOINCREMENT);DROP TABLE seq_seed;ANALYZE");
  for(const [index,file] of prefix.entries())sqlite.prepare("INSERT INTO d1_migrations VALUES(?,?,CURRENT_TIMESTAMP)").run(index+1,file.replace(/\.sql$/, ""));
  const db=new D1(sqlite);
  const forward=SITES_D1_FORWARD_ARTIFACT.migrations.filter(value=>Number(value.id.slice(0,4))<=25).map(({id,sha256,sql})=>({id,sha256,sql}));
  const common={releaseId:"rel_prod_artifact_20260817",issuedAt:1787000000000,reviewedMigrations:[...SITES_D1_FORWARD_ARTIFACT.migrations],schemaCheckpoints:[...SITES_D1_FORWARD_ARTIFACT.schemaCheckpoints]};
  await new SitesD1ForwardOperation(db).run({...common,operationId:"d1-forward:prod-artifact",phase:"0017-0025",migrations:forward});
  const migration0026=SITES_D1_FORWARD_ARTIFACT.migrations.at(-1);
  const authorization={purpose:"d1-0026-separate-authorization",releaseId:common.releaseId,operationId:"d1-forward:prod-0026",migrationSha256:migration0026.sha256};
  await new SitesD1ForwardOperation(db).run({...common,operationId:authorization.operationId,phase:"0026",migrations:[{id:migration0026.id,sha256:migration0026.sha256,sql:migration0026.sql}],authorization});
  assert.equal((await new SitesD1ForwardOperation(db).run({...common,operationId:authorization.operationId,phase:"0026",migrations:[{id:migration0026.id,sha256:migration0026.sha256,sql:migration0026.sql}],authorization})).status,"complete");
  assert.equal(sqlite.prepare("SELECT count(*) n FROM d1_migrations").get().n,17);
  assert.equal(sqlite.prepare("SELECT count(*) n FROM nearyou_sites_d1_operations WHERE status='complete'").get().n,2);
});
test("admin route is literal-dark and authenticates before parsing or constructing the operation",()=>{const route=readFileSync(new URL("../app/api/internal/sites-d1-forward/route.ts",import.meta.url),"utf8"),auth=route.indexOf("createServiceOidcAuthenticator"),parse=route.indexOf("request.json()"),operation=route.indexOf("new SitesD1ForwardOperation");assert.match(route,/ROUTE_ENABLED = false as const/);assert.ok(auth<parse&&parse<operation);assert.match(route,/D1_FORWARD_BASELINE_SCHEMA_SHA256/);assert.match(route,/D1_0026_AUTHORIZATION_SHA256/);assert.doesNotMatch(route,/d1_migrations/)});
