"use client";
import { useEffect, useMemo, useState } from "react";

type Contributor={id:string;display_name?:string;displayName?:string;status:string};
type Consent={id:string;contributor_id:string;kind:"recording"|"transcription";status:string};
type Export={id:string;status:string;parts?:Array<{id:string;logical_path?:string;downloadUrl:string}>};

async function sha256(file:File){const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,"0")).join("");}
async function duration(file:File){const url=URL.createObjectURL(file);try{return await new Promise<number>((resolve,reject)=>{const audio=new Audio();audio.preload="metadata";audio.onloadedmetadata=()=>resolve(Math.round(audio.duration*1000));audio.onerror=()=>reject(new Error("audio_metadata_unavailable"));audio.src=url;});}finally{URL.revokeObjectURL(url);}}

export function LegacyArchiveWorkbench({householdId,contributors,canManage}:{householdId:string;contributors:Contributor[];canManage:boolean}){
  const[consents,setConsents]=useState<Consent[]>([]),[exports,setExports]=useState<Export[]>([]),[message,setMessage]=useState(""),[challenge,setChallenge]=useState<{id:string;phrase:string;contributorId:string;kind:"recording"|"transcription"}|null>(null),[jobId,setJobId]=useState(""),[jobStatus,setJobStatus]=useState(""),[stepUpCode,setStepUpCode]=useState("");
  const baseHeaders=useMemo(()=>({"x-nearyou-household-id":householdId}),[householdId]);
  async function refresh(){const[c,e]=await Promise.all([fetch("/api/v1/legacy/consents",{headers:baseHeaders,cache:"no-store"}),fetch("/api/v1/legacy/exports",{headers:baseHeaders,cache:"no-store"})]);if(c.ok)setConsents(((await c.json())as{consents:Consent[]}).consents||[]);if(e.ok)setExports(((await e.json())as{exports:Export[]}).exports||[]);}
  useEffect(()=>{let active=true;void Promise.all([fetch("/api/v1/legacy/consents",{headers:baseHeaders,cache:"no-store"}),fetch("/api/v1/legacy/exports",{headers:baseHeaders,cache:"no-store"})]).then(async([c,e])=>{if(!active)return;if(c.ok)setConsents(((await c.json())as{consents:Consent[]}).consents||[]);if(e.ok)setExports(((await e.json())as{exports:Export[]}).exports||[]);});return()=>{active=false;};},[baseHeaders]);
  useEffect(()=>{if(!jobId)return;const timer=window.setInterval(()=>{void fetch(`/api/v1/jobs/${encodeURIComponent(jobId)}`,{headers:baseHeaders,cache:"no-store"}).then(async response=>{if(!response.ok)return;const body=await response.json()as{job?:{status?:string;progressStage?:string;progressPercent?:number}};const status=body.job?.status||"queued";setJobStatus(`${status} · ${body.job?.progressStage||"waiting"} · ${body.job?.progressPercent||0}%`);if(["succeeded","failed","canceled"].includes(status))window.clearInterval(timer);});},2000);return()=>window.clearInterval(timer);},[baseHeaders,jobId]);
  async function issueChallenge(form:FormData){const contributorId=String(form.get("contributorId")),kind=String(form.get("kind"))as"recording"|"transcription",response=await fetch("/api/v1/legacy/liveness-challenges",{method:"POST",headers:{...baseHeaders,"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({contributorId,kind})}),body=await response.json()as{id?:string;phrase?:string;error?:string};if(response.ok&&body.id&&body.phrase){setChallenge({id:body.id,phrase:body.phrase,contributorId,kind});setMessage("Record yourself reading the exact one-use phrase.");}else setMessage(body.error||"Liveness challenge could not be created.");}
  async function saveConsent(form:FormData){if(!challenge)return;const evidence=form.get("evidence");if(!(evidence instanceof File))return;const payload=new FormData();payload.set("contributorId",challenge.contributorId);payload.set("kind",challenge.kind);payload.set("challengeId",challenge.id);payload.set("attested","true");payload.set("evidence",evidence);const response=await fetch("/api/v1/legacy/consents",{method:"POST",headers:{...baseHeaders,"idempotency-key":crypto.randomUUID()},body:payload}),body=await response.json()as{error?:string};setMessage(response.ok?"Consent verified and saved.":body.error||"Consent could not be saved.");if(response.ok){setChallenge(null);await refresh();}}
  async function uploadRecording(form:FormData){const file=form.get("recording"),contributorId=String(form.get("contributorId")),recordingConsentId=String(form.get("recordingConsentId")),transcriptionConsentId=String(form.get("transcriptionConsentId"));if(!(file instanceof File))return;setMessage("Validating and securely uploading the recording…");try{const[digest,durationMs]=await Promise.all([sha256(file),duration(file)]),response=await fetch("/api/v1/legacy/recordings",{method:"POST",headers:{...baseHeaders,"idempotency-key":crypto.randomUUID(),"content-type":file.type,"x-content-sha256":digest,"x-nearyou-duration-ms":String(durationMs),"x-nearyou-contributor-id":contributorId,"x-nearyou-recording-consent-id":recordingConsentId,"x-nearyou-transcription-consent-id":transcriptionConsentId},body:file}),body=await response.json()as{jobId?:string;error?:string};if(!response.ok)return setMessage(body.error||"Recording could not be uploaded.");setJobId(body.jobId||"");setJobStatus("queued · waiting · 0%");setMessage("Recording saved; private transcription is queued.");}catch{setMessage("The browser could not read this audio file. Try WebM, M4A, or MP3.");}}
  async function correct(form:FormData){const response=await fetch("/api/v1/legacy/corrections",{method:"POST",headers:{...baseHeaders,"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({segmentId:form.get("segmentId"),speakerContributorId:form.get("speakerContributorId"),correctedText:form.get("correctedText"),reason:"speaker_review"})}),body=await response.json()as{error?:string};setMessage(response.ok?"Correction saved with its original transcript preserved.":body.error||"Correction could not be saved.");}
  async function revokeConsent(id:string){const response=await fetch(`/api/v1/legacy/consents/${encodeURIComponent(id)}/revoke`,{method:"POST",headers:{...baseHeaders,"idempotency-key":crypto.randomUUID()}}),body=await response.json()as{error?:string};setMessage(response.ok?"Consent revoked. New work and cached derivatives are fenced immediately.":body.error||"Consent could not be revoked.");if(response.ok)await refresh();}
  function protectedHeaders(){return{...baseHeaders,"content-type":"application/json","idempotency-key":crypto.randomUUID(),"x-nearyou-reauth-challenge":sessionStorage.getItem("nearyou:privacy:reauth-challenge")||"","x-nearyou-mfa-code":stepUpCode};}
  async function reportDeath(id:string){const response=await fetch(`/api/v1/legacy/contributors/${encodeURIComponent(id)}/lifecycle`,{method:"POST",headers:protectedHeaders(),body:JSON.stringify({action:"report_death"})}),body=await response.json()as{error?:string};setMessage(response.ok?"Death review started. Synthetic generation is fenced; original memories remain available.":body.error||"Death review could not be started.");if(response.ok)setStepUpCode("");}
  async function deleteArchive(form:FormData){const response=await fetch("/api/v1/legacy/deletions",{method:"POST",headers:protectedHeaders(),body:JSON.stringify({targetKind:"archive",confirmation:form.get("confirmation")})}),body=await response.json()as{error?:string};setMessage(response.ok?"Verified archive deletion queued.":body.error||"Archive deletion could not be requested.");if(response.ok)setStepUpCode("");}
  async function saveMetadata(form:FormData){const kind=String(form.get("kind")),payload:{[key:string]:FormDataEntryValue|null}={kind,name:form.get("name"),description:form.get("description"),relationship:form.get("relationship"),title:form.get("title"),summary:form.get("summary"),contributorId:form.get("contributorId"),sourceSegmentId:form.get("sourceSegmentId"),memoryId:form.get("memoryId"),occurredOn:form.get("occurredOn"),precision:form.get("precision")};const response=await fetch("/api/v1/legacy/archive-data",{method:"POST",headers:{...baseHeaders,"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify(payload)}),body=await response.json()as{error?:string};setMessage(response.ok?`${kind} saved to the private archive.`:body.error||"Archive metadata could not be saved.");}
  async function savePhoto(form:FormData){const photo=form.get("photo");if(!(photo instanceof File))return;const payload=new FormData();payload.set("photo",photo);payload.set("caption",String(form.get("caption")||""));const response=await fetch("/api/v1/legacy/photos",{method:"POST",headers:{...baseHeaders,"idempotency-key":crypto.randomUUID()},body:payload}),body=await response.json()as{error?:string};setMessage(response.ok?"Photo saved privately with the archive.":body.error||"Photo could not be saved.");}
  return <>
    <div aria-live="polite" className="muted">{message}</div>
    <section className="panel" style={{marginTop:20}}><h2>Voice consent</h2><p className="panel-intro">Each contributor reads a new random phrase. The original evidence is private and retained only under the consent policy.</p>{!challenge?<form action={issueChallenge}><label htmlFor="legacy-consent-person">Contributor</label><select id="legacy-consent-person" name="contributorId" required>{contributors.filter(item=>item.status==="active").map(item=><option key={item.id} value={item.id}>{item.display_name||item.displayName}</option>)}</select><label htmlFor="legacy-consent-kind">Permission</label><select id="legacy-consent-kind" name="kind"><option value="recording">Store original recordings</option><option value="transcription">Transcribe and search recordings</option></select><button className="btn btn-primary" type="submit">Create one-use phrase</button></form>:<form action={saveConsent}><p><strong>Read exactly:</strong> <span>{challenge.phrase}</span></p><label htmlFor="legacy-consent-evidence">Short recording (WebM or M4A)</label><input id="legacy-consent-evidence" name="evidence" type="file" accept="audio/webm,audio/mp4" capture required/><label><input type="checkbox" required/> I confirm this is my voice and consent to this private archive use.</label><button className="btn btn-primary" type="submit">Verify and save consent</button><button className="btn btn-secondary" type="button" onClick={()=>setChallenge(null)}>Cancel</button></form>}<ul>{consents.map(item=><li key={item.id}>{item.kind} · {item.status}</li>)}</ul></section>
    <section className="panel" style={{marginTop:20}}><h2>Add an original recording</h2><form action={uploadRecording}><label htmlFor="legacy-recording-person">Speaker</label><select id="legacy-recording-person" name="contributorId" required>{contributors.map(item=><option key={item.id} value={item.id}>{item.display_name||item.displayName}</option>)}</select><label htmlFor="legacy-recording-consent">Recording consent</label><select id="legacy-recording-consent" name="recordingConsentId" required>{consents.filter(item=>item.kind==="recording"&&item.status==="active").map(item=><option key={item.id} value={item.id}>{item.id}</option>)}</select><label htmlFor="legacy-transcription-consent">Transcription consent</label><select id="legacy-transcription-consent" name="transcriptionConsentId" required>{consents.filter(item=>item.kind==="transcription"&&item.status==="active").map(item=><option key={item.id} value={item.id}>{item.id}</option>)}</select><label htmlFor="legacy-recording-file">Audio file</label><input id="legacy-recording-file" name="recording" type="file" accept="audio/webm,audio/mp4,audio/mpeg" capture required/><button className="btn btn-primary" type="submit">Upload and transcribe</button></form>{jobStatus&&<p role="status">Transcription: {jobStatus}</p>}</section>
    {canManage&&<section className="panel" style={{marginTop:20}}><h2>Correct a transcript</h2><p className="panel-intro">Corrections are append-only; the original words and recording remain preserved.</p><form action={correct}><label htmlFor="legacy-segment-id">Transcript segment ID</label><input id="legacy-segment-id" name="segmentId" required/><label htmlFor="legacy-corrected-speaker">Verified speaker</label><select id="legacy-corrected-speaker" name="speakerContributorId" required>{contributors.map(item=><option key={item.id} value={item.id}>{item.display_name||item.displayName}</option>)}</select><label htmlFor="legacy-corrected-text">Corrected transcript</label><textarea id="legacy-corrected-text" name="correctedText" maxLength={4000} required/><button className="btn btn-secondary" type="submit">Save correction</button></form></section>}
    {exports.length>0&&<section className="panel" style={{marginTop:20}}><h2>Portable exports</h2><ul>{exports.map(item=><li key={item.id}>{item.status}{item.parts?.map(part=><span key={part.id}> · <a href={part.downloadUrl}>{part.logical_path||"Download part"}</a></span>)}</li>)}</ul></section>}
    <section className="panel" style={{marginTop:20}}><h2>Consent rights</h2><ul>{consents.map(item=><li key={`right-${item.id}`}>{item.kind} · {item.status}{item.status==="active"&&<button className="btn btn-secondary" type="button" onClick={()=>void revokeConsent(item.id)}>Revoke consent</button>}</li>)}</ul></section>
    {canManage&&<section className="panel" style={{marginTop:20}}><h2>Lifecycle and deletion</h2><p className="panel-intro">These controls require the fresh sign-in saved from Account and a current authenticator code.</p><label htmlFor="legacy-workbench-step-up">Authenticator code</label><input id="legacy-workbench-step-up" value={stepUpCode} onChange={event=>setStepUpCode(event.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code"/><ul>{contributors.filter(item=>item.status==="active").map(item=><li key={`lifecycle-${item.id}`}>{item.display_name||item.displayName} <button className="btn btn-secondary" type="button" disabled={stepUpCode.length!==6} onClick={()=>void reportDeath(item.id)}>Report death for review</button></li>)}</ul><form action={deleteArchive}><label htmlFor="legacy-delete-confirmation">Type DELETE ARCHIVE DATA</label><input id="legacy-delete-confirmation" name="confirmation" pattern="DELETE ARCHIVE DATA" required/><button className="btn btn-secondary" type="submit" disabled={stepUpCode.length!==6}>Request verified archive deletion</button></form><a href="/account">Complete fresh sign-in</a></section>}
    {canManage&&<section className="panel" style={{marginTop:20}}><h2>Organize the archive</h2><p className="panel-intro">Create people, places, tags, collections, sourced memories, and timeline entries. Memories require the transcript segment that supports them.</p><form action={saveMetadata}><label htmlFor="legacy-metadata-kind">Item type</label><select id="legacy-metadata-kind" name="kind"><option value="person">Person</option><option value="place">Place</option><option value="tag">Tag</option><option value="collection">Collection</option><option value="memory">Sourced memory</option><option value="timeline">Timeline event</option></select><label htmlFor="legacy-metadata-name">Name (people, places, tags, collections)</label><input id="legacy-metadata-name" name="name" maxLength={160}/><label htmlFor="legacy-metadata-title">Title (memory or timeline)</label><input id="legacy-metadata-title" name="title" maxLength={200}/><label htmlFor="legacy-metadata-description">Description or summary</label><textarea id="legacy-metadata-description" name="description" maxLength={1000}/><input type="hidden" name="summary" value="Family archive entry"/><label htmlFor="legacy-metadata-contributor">Memory contributor</label><select id="legacy-metadata-contributor" name="contributorId"><option value="">Not applicable</option>{contributors.map(item=><option key={`meta-${item.id}`} value={item.id}>{item.display_name||item.displayName}</option>)}</select><label htmlFor="legacy-source-segment">Supporting segment ID</label><input id="legacy-source-segment" name="sourceSegmentId"/><label htmlFor="legacy-memory-id">Memory ID for timeline</label><input id="legacy-memory-id" name="memoryId"/><label htmlFor="legacy-occurred-on">Timeline date or year</label><input id="legacy-occurred-on" name="occurredOn"/><input type="hidden" name="precision" value="unknown"/><button className="btn btn-secondary" type="submit">Save archive item</button></form></section>}
    {canManage&&<section className="panel" style={{marginTop:20}}><h2>Photos</h2><form action={savePhoto}><label htmlFor="legacy-photo-file">JPEG or PNG</label><input id="legacy-photo-file" name="photo" type="file" accept="image/jpeg,image/png" required/><label htmlFor="legacy-photo-caption">Caption</label><input id="legacy-photo-caption" name="caption" maxLength={500}/><button className="btn btn-secondary" type="submit">Save private photo</button></form></section>}
  </>;
}
