"use client";
/* Original recordings render their adjacent transcript citation on screen. */
/* eslint-disable jsx-a11y/media-has-caption */
import { useEffect, useState } from "react";
import { LegacyArchiveWorkbench } from "./LegacyArchiveWorkbench";

type Contributor = { id: string; display_name?: string; displayName?: string; relationship?: string; status: string };
type Interview = { id:string; contributor_id:string; title:string; status:string };
export function LegacyDashboard() {
  const [householdId,setHouseholdId]=useState("");const[linkedContributorId,setLinkedContributorId]=useState("");
  const [contributors, setContributors] = useState<Contributor[]>([]);const[interviews,setInterviews]=useState<Interview[]>([]); const [permissions, setPermissions] = useState({ manage: false, contributeSelf: false, read: false, custody: false,bootstrapCustody:false }); const [message, setMessage] = useState("");const[mfa,setMfa]=useState<{id:string;uri:string}|null>(null);const[recoveryCodes,setRecoveryCodes]=useState<string[]>([]);const[reauthChallenge,setReauthChallenge]=useState(()=>typeof window==="undefined"?"":sessionStorage.getItem("nearyou:privacy:reauth-challenge")||"");const[stepUpCode,setStepUpCode]=useState(""); const [answer, setAnswer] = useState<{ answer: string; label: string; sources?: Array<{ recordingId: string; transcriptId: string | null; recordedAt: string; startMs: number; endMs: number; provenance: string; playable: boolean }> } | null>(null);
  async function load() { const response = await fetch("/api/v1/legacy", { cache: "no-store" }); if (response.ok) { const body = await response.json() as {householdId?:string;linkedContributorId?:string; contributors?: Contributor[];interviews?:Interview[]; permissions?: { manage: boolean; contributeSelf: boolean; read: boolean; custody: boolean;bootstrapCustody:boolean } };setHouseholdId(body.householdId||"");setLinkedContributorId(body.linkedContributorId||""); setContributors(body.contributors || []);setInterviews(body.interviews||[]); setPermissions(body.permissions || { manage: false, contributeSelf: false, read: false, custody: false,bootstrapCustody:false }); } }
  useEffect(() => { let active=true;void fetch("/api/v1/legacy",{cache:"no-store"}).then(async response=>{if(!response.ok||!active)return;const body=await response.json() as{householdId?:string;linkedContributorId?:string;contributors?:Contributor[];interviews?:Interview[];permissions?:{manage:boolean;contributeSelf:boolean;read:boolean;custody:boolean;bootstrapCustody:boolean}};if(active){setHouseholdId(body.householdId||"");setLinkedContributorId(body.linkedContributorId||"");setContributors(body.contributors||[]);setInterviews(body.interviews||[]);setPermissions(body.permissions||{manage:false,contributeSelf:false,read:false,custody:false,bootstrapCustody:false});}});return()=>{active=false;}; }, []);
  async function createSelf(form: FormData) {
    setMessage("Saving contributor…"); const response = await fetch("/api/v1/legacy/contributors", { method: "POST", headers: { "content-type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ displayName: form.get("displayName"), relationship: "self", selfContributor: true }) });
    const body = await response.json() as { error?: string }; setMessage(response.ok ? "Contributor saved." : body.error || "Contributor could not be saved."); if (response.ok) await load();
  }
  async function search(form: FormData) {
    setMessage("Searching recorded memories…"); const response = await fetch("/api/v1/legacy/query", { method: "POST", headers: { "content-type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ question: form.get("question") }) }); const body = await response.json() as { answer: string; label: string; sources?: Array<{ recordingId: string; transcriptId: string | null; recordedAt: string; startMs: number; endMs: number; provenance: string; playable: boolean }>; error?: string };
    setAnswer(response.ok ? body : null); setMessage(response.ok ? "Search complete." : body.error || "Archive search failed.");
  }
  async function createInterview(form:FormData){setMessage("Creating guided interview…");const response=await fetch("/api/v1/legacy/interviews",{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({contributorId:form.get("contributorId"),title:form.get("title")})}),body=await response.json() as{error?:string};setMessage(response.ok?"Guided interview created.":body.error||"Interview could not be created.");if(response.ok)await load();}
  function protectedHeaders(){return{"content-type":"application/json","Idempotency-Key":crypto.randomUUID(),"x-nearyou-reauth-challenge":reauthChallenge,"x-nearyou-mfa-code":stepUpCode};}function validStepUp(){return /^[0-9]{6}$|^[A-Z0-9]{12}$/i.test(stepUpCode);}
  function clearStepUp(){setStepUpCode("");setReauthChallenge("");sessionStorage.removeItem("nearyou:privacy:reauth-challenge");}
  async function createExport(){if(!reauthChallenge||!validStepUp())return setMessage("Complete fresh sign-in and enter a current authenticator or recovery code.");setMessage("Preparing secure export…");const response=await fetch("/api/v1/legacy/exports",{method:"POST",headers:protectedHeaders(),body:"{}"}),body=await response.json() as{error?:string};setMessage(response.ok?"Portable export queued.":body.error||"Export could not be created.");if(response.ok)clearStepUp();}
  async function bootstrapCustody(){if(!reauthChallenge||!validStepUp())return setMessage("Complete fresh sign-in and enter a current authenticator or recovery code.");setMessage("Establishing archive custody…");const response=await fetch("/api/v1/legacy/custodians",{method:"POST",headers:protectedHeaders(),body:JSON.stringify({action:"bootstrap"})}),body=await response.json() as{error?:string};setMessage(response.ok?"Archive custody established.":body.error||"Custody could not be established.");if(response.ok){clearStepUp();await load();}}
  async function custodyAction(form:FormData){if(!reauthChallenge||!validStepUp())return setMessage("Complete fresh sign-in and enter a current authenticator or recovery code.");const action=String(form.get("action")),userId=String(form.get("userId")||""),custodianId=String(form.get("custodianId")||""),endpoint=action==="accept"?"/api/v1/legacy/custodians/accept":action==="transfer"?"/api/v1/legacy/custodians/transfer":"/api/v1/legacy/custodians",payload=action==="appoint"?{action,userId}:action==="transfer"?{toCustodianId:custodianId}:{};const response=await fetch(endpoint,{method:"POST",headers:protectedHeaders(),body:JSON.stringify(payload)}),body=await response.json()as{error?:string};setMessage(response.ok?"Archive custody updated.":body.error||"Custody could not be updated.");if(response.ok){clearStepUp();await load();}}
  async function lifecycleAction(form:FormData){if(!reauthChallenge||!validStepUp())return setMessage("Complete fresh sign-in and enter a current authenticator or recovery code.");const contributorId=String(form.get("contributorId")),action=String(form.get("action"));if(action==="revoke"&&!window.confirm("Revoke your consent and begin verified deletion of your contributor archive?"))return;const response=await fetch(`/api/v1/legacy/contributors/${encodeURIComponent(contributorId)}/lifecycle`,{method:"POST",headers:{...protectedHeaders(),"x-nearyou-household-id":householdId},body:JSON.stringify({action})}),body=await response.json()as{error?:string};setMessage(response.ok?"Contributor lifecycle updated.":body.error||"Contributor lifecycle could not be updated.");if(response.ok){clearStepUp();await load();}}
  async function startMfa(){if(!reauthChallenge)return setMessage("Complete fresh sign-in before setting up an authenticator.");const response=await fetch("/api/v1/legacy/mfa",{method:"POST",headers:{"x-nearyou-reauth-challenge":reauthChallenge,"x-nearyou-household-id":householdId}}),body=await response.json() as{enrollmentId?:string;otpauthUri?:string;error?:string};if(response.ok&&body.enrollmentId&&body.otpauthUri){setMfa({id:body.enrollmentId,uri:body.otpauthUri});setMessage("Add the key to your authenticator, then verify its six-digit code.");}else setMessage(body.error||"MFA enrollment could not start.");}
  async function verifyMfa(form:FormData){if(!mfa)return;const response=await fetch("/api/v1/legacy/mfa",{method:"PUT",headers:{"content-type":"application/json","x-nearyou-household-id":householdId},body:JSON.stringify({enrollmentId:mfa.id,code:form.get("code")})}),body=await response.json() as{error?:string;recoveryCodes?:string[]};setMessage(response.ok?"MFA is active. Save the one-time recovery codes now.":body.error||"Code could not be verified.");if(response.ok){setRecoveryCodes(body.recoveryCodes||[]);setMfa(null);}}
  return <>
    <span className="eyebrow">NearLegacy private family archive</span><h1 className="app-title display">Preserve the stories behind the voice</h1><p className="muted">Original recordings stay distinct from corrected transcripts and AI-composed narration. If the archive has no supporting recording, NearLegacy says so.</p>
    <div aria-live="polite" className="muted" style={{ marginTop: 12 }}>{message}</div>
    <section className="panel" style={{ marginTop: 24 }}><h2>Contributors</h2><p className="panel-intro">Each loved one accepts their own household invitation and records their own consent. You can begin with yourself.</p>
      {permissions.manage && !contributors.some((item) => item.relationship === "self" && item.status === "active") && <form action={createSelf}><label htmlFor="legacy-display-name">Your archive display name</label><input id="legacy-display-name" name="displayName" maxLength={120} required /><button className="btn btn-primary" type="submit">Add myself</button></form>}
      <ul>{contributors.map((item) => <li key={item.id}>{item.display_name || item.displayName} · {item.relationship || "family"} · {item.status}</li>)}</ul>
    </section>
    <section className="panel" style={{ marginTop: 20 }}><h2>Ask the archive</h2><form action={search}><label htmlFor="legacy-question">Question about a recorded memory</label><input id="legacy-question" name="question" maxLength={500} placeholder="How did Grandma meet Grandpa?" required /><button className="btn btn-primary" type="submit">Search recordings</button></form>
      {answer && <div className="consent-box" style={{ marginTop: 16 }}><span aria-hidden="true">♫</span><span><strong>{answer.label}</strong><br />{answer.answer}{answer.sources?.map((source) => <span key={`${source.recordingId}:${source.startMs}`} style={{ display: "block", marginTop: 8 }}><small>Recording {source.recordingId} · transcript {source.transcriptId || "original"} · {new Date(source.recordedAt).toLocaleDateString()} · {(source.startMs / 1000).toFixed(1)}–{(source.endMs / 1000).toFixed(1)} seconds · {source.provenance.replaceAll("_", " ")} · {source.playable ? "available" : "currently unavailable"}</small>{source.playable && <audio controls preload="none" src={`/api/v1/legacy/recordings/${encodeURIComponent(source.recordingId)}/audio#t=${Math.max(0, source.startMs / 1000)},${Math.max(0, source.endMs / 1000)}`} aria-label={`Play cited family recording from ${(source.startMs / 1000).toFixed(1)} seconds`} style={{ display: "block", width: "100%", marginTop: 6 }} />}</span>)}</span></div>}
    </section>
    <section className="panel" style={{ marginTop: 20 }}><h2>Guided interviews</h2><p className="panel-intro">Create a private interview, then record the contributor’s answers with their active consent.</p>{permissions.manage&&contributors.length>0&&<form action={createInterview}><label htmlFor="legacy-interview-person">Contributor</label><select id="legacy-interview-person" name="contributorId" required>{contributors.map(item=><option key={item.id} value={item.id}>{item.display_name||item.displayName}</option>)}</select><label htmlFor="legacy-interview-title">Interview title</label><input id="legacy-interview-title" name="title" maxLength={160} required placeholder="Grandma’s childhood stories"/><button className="btn btn-primary" type="submit">Create guided interview</button></form>}<ul>{interviews.map(item=><li key={item.id}>{item.title} · {item.status}</li>)}</ul></section>
    {(permissions.custody||permissions.bootstrapCustody) && <section className="panel" style={{ marginTop: 20 }}><h2>Archive custody & portability</h2><p className="panel-intro">High-risk actions require a fresh sign-in and a current authenticator code. Posthumous synthetic narration remains disabled.</p><label htmlFor="legacy-step-up-code">Authenticator or recovery code for this action</label><input id="legacy-step-up-code" value={stepUpCode} onChange={event=>setStepUpCode(event.target.value.replace(/[^A-Za-z0-9]/g,"").slice(0,12))} inputMode="text" minLength={6} maxLength={12} autoComplete="one-time-code"/><p>{reauthChallenge?"Fresh sign-in is ready for one protected action.":"Complete fresh sign-in before a protected action."}</p>{permissions.bootstrapCustody&&<button type="button" className="btn btn-secondary" disabled={!reauthChallenge||stepUpCode.length<6} onClick={bootstrapCustody}>Establish primary custody</button>}{permissions.custody&&<><button type="button" className="btn btn-secondary" disabled={!reauthChallenge||stepUpCode.length<6} onClick={createExport}>Create portable export</button><form action={custodyAction}><input type="hidden" name="action" value="appoint"/><label htmlFor="legacy-successor-user">Successor’s household user ID</label><input id="legacy-successor-user" name="userId" maxLength={200} required/><button className="btn btn-secondary" type="submit">Appoint successor</button></form><form action={custodyAction}><input type="hidden" name="action" value="accept"/><button className="btn btn-secondary" type="submit">Accept my successor appointment</button></form><form action={custodyAction}><input type="hidden" name="action" value="transfer"/><label htmlFor="legacy-transfer-custodian">Accepted successor custodian ID</label><input id="legacy-transfer-custodian" name="custodianId" maxLength={200} required/><button className="btn btn-secondary" type="submit">Transfer primary custody</button></form><form action={lifecycleAction}><label htmlFor="legacy-lifecycle-contributor">Contributor</label><select id="legacy-lifecycle-contributor" name="contributorId" required>{contributors.map(item=><option key={item.id} value={item.id}>{item.display_name||item.displayName}</option>)}</select><label htmlFor="legacy-lifecycle-action">Lifecycle action</label><select id="legacy-lifecycle-action" name="action"><option value="report_death">Report death for review</option><option value="review_death">Complete death review</option><option value="revoke">Revoke my contributor archive</option></select><button className="btn btn-secondary" type="submit">Apply lifecycle action</button></form></>}<p><a href="/account">Complete fresh sign-in or manage privacy controls</a></p></section>}
    {(permissions.manage||permissions.custody)&&<section className="panel" style={{marginTop:20}}><h2>Multi-factor security</h2><p className="panel-intro">Custody, export, and deletion require a fresh sign-in plus a one-time authenticator code.</p>{recoveryCodes.length>0?<div role="status"><strong>Save these recovery codes once</strong><pre aria-label="One-time MFA recovery codes">{recoveryCodes.join("\n")}</pre><button type="button" className="btn btn-secondary" onClick={()=>{const blob=new Blob([recoveryCodes.join("\n")+"\n"],{type:"text/plain"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="nearyou-recovery-codes.txt";anchor.click();URL.revokeObjectURL(url);}}>Download recovery codes</button><button type="button" className="btn btn-secondary" onClick={()=>setRecoveryCodes([])}>I saved them</button></div>:!mfa?<button type="button" className="btn btn-secondary" disabled={!reauthChallenge} onClick={startMfa}>Set up authenticator</button>:<><p><a href={mfa.uri}>Open this key in your authenticator app</a></p><form action={verifyMfa}><label htmlFor="legacy-mfa-code">Six-digit code</label><input id="legacy-mfa-code" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required/><button className="btn btn-primary" type="submit">Verify authenticator</button></form></>} {!reauthChallenge&&<a href="/account">Complete fresh sign-in</a>}</section>}
    {permissions.contributeSelf&&linkedContributorId&&<section className="panel" style={{marginTop:20}}><h2>My contributor rights</h2><p className="panel-intro">You can revoke your own archive consent and begin verified deletion even after leaving a household.</p><form action={lifecycleAction}><input type="hidden" name="contributorId" value={linkedContributorId}/><input type="hidden" name="action" value="revoke"/><button className="btn btn-secondary" type="submit" disabled={!reauthChallenge||!validStepUp()}>Revoke my contributor archive</button></form></section>}
    {householdId&&<LegacyArchiveWorkbench householdId={householdId} contributors={contributors} canManage={permissions.manage}/>}
  </>;
}
