import type { Metadata } from "next";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return <><SiteHeader /><main className="section" style={{ paddingTop: 55 }}><article className="container" style={{ maxWidth: 800 }}><span className="eyebrow">Plain-language draft</span><h1 className="display" style={{ fontSize: "4.7rem", lineHeight: 1 }}>Privacy</h1><p className="muted">Last updated August 11, 2026 · This launch draft requires legal review before public release.</p><div className="panel" style={{ marginTop: 30 }}><h2>What we collect</h2><p>Adult account details supplied by Google or Apple, a baby nickname and age in months, bedtime preferences, parent-authored or generated scripts, generated audio, subscription status, consent records, and product usage events. Our optional product waitlist collects an adult email address, selected product interests, signup source, and marketing-consent evidence.</p><h2>Voice data</h2><p>A parent voice sample is sent to ElevenLabs to create a voice profile. NearSleep does not retain the raw sample after that transfer. The resulting provider voice identifier is stored so the parent can generate and delete audio. Voice data may be considered biometric or sensitive data depending on location.</p><h2>How data is used</h2><p>To provide the service, secure accounts, process payments, maintain safety and reliability, answer support requests, and—only with explicit consent—send product launch and marketing email. We do not sell personal data or use voice samples for advertising.</p><h2>Processors</h2><p>Core subprocessors include Google for sign-in and the private marketing waitlist mirror, OpenAI for constrained script generation, ElevenLabs for voice cloning and speech, Stripe for billing, and hosting/storage providers. The application database remains authoritative for waitlist consent and suppression.</p><h2>Deletion and retention</h2><p>Parents may delete individual voice profiles, audio sessions, or the full account. Waitlist subscribers may unsubscribe at any time; suppression is recorded in the application and mirrored to Google Sheets.</p><h2>Contact</h2><p>Before launch, replace this section with the legal entity, mailing address, privacy email, and jurisdiction-specific rights process.</p></div></article></main><SiteFooter /></>;
}
