import type { Metadata } from "next";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return <><SiteHeader /><main className="section" style={{ paddingTop: 55 }}><article className="container" style={{ maxWidth: 800 }}><span className="eyebrow">Plain-language draft</span><h1 className="display" style={{ fontSize: "4.7rem", lineHeight: 1 }}>Privacy</h1><p className="muted">Last updated August 10, 2026 · This launch draft requires legal review before public release.</p><div className="panel" style={{ marginTop: 30 }}><h2>What we collect</h2><p>Adult account details supplied by Google or Apple, a baby nickname and age in months, bedtime preferences, parent-authored or generated scripts, generated audio, subscription status, consent records, and product usage events. We do not receive your Google or Apple password, and we do not ask for a baby’s full legal name, birthday, photo, or direct account.</p><h2>Voice data</h2><p>A parent voice sample is sent to ElevenLabs to create a voice profile. Nearnight does not retain the raw sample after that transfer. The resulting provider voice identifier is stored so the parent can generate and delete audio. Voice data may be considered biometric or sensitive data depending on location.</p><h2>How data is used</h2><p>To provide the service, secure accounts, process payments, maintain safety and reliability, answer support requests, and understand aggregate product performance. We do not sell personal data or use voice samples for advertising.</p><h2>Processors</h2><p>Core subprocessors are expected to include Google and Apple for account sign-in, OpenAI for constrained script generation, ElevenLabs for voice cloning and speech, Stripe for billing, and hosting/storage providers. Final vendor terms and data-processing agreements must be reviewed before launch.</p><h2>Deletion and retention</h2><p>Parents may delete individual voice profiles, audio sessions, or the full account. Operational logs are kept only as long as needed for security, billing, dispute resolution, and legal obligations.</p><h2>Contact</h2><p>Before launch, replace this section with the legal entity, mailing address, privacy email, and jurisdiction-specific rights process.</p></div></article></main><SiteFooter /></>;
}
