"use client";

import { useEffect, useState } from "react";
import { clearStoredSecret, exportArtifactPlan, stableStoredRequestId, storedSecret } from "@/lib/task2c-client-state";

type ExportRecord = { id: string; requestId: string; status: string; progress: number; manifestUrl?: string; downloadConfirmed?: boolean };
type DeletionStatus = { operationId: string; status: string; stage: string; graceUntil: string; retryable: boolean; action?: string };
type HouseholdRole = "owner" | "adult_manager" | "contributor" | "listener";
type ArtifactReceipt = { kind: "manifest" | "metadata" | "part"; id: string; sha256: string };
const KEYS = { export: "nearyou:privacy:export-request", deletion: "nearyou:privacy:delete-request", receipt: "nearyou:privacy:delete-receipt", reauth: "nearyou:privacy:reauth-challenge", downloaded: "nearyou:privacy:downloaded-export" };

async function errorMessage(response: Response) { try { return ((await response.json()) as { error?: string }).error || "The request could not be completed."; } catch { return "The request could not be completed."; } }
function receiptToken() { const bytes = crypto.getRandomValues(new Uint8Array(32)); return btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function hex(bytes: ArrayBuffer) { return [...new Uint8Array(bytes)].map((value) => value.toString(16).padStart(2, "0")).join(""); }
function filename(response: Response, fallback: string) { return response.headers.get("content-disposition")?.match(/filename="([^"\r\n]+)"/i)?.[1] || fallback.replace(/[^A-Za-z0-9_.-]/g, "-"); }
type WritableFile = { write(data: ArrayBuffer): Promise<void>; close(): Promise<void>; abort?(): Promise<void> };
type ExportDirectory = { getFileHandle(name: string, options: { create: true }): Promise<{ createWritable(): Promise<WritableFile> }> };
type DirectoryPickerWindow = Window & { showDirectoryPicker?: (options: { mode: "readwrite" }) => Promise<ExportDirectory> };

export function ProductionPrivacyControls({ role }: { role: HouseholdRole }) {
  const [exports, setExports] = useState<ExportRecord[]>([]), [challengeId, setChallengeId] = useState(""), [confirmation, setConfirmation] = useState("");
  const [reauthenticated, setReauthenticated] = useState(false), [selectedExportId, setSelectedExportId] = useState(""), [downloadedExportId, setDownloadedExportId] = useState("");
  const [exportPolicy, setExportPolicy] = useState<"skip" | "require_completed_export">("skip"), [graceHours, setGraceHours] = useState<0 | 24>(24);
  const [receipt, setReceipt] = useState(""), [deletion, setDeletion] = useState<DeletionStatus | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(""), [downloadProgress, setDownloadProgress] = useState("");

  async function refreshExports() {
    const response = await fetch("/api/account/export", { cache: "no-store" }); if (!response.ok) return setMessage(await errorMessage(response));
    const records = (await response.json() as { exports: ExportRecord[] }).exports; setExports(records); const serverConfirmed = records.find(({ downloadConfirmed }) => downloadConfirmed); if (serverConfirmed) { sessionStorage.setItem(KEYS.downloaded, serverConfirmed.id); setDownloadedExportId(serverConfirmed.id); }
    const live = records.find(({ status }) => ["queued", "running", "failed"].includes(status)); if (live?.requestId) sessionStorage.setItem(KEYS.export, live.requestId);
    setSelectedExportId((current) => current || records.find(({ status }) => status === "succeeded")?.id || "");
  }
  async function refreshDeletion(token: string) {
    const response = await fetch("/api/account", { cache: "no-store", headers: token ? { authorization: `Bearer ${token}` } : undefined }); if (!response.ok) return setMessage(await errorMessage(response));
    const state = (await response.json() as { deletion: DeletionStatus | null }).deletion; setDeletion(state); if (state && ["completed", "canceled"].includes(state.status)) clearStoredSecret(sessionStorage, KEYS.deletion);
  }
  useEffect(() => {
    if (role !== "owner") return; queueMicrotask(() => { const savedReceipt = sessionStorage.getItem(KEYS.receipt) || ""; setReceipt(savedReceipt); setDownloadedExportId(sessionStorage.getItem(KEYS.downloaded) || ""); void refreshExports(); if (savedReceipt) void refreshDeletion(savedReceipt);
      const pending = new URLSearchParams(window.location.search).get("reauthChallenge") || sessionStorage.getItem(KEYS.reauth) || ""; if (!pending) return; setBusy("reauth-verify");
      void fetch("/api/account/reauth", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ challengeId: pending }) }).then(async (response) => { if (!response.ok) setMessage(await errorMessage(response)); else { sessionStorage.setItem(KEYS.reauth, pending); setChallengeId(pending); setReauthenticated(true); setMessage("Fresh Google sign-in verified."); } }).catch(() => setMessage("Fresh sign-in could not be verified. Start again.")).finally(() => setBusy("")); });
  }, [role]);
  if (role !== "owner") return <section className="panel" style={{ marginTop: 20 }}><h2>Export and account deletion</h2><p className="panel-intro">Only the selected household owner can export or delete this household. Ask the owner, or transfer/leave household access before deleting your own account.</p></section>;

  async function requestExport() {
    setBusy("export"); setMessage(""); try { const requestId = stableStoredRequestId(sessionStorage, KEYS.export); const response = await fetch("/api/account/export", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ requestId }) }); if (!response.ok) return setMessage(await errorMessage(response)); const record = (await response.json() as { export: ExportRecord }).export; setExports((current) => [record, ...current.filter(({ id }) => id !== record.id)]); if (record.status === "succeeded") { setSelectedExportId(record.id); clearStoredSecret(sessionStorage, KEYS.export); } else setMessage(`Export ${record.progress}% complete. Retry is safe.`); } catch { setMessage("Export response was ambiguous. Retry preserves the same protected request ID."); } finally { setBusy(""); }
  }
  async function downloadFullExport(record: ExportRecord) {
    setBusy(`download:${record.id}`); setMessage(""); setDownloadProgress("Reading manifest…"); try {
      const picker = (window as DirectoryPickerWindow).showDirectoryPicker; if (!picker) throw new Error("Verified full export requires a desktop browser that supports choosing a private download folder. No export was marked complete."); const directory = await picker({ mode: "readwrite" });
      const manifestResponse = await fetch(record.manifestUrl || `/api/account/export/${encodeURIComponent(record.id)}`, { cache: "no-store" }); if (!manifestResponse.ok) throw new Error(await errorMessage(manifestResponse)); const manifestBytes = await manifestResponse.arrayBuffer(); const manifest = JSON.parse(new TextDecoder().decode(manifestBytes)) as { metadataPages: { count: number }; integrityCatalog?: { count: number }; mediaParts: { count: number } }; const plan = exportArtifactPlan(record.id, manifest); const receipts: ArtifactReceipt[] = [];
      for (let index = 0; index < plan.length; index += 1) { const artifact = plan[index]; setDownloadProgress(`Writing and verifying file ${index + 1} of ${plan.length}…`); let response: Response, bytes: ArrayBuffer; if (artifact.kind === "manifest") { response = manifestResponse; bytes = manifestBytes; } else { response = await fetch(artifact.url, { cache: "no-store" }); if (!response.ok) throw new Error(await errorMessage(response)); bytes = await response.arrayBuffer(); } const sha256 = hex(await crypto.subtle.digest("SHA-256", bytes)); if (response.headers.get("x-nearyou-sha256")?.toLowerCase() !== sha256) throw new Error(`Checksum verification failed for file ${index + 1}.`); const handle = await directory.getFileHandle(filename(response, `${artifact.kind}-${artifact.id}`), { create: true }); const writable = await handle.createWritable(); try { await writable.write(bytes); await writable.close(); } catch (error) { try { await writable.abort?.(); } catch { /* best effort */ } throw error; } receipts.push({ kind: artifact.kind, id: artifact.id, sha256 }); }
      const confirmationResponse = await fetch(`/api/account/export/${encodeURIComponent(record.id)}/download`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ artifacts: receipts }) }); if (!confirmationResponse.ok) throw new Error(await errorMessage(confirmationResponse)); sessionStorage.setItem(KEYS.downloaded, record.id); setDownloadedExportId(record.id); setSelectedExportId(record.id); setDownloadProgress(`Verified all ${plan.length} files.`); setMessage("Full checksummed export downloaded. If your browser blocked files, allow multiple downloads and run it again.");
    } catch (error) { setDownloadProgress(""); setMessage(error instanceof Error ? error.message : "The full export download could not be verified."); } finally { setBusy(""); }
  }
  async function startReauth() { setBusy("reauth"); setMessage(""); try { clearStoredSecret(sessionStorage, KEYS.reauth); const response = await fetch("/api/account/reauth", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); if (!response.ok) return setMessage(await errorMessage(response)); window.location.assign(((await response.json()) as { signInUrl: string }).signInUrl); } catch { setMessage("Fresh sign-in could not be started."); setBusy(""); } }
  async function submitDeletion() {
    if (!reauthenticated || !challengeId) return setMessage("Complete a new Google sign-in first."); if (exportPolicy === "require_completed_export" && downloadedExportId !== selectedExportId) return setMessage("Download and verify the complete selected export first."); const token = storedSecret(sessionStorage, KEYS.receipt, receiptToken), requestId = stableStoredRequestId(sessionStorage, KEYS.deletion); setReceipt(token); setBusy("delete"); setMessage("");
    try { const response = await fetch("/api/account", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ requestId, reauthChallengeId: challengeId, receiptToken: token, confirmation, exportPolicy, exportId: exportPolicy === "require_completed_export" ? selectedExportId : null, exportDownloaded: exportPolicy === "skip" || downloadedExportId === selectedExportId, graceHours }) }); if (!response.ok) return setMessage(await errorMessage(response)); const state = (await response.json() as { deletion: DeletionStatus }).deletion; setDeletion(state); if (state.status === "completed") clearStoredSecret(sessionStorage, KEYS.deletion); setMessage(state.status === "completed" ? "Deletion completed. Keep the private receipt token below." : state.action || "Deletion is safely continuing."); } catch { setMessage("Deletion response was ambiguous. Retry preserves the same request ID and receipt token."); } finally { setBusy(""); }
  }
  async function cancelDeletion() {
    if (!receipt) return setMessage("The saved deletion receipt is required to cancel."); setBusy("cancel"); setMessage(""); try { const response = await fetch("/api/account", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ receiptToken: receipt }) }); if (!response.ok) return setMessage(await errorMessage(response)); setDeletion((await response.json() as { deletion: DeletionStatus }).deletion); clearStoredSecret(sessionStorage, KEYS.deletion); clearStoredSecret(sessionStorage, KEYS.receipt); setReceipt(""); setMessage("Deletion canceled during the grace period. Your household remains active."); } catch { setMessage("Cancellation response was ambiguous. Refresh with the saved receipt before retrying."); } finally { setBusy(""); }
  }

  return <><section className="panel" style={{ marginTop: 20 }}><h2>Portable household export</h2><p className="panel-intro">Owner-only, private, checksummed metadata and audio remain downloadable for seven days. The single archive works across supported browsers; Chromium desktop can also verify directly into a chosen folder.</p><button className="btn btn-secondary" type="button" disabled={Boolean(busy)} onClick={() => void requestExport()}>{busy === "export" ? "Advancing export…" : exports.some(({ status }) => ["queued","running","failed"].includes(status)) ? "Retry export now" : "Start household export"}</button> <button className="btn btn-secondary" type="button" disabled={Boolean(busy)} onClick={() => void refreshExports()}>Refresh status</button><ul>{exports.map((record) => <li key={record.id}>{record.status} · {record.progress}%{record.downloadConfirmed ? " · download verified" : ""}{record.manifestUrl && <> · <a href={`/api/account/export/${encodeURIComponent(record.id)}/archive`}>Download single archive</a> · <button type="button" disabled={Boolean(busy)} onClick={() => void downloadFullExport(record)}>Verify into folder</button></>}</li>)}</ul>{downloadProgress && <p role="status">{downloadProgress}</p>}</section>
    <section className="panel" style={{ marginTop: 20 }}><h2>Delete account</h2><p className="panel-intro">Deletion is resumable, cancels billing first, and requires a new one-use Google sign-in.</p><button className="btn btn-secondary" type="button" disabled={Boolean(busy)} onClick={() => void startReauth()}>{reauthenticated ? "Fresh sign-in verified" : "Complete fresh sign-in"}</button><div className="field"><label htmlFor="delete-export-policy">Export policy</label><select id="delete-export-policy" value={exportPolicy} onChange={(event) => setExportPolicy(event.target.value as typeof exportPolicy)}><option value="skip">Delete without requiring an export</option><option value="require_completed_export">Require verified full export</option></select></div>{exportPolicy === "require_completed_export" && <div className="field"><label htmlFor="delete-export">Verified completed export</label><select id="delete-export" value={selectedExportId} onChange={(event) => setSelectedExportId(event.target.value)}><option value="">Select export</option>{exports.filter(({ status }) => status === "succeeded").map((record) => <option key={record.id} value={record.id}>{record.id}{downloadedExportId === record.id ? " · verified" : ""}</option>)}</select></div>}<div className="field"><label htmlFor="delete-grace">Grace period</label><select id="delete-grace" value={graceHours} onChange={(event) => setGraceHours(Number(event.target.value) as 0 | 24)}><option value={24}>24 hours (cancel before cleanup starts)</option><option value={0}>Delete as soon as cleanup verifies</option></select></div><div className="field"><label htmlFor="delete-confirmation">Type DELETE MY ACCOUNT</label><input id="delete-confirmation" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></div><button className="btn btn-secondary" type="button" disabled={busy === "delete" || confirmation !== "DELETE MY ACCOUNT" || !reauthenticated} onClick={() => void submitDeletion()}>{deletion?.retryable ? "Retry protected deletion" : "Start protected deletion"}</button> <button className="btn btn-secondary" type="button" onClick={() => void refreshDeletion(receipt)}>Refresh deletion status</button>{deletion?.status === "grace_period" && <button className="btn btn-secondary" type="button" disabled={busy === "cancel"} onClick={() => void cancelDeletion()}>Cancel deletion</button>}{deletion && <p role="status">{deletion.status} · {deletion.stage}{deletion.action ? ` · ${deletion.action}` : ""}</p>}{receipt && <div className="consent-box"><span>Deletion receipt token (save privately): <code>{receipt}</code></span></div>}{message && <div className="alert" role="status" style={{ marginTop: 12 }}>{message}</div>}</section></>;
}
