/* eslint-disable no-empty */
import {isOfflineRightsVerifier,type OfflineRightsVerifier} from "../../lib/mobile-rights";
const DEVICE_KEY=Symbol("attested-device-key");
export type DeviceBoundKey={readonly [DEVICE_KEY]:true;readonly alias:string;readonly hardwareBacked:true;readonly accountBinding:string;encrypt(input:{plaintext:Uint8Array;aad:Uint8Array}):Promise<{iv:Uint8Array;ciphertext:Uint8Array}>;decrypt(input:{iv:Uint8Array;ciphertext:Uint8Array;aad:Uint8Array}):Promise<Uint8Array>;delete():Promise<void>};
export type NativeDeviceKeyHostObject={readonly __nativeHostObject:true;attestation(challenge:string):Promise<{version:1;keyId:string;keyVersion:string;appId:"com.nearyou.family";platform:"ios"|"android";alias:string;accountBinding:string;challenge:string;issuedAt:number;signature:string}>;encrypt(plaintext:Uint8Array,aad:Uint8Array):Promise<{iv:Uint8Array;ciphertext:Uint8Array}>;decrypt(iv:Uint8Array,ciphertext:Uint8Array,aad:Uint8Array):Promise<Uint8Array>;delete():Promise<void>};
type NativeTrust={keyId:string;keyVersion:string;key:CryptoKey;fingerprint:string;validFrom:number;validUntil:number;status:"active"|"retiring"|"revoked";revokedAt:number|null};
const hex=async(v:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",v)),x=>x.toString(16).padStart(2,"0")).join("");
const b64=(v:string)=>{if(!/^[A-Za-z0-9_-]+$/.test(v)||v.length%4===1)throw new Error();const bytes=Uint8Array.from(atob(v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-v.length%4)%4)),c=>c.charCodeAt(0));if(btoa(String.fromCharCode(...bytes)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")!==v)throw new Error();return bytes};
const keyOk=(key:CryptoKey)=>{const a=key.algorithm as RsaHashedKeyAlgorithm;return key.type==="public"&&key.extractable&&key.usages.length===1&&key.usages[0]==="verify"&&a.name==="RSA-PSS"&&a.hash.name==="SHA-256"&&a.modulusLength>=3072&&Array.from(a.publicExponent).join(",")==="1,0,1"};
export async function loadNativeDeviceKey(host:NativeDeviceKeyHostObject,input:{trust:readonly NativeTrust[];expectedChallenge:string;now:number;consumeChallenge(value:{challenge:string;keyId:string;keyVersion:string;proofDigest:string}):Promise<boolean>}):Promise<DeviceBoundKey>{try{if(host.__nativeHostObject!==true||!/^[A-Za-z0-9_-]{22,128}$/.test(input.expectedChallenge)||!Number.isSafeInteger(input.now)||input.trust.length<1||input.trust.length>8)throw 0;const seen=new Set<string>();for(const t of input.trust){const tuple=`${t.keyId}:${t.keyVersion}`;if(seen.has(tuple)||!/^att_[A-Za-z0-9_-]{3,64}$/.test(t.keyId)||!/^[1-9][0-9]{0,8}$/.test(t.keyVersion)||!keyOk(t.key)||!/^[a-f0-9]{64}$/.test(t.fingerprint)||!Number.isSafeInteger(t.validFrom)||!Number.isSafeInteger(t.validUntil)||t.validFrom>=t.validUntil||t.status==="revoked"!==(t.revokedAt!==null))throw 0;seen.add(tuple)}const proof=await host.attestation(input.expectedChallenge),trust=input.trust.find(t=>t.keyId===proof.keyId&&t.keyVersion===proof.keyVersion);if(!trust||trust.status==="revoked"||input.now<trust.validFrom||input.now>=trust.validUntil||proof.challenge!==input.expectedChallenge||proof.appId!=="com.nearyou.family"||proof.version!==1||Math.abs(input.now-proof.issuedAt)>30000||!/^nearyou\.offline\.[A-Za-z0-9_-]{8,100}$/.test(proof.alias)||!/^[a-f0-9]{64}$/.test(proof.accountBinding))throw 0;const fingerprint=await hex(await crypto.subtle.exportKey("spki",trust.key));if(fingerprint!==trust.fingerprint)throw 0;const {signature,...claims}=proof,canonical=JSON.stringify(claims),sig=b64(signature);if(sig.byteLength!==(trust.key.algorithm as RsaHashedKeyAlgorithm).modulusLength/8||!await crypto.subtle.verify({name:"RSA-PSS",saltLength:32},trust.key,sig,new TextEncoder().encode(canonical)))throw 0;const proofDigest=await hex(new TextEncoder().encode(canonical).buffer);if(!await input.consumeChallenge({challenge:proof.challenge,keyId:proof.keyId,keyVersion:proof.keyVersion,proofDigest}))throw 0;return{[DEVICE_KEY]:true,alias:proof.alias,hardwareBacked:true,accountBinding:proof.accountBinding,encrypt:({plaintext,aad})=>host.encrypt(plaintext,aad),decrypt:({iv,ciphertext,aad})=>host.decrypt(iv,ciphertext,aad),delete:()=>host.delete()}}catch{throw new Error("native_attestation_invalid")}}
type Metadata={accountBinding:string;rightsVersion:number;expiresAt:number;checksum:string};type Record={iv:Uint8Array;ciphertext:Uint8Array;metadata:Metadata};
const valid=(m:Metadata)=>/^[a-f0-9]{64}$/.test(m.accountBinding)&&/^[a-f0-9]{64}$/.test(m.checksum)&&Number.isSafeInteger(m.rightsVersion)&&m.rightsVersion>=0&&Number.isSafeInteger(m.expiresAt)&&m.expiresAt>0;
const aad=(id:string,m:Metadata)=>new TextEncoder().encode(JSON.stringify([id,m.accountBinding,m.rightsVersion,m.expiresAt,m.checksum]));
export function createOfflineCache(key:DeviceBoundKey,files:{write(id:string,value:Record):Promise<void>;read(id:string):Promise<Record|null>;deleteAll():Promise<void>},security:{rightsVerifier:OfflineRightsVerifier;deviceIdHash:string;entitlementId:string;lastTrustedTime:number;purgeJournal:{load():Promise<{phase:"files"|"key"}|null>;save(value:{phase:"files"|"key"}):Promise<void>;clear():Promise<void>}}){if(!key||key[DEVICE_KEY]!==true||!security||!isOfflineRightsVerifier(security.rightsVerifier))throw new Error("attested device key and durable security required");const purge=async()=>{const state=await security.purgeJournal.load()??{phase:"files" as const};if(state.phase==="files"){await security.purgeJournal.save({phase:"files"});await files.deleteAll();await security.purgeJournal.save({phase:"key"})}await key.delete();await security.purgeJournal.clear()};return{async put(id:string,plaintext:Uint8Array,metadata:Metadata){if(key.accountBinding!==metadata.accountBinding||!/^media_[A-Za-z0-9_-]+$/.test(id)||!valid(metadata))throw new Error("Offline cache metadata invalid.");const encrypted=await key.encrypt({plaintext,aad:aad(id,metadata)});if(encrypted.iv.byteLength!==12||encrypted.ciphertext.byteLength<16)throw new Error("Offline cache encryption invalid.");await files.write(id,{...encrypted,metadata})},async get(id:string,expected:{accountBinding:string;rightsVersion:number;now:number;receipt:unknown}){const value=await files.read(id);if(!value)return null;let rights=false;try{const verified=await security.rightsVerifier.verify(expected.receipt,{deviceIdHash:security.deviceIdHash,accountBinding:expected.accountBinding,entitlementId:security.entitlementId,mediaId:id,rightsVersion:expected.rightsVersion,now:expected.now,lastTrustedTime:security.lastTrustedTime});rights=verified.expiresAt===value.metadata.expiresAt}catch{}if(!valid(value.metadata)||!Number.isSafeInteger(expected.now)||!rights||key.accountBinding!==expected.accountBinding||value.metadata.accountBinding!==expected.accountBinding||value.metadata.rightsVersion!==expected.rightsVersion||value.metadata.expiresAt<=expected.now){await purge();throw new Error("Offline rights or binding invalid.")}try{const plaintext=await key.decrypt({iv:value.iv,ciphertext:value.ciphertext,aad:aad(id,value.metadata)}),actual=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new Uint8Array(plaintext).buffer)),byte=>byte.toString(16).padStart(2,"0")).join("");if(actual!==value.metadata.checksum)throw new Error();return plaintext}catch{await purge();throw new Error("Offline cache authentication failed.")}}}}
export async function purgeOfflineSession(key:DeviceBoundKey,files:{deleteAll():Promise<void>},journal:{load():Promise<{phase:"files"|"key"}|null>;save(value:{phase:"files"|"key"}):Promise<void>;clear():Promise<void>}){if(key[DEVICE_KEY]!==true)throw new Error("attested device key required");const state=await journal.load()??{phase:"files" as const};if(state.phase==="files"){await journal.save({phase:"files"});await files.deleteAll();await journal.save({phase:"key"})}await key.delete();await journal.clear()}
export function persistentDownloadMetadata(input:{mediaId:string;checksum:string;accessToken?:string;signedUrl?:string}){return{mediaId:input.mediaId,checksum:input.checksum}}
