import type { Metadata } from "next";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return <><SiteHeader /><main className="section" style={{ paddingTop: 55 }}><article className="container" style={{ maxWidth: 800 }}><span className="eyebrow">Launch draft</span><h1 className="display" style={{ fontSize: "4.7rem", lineHeight: 1 }}>Terms of use</h1><p className="muted">Last updated August 11, 2026 · Obtain qualified legal review before accepting customers.</p><div className="panel" style={{ marginTop: 30 }}><h2>Adult-operated service</h2><p>You must be at least 18 and legally able to enter this agreement. NearSleep is for parents and caregivers; children may not create accounts or operate the service.</p><h2>Your voice and content</h2><p>You may upload only your own voice, with informed consent, and only content you have the right to use. You retain rights in your input and generated audio subject to provider terms. You grant NearSleep the limited rights needed to process, store, and deliver the service.</p><h2>Waitlist messages</h2><p>Product waitlist messages require separate marketing consent and may be stopped at any time through unsubscribe controls.</p><h2>Prohibited use</h2><p>Do not impersonate another person, generate deceptive or harmful material, bypass limits, resell voice access, reverse engineer the service, or use generated audio as medical guidance.</p><h2>Wellbeing disclaimer</h2><p>NearSleep is not a medical device, sleep-training program, monitoring service, or emergency service. It makes no guarantee that a baby will fall asleep or remain asleep. Seek qualified care for health or sleep concerns.</p><h2>Subscriptions</h2><p>Paid plans renew automatically until canceled. Stripe processes payments. Plan limits, trials, taxes, refunds, cancellation timing, and price-change notice must be finalized before launch.</p><h2>Availability and liability</h2><p>AI output and provider services can be inaccurate or unavailable. Parents must review scripts before generation and supervise playback. Final warranty, liability, indemnity, governing-law, and dispute terms require counsel.</p></div></article></main><SiteFooter /></>;
}
