// Generated by scripts/generate-d1-domain-registry.ts. Do not edit.
export const D1_DOMAIN_REGISTRY_VERSION=1 as const;
export const D1_DOMAIN_REGISTRY_CHECKSUM="b29efd8f5b5fc8757f7ba4ac0cd2ac834e927fd32e665f15d36976da2a1b1d38" as const;
export const D1_DOMAIN_REGISTRY=[
  {
    "exportName": "accountDeletionBillingTombstones",
    "table": "account_deletion_billing_tombstones",
    "columns": [
      "id",
      "kind",
      "reference_hash",
      "created_at",
      "expires_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "accountDeletionItems",
    "table": "account_deletion_items",
    "columns": [
      "id",
      "operation_id",
      "kind",
      "reference",
      "status",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "accountDeletionOperations",
    "table": "account_deletion_operations",
    "columns": [
      "id",
      "user_id",
      "household_id",
      "subject_receipt_hash",
      "idempotency_key",
      "request_hash",
      "reauth_challenge_id",
      "reauth_session_id",
      "status",
      "stage",
      "attempt_token",
      "attempt_expires_at",
      "billing_cursor",
      "provider_cursor",
      "storage_cursor",
      "quiescent_at",
      "inventory_stage",
      "inventory_cursor",
      "inventory_complete",
      "export_policy",
      "grace_until",
      "snapshot",
      "error_code",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "accountReauthChallenges",
    "table": "account_reauth_challenges",
    "columns": [
      "id",
      "user_id",
      "initial_session_id",
      "verified_session_id",
      "status",
      "expires_at",
      "created_at",
      "verified_at",
      "consumed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "adultOnboardingAcceptances",
    "table": "adult_onboarding_acceptances",
    "columns": [
      "id",
      "household_id",
      "adult_user_id",
      "version",
      "attestation",
      "accepted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "annualAllowanceRefills",
    "table": "annual_allowance_refills",
    "columns": [
      "entitlement_id",
      "household_id",
      "anchor_seconds",
      "refilled_through_seconds",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "entitlement_id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "authSessions",
    "table": "auth_sessions",
    "columns": [
      "id",
      "token",
      "expires_at",
      "created_at",
      "updated_at",
      "ip_address",
      "user_agent",
      "user_id"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "authVerifications",
    "table": "auth_verifications",
    "columns": [
      "id",
      "identifier",
      "value",
      "expires_at",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "bedtimeQueueItems",
    "table": "bedtime_queue_items",
    "columns": [
      "id",
      "household_id",
      "queued_by_user_id",
      "session_id",
      "position",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "childProfiles",
    "table": "child_profiles",
    "columns": [
      "id",
      "household_id",
      "legacy_child_id",
      "nickname",
      "normalized_nickname",
      "pronunciation",
      "age_months",
      "bedtime_challenge",
      "created_at",
      "updated_at",
      "archived_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "children",
    "table": "children",
    "columns": [
      "id",
      "user_id",
      "household_id",
      "profile_id",
      "nickname",
      "normalized_nickname",
      "pronunciation",
      "age_months",
      "bedtime_challenge",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "contributors",
    "table": "contributors",
    "columns": [
      "id",
      "household_id",
      "adult_user_id",
      "display_name",
      "relationship",
      "status",
      "creation_idempotency_key",
      "request_hash",
      "invitation_id",
      "death_reviewed_at",
      "death_reviewed_by_user_id",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "deletionReconciliations",
    "table": "deletion_reconciliations",
    "columns": [
      "id",
      "scope",
      "scope_id",
      "household_id",
      "attempt_token",
      "attempt_expires_at",
      "status",
      "storage_keys",
      "provider_references",
      "error_code",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "encryptedIntegrationTokens",
    "table": "encrypted_integration_tokens",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "provider",
      "ciphertext",
      "iv",
      "key_version",
      "expires_at",
      "revoked_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "entitlements",
    "table": "entitlements",
    "columns": [
      "id",
      "household_id",
      "plan_id",
      "source",
      "status",
      "allowance_milliunits",
      "remaining_milliunits",
      "legacy_credits_remaining",
      "external_ref",
      "billing_period_start",
      "valid_from",
      "valid_until",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "generationOperations",
    "table": "generation_operations",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "operation",
      "request_hash",
      "status",
      "result",
      "error_code",
      "allowance_reservation_id",
      "provider_spend_reservation_id",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "householdBillingAccounts",
    "table": "household_billing_accounts",
    "columns": [
      "household_id",
      "customer_id",
      "subscription_id",
      "price_id",
      "status",
      "subscription_event_created_at",
      "checkout_pending_at",
      "checkout_operation_id",
      "checkout_session_id",
      "checkout_session_url",
      "checkout_price_id",
      "checkout_status",
      "checkout_expires_at",
      "last_credited_invoice_id",
      "last_credited_period_start",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "household_id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "householdBillingSubscriptions",
    "table": "household_billing_subscriptions",
    "columns": [
      "subscription_id",
      "household_id",
      "customer_id",
      "price_id",
      "status",
      "event_created_at",
      "superseded_at",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "subscription_id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "householdExportDownloadConfirmations",
    "table": "household_export_download_confirmations",
    "columns": [
      "export_id",
      "user_id",
      "manifest_checksum",
      "artifact_count",
      "confirmed_at"
    ],
    "primaryKey": [
      "export_id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "householdExportMetadataPages",
    "table": "household_export_metadata_pages",
    "columns": [
      "id",
      "export_id",
      "position",
      "kind",
      "storage_key",
      "item_count",
      "byte_size",
      "checksum",
      "status",
      "expires_at",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "householdExportParts",
    "table": "household_export_parts",
    "columns": [
      "id",
      "export_id",
      "source_media_asset_id",
      "source_storage_key",
      "export_storage_key",
      "content_type",
      "byte_size",
      "checksum",
      "status",
      "expires_at",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "householdExports",
    "table": "household_exports",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "idempotency_key",
      "request_hash",
      "snapshot",
      "status",
      "attempt_token",
      "attempt_expires_at",
      "inventory_stage",
      "inventory_cursor",
      "metadata_page_count",
      "cursor_position",
      "inventory_count",
      "manifest_storage_key",
      "manifest_byte_size",
      "manifest_checksum",
      "error_code",
      "expires_at",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "householdInvitations",
    "table": "household_invitations",
    "columns": [
      "id",
      "household_id",
      "invited_by_user_id",
      "invited_email",
      "role",
      "token_hash",
      "status",
      "expires_at",
      "accepted_by_user_id",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "householdMembers",
    "table": "household_members",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "role",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "householdOwnerTransferGuards",
    "table": "household_owner_transfer_guards",
    "columns": [
      "id",
      "household_id",
      "prior_owner_user_id",
      "new_owner_user_id",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "householdStorageReservations",
    "table": "household_storage_reservations",
    "columns": [
      "id",
      "household_id",
      "media_asset_id",
      "byte_size",
      "status",
      "created_at",
      "updated_at",
      "released_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "households",
    "table": "households",
    "columns": [
      "id",
      "name",
      "owner_user_id",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "integrationRightsReceipts",
    "table": "integration_rights_receipts",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "source_kind",
      "source_id_hash",
      "consent_version",
      "attested_at",
      "revoked_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "jobs",
    "table": "jobs",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "legacy_session_id",
      "type",
      "status",
      "idempotency_key",
      "request_hash",
      "input",
      "result",
      "attempts",
      "error_code",
      "progress_percent",
      "progress_stage",
      "worker_attempt_token",
      "worker_lease_expires_at",
      "rollout_release_id",
      "rollout_version",
      "reservation_id",
      "consent_id",
      "consent_version",
      "created_at",
      "updated_at",
      "started_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyActivationState",
    "table": "legacy_activation_state",
    "columns": [
      "id",
      "status",
      "migration_version",
      "worker_heartbeat_at",
      "unresolved_objects",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "legacyAuditEvents",
    "table": "legacy_audit_events",
    "columns": [
      "id",
      "household_id",
      "actor_user_id",
      "event_type",
      "target_kind",
      "target_id",
      "request_hash",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyCollectionItems",
    "table": "legacy_collection_items",
    "columns": [
      "id",
      "household_id",
      "collection_id",
      "memory_id",
      "position",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyCollections",
    "table": "legacy_collections",
    "columns": [
      "id",
      "household_id",
      "created_by_user_id",
      "name",
      "description",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyConsents",
    "table": "legacy_consents",
    "columns": [
      "id",
      "household_id",
      "contributor_id",
      "attesting_user_id",
      "supersedes_consent_id",
      "version",
      "kind",
      "audience",
      "purpose",
      "posthumous_use",
      "status",
      "evidence_key",
      "evidence_checksum",
      "evidence_media_asset_id",
      "liveness_challenge_id",
      "media_probe_receipt_id",
      "attested_at",
      "expires_at",
      "revoked_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyCustodianAcceptances",
    "table": "legacy_custodian_acceptances",
    "columns": [
      "id",
      "household_id",
      "custodian_id",
      "user_id",
      "request_hash",
      "reauth_challenge_id",
      "reauth_session_id",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyCustodianTransfers",
    "table": "legacy_custodian_transfers",
    "columns": [
      "id",
      "household_id",
      "from_custodian_id",
      "to_custodian_id",
      "requested_by_user_id",
      "status",
      "reauth_challenge_id",
      "reauth_session_id",
      "created_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyCustodians",
    "table": "legacy_custodians",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "role",
      "status",
      "appointed_by_user_id",
      "accepted_at",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyDeletionItems",
    "table": "legacy_deletion_items",
    "columns": [
      "id",
      "household_id",
      "operation_id",
      "object_kind",
      "object_id",
      "storage_key",
      "status",
      "attempts",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyDeletionOperations",
    "table": "legacy_deletion_operations",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "target_kind",
      "target_id",
      "request_hash",
      "reauth_challenge_id",
      "reauth_session_id",
      "status",
      "cursor",
      "attempt_token",
      "lease_expires_at",
      "attempts",
      "next_attempt_at",
      "dead_lettered_at",
      "error_code",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyErasureAuthorizations",
    "table": "legacy_erasure_authorizations",
    "columns": [
      "id",
      "household_id",
      "operation_kind",
      "operation_id",
      "active",
      "created_at",
      "expires_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyErasureTombstones",
    "table": "legacy_erasure_tombstones",
    "columns": [
      "household_id",
      "target_kind",
      "target_id",
      "operation_id",
      "completed_at"
    ],
    "primaryKey": [
      "household_id",
      "target_kind",
      "target_id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyEvidenceRetention",
    "table": "legacy_evidence_retention",
    "columns": [
      "household_id",
      "consent_id",
      "media_asset_id",
      "delete_after",
      "status",
      "attempts",
      "next_attempt_at",
      "attempt_token",
      "lease_expires_at",
      "dead_lettered_at",
      "error_code",
      "updated_at"
    ],
    "primaryKey": [
      "household_id",
      "consent_id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyExportConsents",
    "table": "legacy_export_consents",
    "columns": [
      "household_id",
      "export_id",
      "consent_id"
    ],
    "primaryKey": [
      "household_id",
      "export_id",
      "consent_id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyExportOperations",
    "table": "legacy_export_operations",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "request_hash",
      "status",
      "snapshot_at",
      "inventory_stage",
      "cursor",
      "manifest_key",
      "manifest_checksum",
      "part_count",
      "attempts",
      "next_attempt_at",
      "dead_lettered_at",
      "error_code",
      "expires_at",
      "reauth_challenge_id",
      "reauth_session_id",
      "attempt_token",
      "lease_expires_at",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyExportParts",
    "table": "legacy_export_parts",
    "columns": [
      "id",
      "household_id",
      "export_id",
      "ordinal",
      "source_kind",
      "source_id",
      "logical_path",
      "content_type",
      "storage_key",
      "checksum",
      "byte_size",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyInterviews",
    "table": "legacy_interviews",
    "columns": [
      "id",
      "household_id",
      "contributor_id",
      "created_by_user_id",
      "title",
      "idempotency_key",
      "request_hash",
      "prompt_set_version",
      "status",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyJobBindings",
    "table": "legacy_job_bindings",
    "columns": [
      "id",
      "household_id",
      "job_id",
      "contributor_id",
      "recording_id",
      "consent_id",
      "reservation_id",
      "provider_spend_reservation_id",
      "operation",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyLivenessChallenges",
    "table": "legacy_liveness_challenges",
    "columns": [
      "id",
      "household_id",
      "contributor_id",
      "user_id",
      "kind",
      "phrase",
      "phrase_hash",
      "status",
      "expires_at",
      "created_at",
      "consumed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyMediaProbeReceipts",
    "table": "legacy_media_probe_receipts",
    "columns": [
      "id",
      "household_id",
      "challenge_id",
      "user_id",
      "contributor_id",
      "kind",
      "consent_kind",
      "checksum",
      "byte_size",
      "content_type",
      "duration_ms",
      "phrase_matched",
      "live_speaker_verified",
      "processor_receipt_hash",
      "status",
      "expires_at",
      "created_at",
      "consumed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyMemories",
    "table": "legacy_memories",
    "columns": [
      "id",
      "household_id",
      "contributor_id",
      "title",
      "summary",
      "source_segment_id",
      "status",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyMemoryTags",
    "table": "legacy_memory_tags",
    "columns": [
      "household_id",
      "memory_id",
      "tag_id"
    ],
    "primaryKey": [
      "household_id",
      "memory_id",
      "tag_id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyMfaEnrollments",
    "table": "legacy_mfa_enrollments",
    "columns": [
      "id",
      "user_id",
      "method",
      "status",
      "secret_ciphertext",
      "secret_iv",
      "last_used_counter",
      "reauth_challenge_id",
      "reauth_session_id",
      "created_at",
      "verified_at",
      "revoked_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "legacyMfaRateLimits",
    "table": "legacy_mfa_rate_limits",
    "columns": [
      "user_id",
      "operation",
      "window_started_at",
      "request_count"
    ],
    "primaryKey": [
      "user_id",
      "operation"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "legacyMfaRecoveryCodes",
    "table": "legacy_mfa_recovery_codes",
    "columns": [
      "id",
      "enrollment_id",
      "user_id",
      "code_hash",
      "created_at",
      "used_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "legacyPeople",
    "table": "legacy_people",
    "columns": [
      "id",
      "household_id",
      "display_name",
      "relationship",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyPhotos",
    "table": "legacy_photos",
    "columns": [
      "id",
      "household_id",
      "media_asset_id",
      "caption",
      "taken_at",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyPlaces",
    "table": "legacy_places",
    "columns": [
      "id",
      "household_id",
      "name",
      "description",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyQueryReceipts",
    "table": "legacy_query_receipts",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "question_hash",
      "supported",
      "answer_kind",
      "status",
      "answer_text",
      "answer_checksum",
      "selected_segment_id",
      "selected_transcript_id",
      "selected_correction_id",
      "selected_recording_id",
      "selected_score_micros",
      "created_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyQuerySources",
    "table": "legacy_query_sources",
    "columns": [
      "household_id",
      "query_receipt_id",
      "segment_id",
      "transcript_id",
      "correction_id",
      "recording_id",
      "rank",
      "score_micros"
    ],
    "primaryKey": [
      "household_id",
      "query_receipt_id",
      "rank"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyRateLimits",
    "table": "legacy_rate_limits",
    "columns": [
      "household_id",
      "user_id",
      "operation",
      "window_started_at",
      "request_count"
    ],
    "primaryKey": [
      "household_id",
      "user_id",
      "operation"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyRecordings",
    "table": "legacy_recordings",
    "columns": [
      "id",
      "household_id",
      "interview_id",
      "contributor_id",
      "consent_id",
      "media_asset_id",
      "transcription_job_id",
      "recorded_at",
      "duration_ms",
      "status",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacySecurityActions",
    "table": "legacy_security_actions",
    "columns": [
      "id",
      "household_id",
      "actor_user_id",
      "action",
      "target_kind",
      "target_id",
      "request_hash",
      "reauth_challenge_id",
      "reauth_session_id",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyTags",
    "table": "legacy_tags",
    "columns": [
      "id",
      "household_id",
      "name",
      "normalized_name",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyTimelineEvents",
    "table": "legacy_timeline_events",
    "columns": [
      "id",
      "household_id",
      "memory_id",
      "occurred_on",
      "precision",
      "title",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyTranscriptCorrections",
    "table": "legacy_transcript_corrections",
    "columns": [
      "id",
      "household_id",
      "segment_id",
      "corrected_by_user_id",
      "speaker_contributor_id",
      "corrected_text",
      "reason",
      "idempotency_key",
      "request_hash",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyTranscriptSegments",
    "table": "legacy_transcript_segments",
    "columns": [
      "id",
      "household_id",
      "transcript_id",
      "recording_id",
      "contributor_id",
      "ordinal",
      "start_ms",
      "end_ms",
      "original_text",
      "effective_text",
      "provenance",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyTranscripts",
    "table": "legacy_transcripts",
    "columns": [
      "id",
      "household_id",
      "recording_id",
      "consent_id",
      "job_binding_id",
      "provider_request_id",
      "language",
      "status",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "legacyUploadOperations",
    "table": "legacy_upload_operations",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "kind",
      "request_hash",
      "storage_key",
      "checksum",
      "byte_size",
      "status",
      "target_id",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "marketingWaitlistContacts",
    "table": "marketing_waitlist_contacts",
    "columns": [
      "id",
      "email_lookup_hash",
      "email_ciphertext",
      "email_iv",
      "consent_version",
      "consented_at",
      "unsubscribed_at",
      "version",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "marketingWaitlistInterests",
    "table": "marketing_waitlist_interests",
    "columns": [
      "id",
      "contact_id",
      "product",
      "signup_source",
      "joined_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "marketingWaitlistSync",
    "table": "marketing_waitlist_sync",
    "columns": [
      "id",
      "contact_id",
      "contact_version",
      "status",
      "attempt_token",
      "lease_expires_at",
      "attempt_count",
      "next_attempt_at",
      "error_code",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "mediaAssets",
    "table": "media_assets",
    "columns": [
      "id",
      "household_id",
      "owner_user_id",
      "child_profile_id",
      "legacy_session_id",
      "kind",
      "status",
      "storage_key",
      "content_type",
      "byte_size",
      "checksum",
      "private",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "mobileAccountBindings",
    "table": "mobile_account_bindings",
    "columns": [
      "app_user_id_hash",
      "household_id",
      "user_id",
      "created_at",
      "revoked_at",
      "app_id",
      "environment",
      "binding_version",
      "status"
    ],
    "primaryKey": [
      "app_user_id_hash"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "mobileEntitlementEvents",
    "table": "mobile_entitlement_events",
    "columns": [
      "id",
      "household_id",
      "app_id",
      "environment",
      "product_id",
      "entitlement_id",
      "app_user_id_hash",
      "event_type",
      "occurred_at",
      "payload_checksum",
      "processed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "nearStoryActivationState",
    "table": "nearstory_activation_state",
    "columns": [
      "id",
      "status",
      "migration_version",
      "worker_heartbeat_at",
      "checked_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "oauthAccounts",
    "table": "oauth_accounts",
    "columns": [
      "id",
      "account_id",
      "provider_id",
      "user_id",
      "access_token",
      "refresh_token",
      "id_token",
      "access_token_expires_at",
      "refresh_token_expires_at",
      "scope",
      "password",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "playlistItems",
    "table": "playlist_items",
    "columns": [
      "id",
      "playlist_id",
      "media_asset_id",
      "position",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "playlists",
    "table": "playlists",
    "columns": [
      "id",
      "household_id",
      "created_by_user_id",
      "name",
      "private",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "providerBudgetPolicies",
    "table": "provider_budget_policies",
    "columns": [
      "provider",
      "household_window_microcents",
      "global_window_microcents",
      "window_milliseconds",
      "max_concurrent",
      "enabled",
      "updated_at"
    ],
    "primaryKey": [
      "provider"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "providerCircuits",
    "table": "provider_circuits",
    "columns": [
      "provider",
      "consecutive_failures",
      "open_until",
      "updated_at"
    ],
    "primaryKey": [
      "provider"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "providerSpendReservations",
    "table": "provider_spend_reservations",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "provider",
      "operation",
      "idempotency_key",
      "estimated_microcents",
      "actual_microcents",
      "status",
      "charge_committed_at",
      "expires_at",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "sleepSessions",
    "table": "sleep_sessions",
    "columns": [
      "id",
      "user_id",
      "household_id",
      "job_id",
      "media_asset_id",
      "child_id",
      "voice_id",
      "title",
      "script",
      "script_mode",
      "content_type",
      "narration_kind",
      "source_url",
      "source_title",
      "consent_id",
      "consent_version",
      "consent_lease_id",
      "allowance_reservation_id",
      "theme",
      "style",
      "background_sound",
      "pronunciation",
      "frequency_layers",
      "duration_minutes",
      "status",
      "audio_key",
      "favorite",
      "repeat_minutes",
      "deletion_status",
      "deletion_requested_at",
      "deleted_at",
      "provider_request_id",
      "error_code",
      "created_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storyBranchRequests",
    "table": "story_branch_requests",
    "columns": [
      "id",
      "household_id",
      "story_id",
      "requested_by_user_id",
      "direction",
      "after_segment",
      "request_hash",
      "job_id",
      "reservation_id",
      "consent_lease_id",
      "moderation_receipt_id",
      "reserved_minutes",
      "status",
      "moderation_provenance",
      "error_code",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storyDeletionOperations",
    "table": "story_deletion_operations",
    "columns": [
      "id",
      "household_id",
      "story_id",
      "idempotency_key",
      "request_hash",
      "status",
      "storage_keys",
      "attempt_token",
      "attempt_expires_at",
      "error_code",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storyExperiences",
    "table": "story_experiences",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "child_profile_id",
      "voice_id",
      "consent_id",
      "consent_version",
      "consent_lease_id",
      "mode",
      "duration_minutes",
      "plan",
      "rights_actor_user_id",
      "rights_version",
      "rights_canonical_url",
      "rights_attested_at",
      "status",
      "highest_played_segment",
      "job_id",
      "reservation_id",
      "provider_budget_hold_ids",
      "media_asset_id",
      "idempotency_key",
      "request_hash",
      "error_code",
      "created_at",
      "updated_at",
      "completed_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storyMediaBindings",
    "table": "story_media_bindings",
    "columns": [
      "id",
      "household_id",
      "story_id",
      "media_asset_id",
      "role",
      "branch_key",
      "ordinal",
      "status",
      "attempt_token",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storyModerationReceipts",
    "table": "story_moderation_receipts",
    "columns": [
      "id",
      "household_id",
      "requested_by_user_id",
      "request_hash",
      "verdict",
      "model",
      "provider_request_id",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storyPersistStagingObjects",
    "table": "story_persist_staging_objects",
    "columns": [
      "id",
      "household_id",
      "story_id",
      "attempt_token",
      "role",
      "ordinal",
      "storage_key",
      "byte_size",
      "checksum",
      "status",
      "created_at",
      "updated_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storyProviderBudgetHolds",
    "table": "story_provider_budget_holds",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "story_id",
      "branch_key",
      "provider",
      "operation",
      "max_microcents",
      "idempotency_key",
      "provider_spend_reservation_id",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storySegments",
    "table": "story_segments",
    "columns": [
      "id",
      "household_id",
      "story_id",
      "branch_key",
      "ordinal",
      "purpose",
      "narration",
      "status",
      "plan_version",
      "prompt_version",
      "writer_model",
      "writer_request_id",
      "moderation_model",
      "moderation_request_id",
      "moderation_verdict",
      "tts_model",
      "tts_request_id",
      "media_asset_id",
      "start_ms",
      "end_ms",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "storySoundAssets",
    "table": "story_sound_assets",
    "columns": [
      "id",
      "cache_key",
      "descriptor",
      "provenance",
      "license_policy_version",
      "provider",
      "provider_request_id",
      "storage_key",
      "checksum",
      "byte_size",
      "attempt_token",
      "attempt_expires_at",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "storyWorkerCheckpoints",
    "table": "story_worker_checkpoints",
    "columns": [
      "id",
      "household_id",
      "story_id",
      "attempt_token",
      "stage",
      "ordinal",
      "payload",
      "storage_key",
      "byte_size",
      "checksum",
      "status",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "stripeEvents",
    "table": "stripe_events",
    "columns": [
      "id",
      "type",
      "event_created_at",
      "status",
      "error_code",
      "attempt_token",
      "processed_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "task2cActivationState",
    "table": "task2c_activation_state",
    "columns": [
      "id",
      "status",
      "unresolved_ready_media",
      "checked_at",
      "scheduler_heartbeat_at",
      "scheduler_run_id"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "task2cMediaIntegrity",
    "table": "task2c_media_integrity",
    "columns": [
      "media_asset_id",
      "byte_size",
      "checksum",
      "verified_at"
    ],
    "primaryKey": [
      "media_asset_id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "usageEvents",
    "table": "usage_events",
    "columns": [
      "id",
      "user_id",
      "household_id",
      "ledger_entry_id",
      "session_id",
      "type",
      "units",
      "metadata",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "usageLedger",
    "table": "usage_ledger",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "entitlement_id",
      "legacy_usage_event_id",
      "product",
      "operation",
      "quantity",
      "weight_milliunits",
      "direction",
      "idempotency_key",
      "metadata",
      "created_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "usageReservations",
    "table": "usage_reservations",
    "columns": [
      "id",
      "household_id",
      "user_id",
      "entitlement_id",
      "operation",
      "quantity",
      "weight_milliunits",
      "idempotency_key",
      "request_hash",
      "status",
      "consent_lease_id",
      "created_at",
      "updated_at",
      "finalized_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "users",
    "table": "users",
    "columns": [
      "id",
      "email",
      "display_name",
      "email_verified",
      "image",
      "role",
      "stripe_customer_id",
      "subscription_id",
      "subscription_price_id",
      "subscription_status",
      "subscription_event_created_at",
      "checkout_pending_at",
      "last_credited_invoice_id",
      "last_credited_period_start",
      "credits_remaining",
      "consent_version",
      "consented_at",
      "created_at",
      "updated_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "global"
    }
  },
  {
    "exportName": "voiceConsentLeases",
    "table": "voice_consent_leases",
    "columns": [
      "id",
      "household_id",
      "voice_id",
      "consent_id",
      "consent_version",
      "session_id",
      "status",
      "expires_at",
      "created_at",
      "finalized_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "voiceConsents",
    "table": "voice_consents",
    "columns": [
      "id",
      "household_id",
      "voice_id",
      "contributor_id",
      "adult_user_id",
      "consent_version",
      "scope",
      "status",
      "evidence",
      "attested_at",
      "revoked_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "voiceReplacements",
    "table": "voice_replacements",
    "columns": [
      "id",
      "household_id",
      "voice_id",
      "challenge_id",
      "adult_user_id",
      "original_provider_voice_id",
      "original_consent_id",
      "replacement_provider_voice_id",
      "provider_request_id",
      "consent_id",
      "consent_version",
      "evidence",
      "status",
      "error_code",
      "created_at",
      "updated_at",
      "completed_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "voiceVerificationChallenges",
    "table": "voice_verification_challenges",
    "columns": [
      "id",
      "household_id",
      "voice_id",
      "adult_user_id",
      "onboarding_acceptance_id",
      "version",
      "phrase",
      "phrase_hash",
      "status",
      "attempts",
      "expires_at",
      "created_at",
      "verified_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  },
  {
    "exportName": "voices",
    "table": "voices",
    "columns": [
      "id",
      "user_id",
      "household_id",
      "current_consent_id",
      "creation_request_id",
      "provider_voice_id",
      "name",
      "status",
      "consent_attested_at",
      "created_at",
      "deleted_at"
    ],
    "primaryKey": [
      "id"
    ],
    "scope": {
      "kind": "tenant",
      "column": "household_id"
    }
  }
] as const;
