const ID=/^[A-Za-z0-9_:/.@-]{3,200}$/,HASH=/^[a-f0-9]{64}$/,NONCE=/^[A-Za-z0-9_-]{22,128}$/;
const BRAND=Symbol("postgres-inventory-evidence-verifier"),encoder=new TextEncoder();
type Purpose="d1-inventory-page"|"d1-inventory-complete";
type Base={version:1;purpose:Purpose;principal:string;keyId:string;keyVersion:number;operationId:string;registryChecksum:string;nonce:string;notBefore:number;issuedAt:number;expiresAt:number};
export type InventoryPageEvidenceClaims=Base&{purpose:"d1-inventory-page";pass:1|2;tableIndex:number;pageOrdinal:number;table:string;fromCursor:string;toCursor:string;rowCount:number;eventFrom:number|null;eventTo:number|null;pageChecksum:string;eventsDigest:string};
export type InventoryCompletionEvidenceClaims=Base&{purpose:"d1-inventory-complete";inventoryChecksum:string;rowCount:number;pageCount:number;orderedPageDigest:string};
export type InventoryEvidenceEnvelope<T=InventoryPageEvidenceClaims|InventoryCompletionEvidenceClaims>={claims:T;signature:string};
export type InventoryEvidenceTrust={principal:string;keyId:string;version:number;fingerprint:string;status:"active"|"retiring"|"revoked";validFrom:number;validUntil:number;revokedAt:number|null;usage:"inventory-evidence"};
type KeyRecord={principal:string;keyId:string;version:number;fingerprint:string;key:CryptoKey};
type Pg={query<T=Record<string,unknown>>(sql:string,args?:unknown[]):Promise<{rows:T[]}>};
const exact=(value:unknown,names:string[])=>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype||Object.values(Object.getOwnPropertyDescriptors(value)).some(d=>!("value" in d)||d.get||d.set)||JSON.stringify(Object.keys(value).sort())!==JSON.stringify([...names].sort()))throw new Error("inventory evidence invalid")};
const integer=(value:unknown,min=0,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(value)&&Number(value)>=min&&Number(value)<=max;
const names=(purpose:Purpose)=>purpose==="d1-inventory-page"?["version","purpose","principal","keyId","keyVersion","operationId","registryChecksum","pass","tableIndex","pageOrdinal","table","fromCursor","toCursor","rowCount","eventFrom","eventTo","pageChecksum","eventsDigest","nonce","notBefore","issuedAt","expiresAt"]:["version","purpose","principal","keyId","keyVersion","operationId","registryChecksum","inventoryChecksum","rowCount","pageCount","orderedPageDigest","nonce","notBefore","issuedAt","expiresAt"];
function canonical(claims:InventoryPageEvidenceClaims|InventoryCompletionEvidenceClaims){exact(claims,names(claims.purpose));if(claims.version!==1||![claims.principal,claims.keyId,claims.operationId].every(v=>ID.test(v))||!integer(claims.keyVersion,1)||!HASH.test(claims.registryChecksum)||!NONCE.test(claims.nonce)||![claims.notBefore,claims.issuedAt,claims.expiresAt].every(v=>integer(v)))throw new Error("inventory evidence invalid");if(claims.purpose==="d1-inventory-page"){if(![1,2].includes(claims.pass)||!integer(claims.tableIndex,0,10000)||!integer(claims.pageOrdinal)||!ID.test(claims.table)||typeof claims.fromCursor!=="string"||typeof claims.toCursor!=="string"||new TextEncoder().encode(claims.fromCursor).length>8192||new TextEncoder().encode(claims.toCursor).length>8192||!integer(claims.rowCount,1,500)||!(claims.eventFrom===null||integer(claims.eventFrom,1))||!(claims.eventTo===null||integer(claims.eventTo,1))||((claims.eventFrom===null)!==(claims.eventTo===null))||!HASH.test(claims.pageChecksum)||!HASH.test(claims.eventsDigest))throw new Error("inventory evidence invalid")}else if(!HASH.test(claims.inventoryChecksum)||!integer(claims.rowCount)||!integer(claims.pageCount)||!HASH.test(claims.orderedPageDigest))throw new Error("inventory evidence invalid");const body=JSON.stringify(Object.fromEntries(Object.entries(claims).sort(([a],[b])=>a<b?-1:a>b?1:0)));if(encoder.encode(body).byteLength>32768)throw new Error("inventory evidence invalid");return body}
function decode(value:string){try{if(!/^[A-Za-z0-9_-]+$/.test(value))throw 0;const bytes=Uint8Array.from(atob(value.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-value.length%4)%4)),c=>c.charCodeAt(0)),again=btoa(String.fromCharCode(...bytes)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_");if(again!==value)throw 0;return bytes}catch{throw new Error("inventory evidence signature invalid")}}
const hex=(buffer:ArrayBuffer)=>Array.from(new Uint8Array(buffer),v=>v.toString(16).padStart(2,"0")).join("");
function validateTrust(records:readonly InventoryEvidenceTrust[],now:number){const seen=new Set<string>();for(const r of records){exact(r,["principal","keyId","version","fingerprint","status","validFrom","validUntil","revokedAt","usage"]);const tuple=`${r.principal}\0${r.keyId}\0${r.version}`;if(seen.has(tuple)||!ID.test(r.principal)||!ID.test(r.keyId)||!integer(r.version,1)||!HASH.test(r.fingerprint)||!integer(r.validFrom)||!integer(r.validUntil)||r.validFrom>=r.validUntil||r.usage!=="inventory-evidence"||!["active","retiring","revoked"].includes(r.status)||(r.status==="revoked"?(!integer(r.revokedAt)||Number(r.revokedAt)<r.validFrom||Number(r.revokedAt)>Math.min(r.validUntil,now)):r.revokedAt!==null))throw new Error("inventory trust invalid");seen.add(tuple)}}
export type PostgresInventoryEvidenceVerifier={readonly [BRAND]:true;verifyPage(envelope:InventoryEvidenceEnvelope<InventoryPageEvidenceClaims>,expected:InventoryPageEvidenceClaims):Promise<string>;verifyCompletion(envelope:InventoryEvidenceEnvelope<InventoryCompletionEvidenceClaims>,expected:InventoryCompletionEvidenceClaims):Promise<string>};
export function createPostgresInventoryEvidenceVerifier(options:{pg:Pg;clock:{now():Promise<number>};trust:readonly InventoryEvidenceTrust[];lookupKey(principal:string,keyId:string,version:number):Promise<KeyRecord>}):PostgresInventoryEvidenceVerifier{
 const verify=async<T extends InventoryPageEvidenceClaims|InventoryCompletionEvidenceClaims>(envelope:InventoryEvidenceEnvelope<T>,expected:T)=>{exact(envelope,["claims","signature"]);const body=canonical(envelope.claims),expectedBody=canonical(expected);if(body!==expectedBody)throw new Error("inventory evidence invalid");const c=envelope.claims;let now:number;try{now=await options.clock.now()}catch{throw new Error("inventory evidence clock failed")}if(!integer(now)||c.notBefore>c.issuedAt||c.issuedAt>now+30000||c.notBefore>now+30000||c.expiresAt<=now||c.expiresAt-c.issuedAt>300000)throw new Error("inventory evidence freshness invalid");validateTrust(options.trust,now);const trust=options.trust.find(r=>r.principal===c.principal&&r.keyId===c.keyId&&r.version===c.keyVersion&&r.status!=="revoked"&&now>=r.validFrom&&now<r.validUntil);if(!trust)throw new Error("inventory evidence signer untrusted");let record:KeyRecord;try{record=await options.lookupKey(c.principal,c.keyId,c.keyVersion)}catch{throw new Error("inventory evidence key lookup failed")}exact(record,["principal","keyId","version","fingerprint","key"]);const a=record.key.algorithm as RsaHashedKeyAlgorithm;if(record.principal!==c.principal||record.keyId!==c.keyId||record.version!==c.keyVersion||record.key.type!=="public"||record.key.usages.length!==1||record.key.usages[0]!=="verify"||a.name!=="RSA-PSS"||a.hash.name!=="SHA-256"||a.modulusLength<3072||a.publicExponent.length!==3||a.publicExponent[0]!==1||a.publicExponent[1]!==0||a.publicExponent[2]!==1)throw new Error("inventory evidence key invalid");let fingerprint:string;try{fingerprint=hex(await crypto.subtle.digest("SHA-256",await crypto.subtle.exportKey("spki",record.key)))}catch{throw new Error("inventory evidence key invalid")}if(fingerprint!==trust.fingerprint||record.fingerprint!==fingerprint)throw new Error("inventory evidence key invalid");const signature=decode(envelope.signature);if(signature.byteLength!==a.modulusLength/8)throw new Error("inventory evidence signature invalid");let valid=false;try{valid=await crypto.subtle.verify({name:"RSA-PSS",saltLength:32},record.key,signature,encoder.encode(body))}catch{throw new Error("inventory evidence signature invalid")}if(!valid)throw new Error("inventory evidence signature invalid");const digest=hex(await crypto.subtle.digest("SHA-256",encoder.encode(body))),nonceHash=hex(await crypto.subtle.digest("SHA-256",encoder.encode(c.nonce)));let accepted=false;try{accepted=(await options.pg.query<{accepted:boolean}>("SELECT nearyou.record_inventory_verified_claim($1,$2,$3,$4,$5,$6,$7,$8,$9,to_timestamp($10::double precision/1000)) AS accepted",[digest,c.purpose,c.operationId,c.registryChecksum,body,c.principal,c.keyId,c.keyVersion,nonceHash,c.expiresAt])).rows[0]?.accepted===true}catch{throw new Error("inventory evidence store failed")}if(!accepted)throw new Error("inventory evidence rejected");return digest};
 return Object.freeze({[BRAND]:true as const,verifyPage:(e,x)=>verify(e,x),verifyCompletion:(e,x)=>verify(e,x)});
}
export function isPostgresInventoryEvidenceVerifier(value:unknown):value is PostgresInventoryEvidenceVerifier{return !!value&&typeof value==="object"&&(value as PostgresInventoryEvidenceVerifier)[BRAND]===true}
