const ALPHABET="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
const bytesToHex=(bytes:Uint8Array)=>Array.from(bytes,value=>value.toString(16).padStart(2,"0")).join("");
const hexToBytes=(hex:string)=>new Uint8Array(hex.match(/../g)?.map(value=>Number.parseInt(value,16))||[]);
const buffer=(bytes:Uint8Array)=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;
export function base32(bytes:Uint8Array){let bits=0,value=0,result="";for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){result+=ALPHABET[(value>>>(bits-5))&31];bits-=5;}}if(bits)result+=ALPHABET[(value<<(5-bits))&31];return result;}
function encryptionKey(value:string){if(!/^[0-9a-f]{64}$/i.test(value))throw new Error("legacy_mfa_key_invalid");return crypto.subtle.importKey("raw",buffer(hexToBytes(value)),"AES-GCM",false,["encrypt","decrypt"]);}
export async function protectTotpSecret(secret:Uint8Array,keyHex:string){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await encryptionKey(keyHex),cipher=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv:buffer(iv)},key,buffer(secret)));return{ciphertext:bytesToHex(cipher),iv:bytesToHex(iv)};}
export async function revealTotpSecret(ciphertext:string,iv:string,keyHex:string){const key=await encryptionKey(keyHex),ivBytes=hexToBytes(iv);return new Uint8Array(await crypto.subtle.decrypt({name:"AES-GCM",iv:buffer(ivBytes)},key,buffer(hexToBytes(ciphertext))));}
export async function totpCode(secret:Uint8Array,counter:number){const message=new ArrayBuffer(8),view=new DataView(message);view.setUint32(4,counter);const key=await crypto.subtle.importKey("raw",buffer(secret),{name:"HMAC",hash:"SHA-1"},false,["sign"]),digest=new Uint8Array(await crypto.subtle.sign("HMAC",key,message)),offset=digest[digest.length-1]&15,value=((digest[offset]&127)<<24)|((digest[offset+1]&255)<<16)|((digest[offset+2]&255)<<8)|(digest[offset+3]&255);return String(value%1_000_000).padStart(6,"0");}
export async function verifyTotp(secret:Uint8Array,code:string,now=Date.now(),lastCounter=-1){if(!/^\d{6}$/.test(code))return null;const current=Math.floor(now/30000);for(const counter of [current-1,current,current+1])if(counter>lastCounter&&await totpCode(secret,counter)===code)return counter;return null;}
