const BRAND=Symbol("offline-rights-verifier"),enc=new TextEncoder(),HASH=/^[a-f0-9]{64}$/;
type Trust={issuer:string;keyId:string;keyVersion:string;key:CryptoKey;fingerprint:string;validFrom:number;validUntil:number;status:"active"|"retiring"|"revoked";revokedAt:number|null};
export type RightsReceipt={version:1;purpose:"nearyou-offline-rights";issuer:string;keyId:string;keyVersion:string;deviceIdHash:string;accountBinding:string;entitlementId:string;mediaId:string;rightsVersion:number;issuedAt:number;expiresAt:number;nonce:string;signature:string};
export type OfflineRightsVerifier={readonly [BRAND]:true;verify(receipt:unknown,input:{deviceIdHash:string;accountBinding:string;entitlementId:string;mediaId:string;rightsVersion:number;now:number;lastTrustedTime:number}):Promise<{expiresAt:number}>};
const b64=(s:string)=>{if(!/^[A-Za-z0-9_-]+$/.test(s)||s.length%4===1)throw 0;const b=Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));if(btoa(String.fromCharCode(...b)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")!==s)throw 0;return b};
const fingerprint=async(k:CryptoKey)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await crypto.subtle.exportKey("spki",k))),v=>v.toString(16).padStart(2,"0")).join("");
const keyOk=(k:CryptoKey)=>{const a=k.algorithm as RsaHashedKeyAlgorithm;return k.type==="public"&&k.extractable&&k.usages.length===1&&k.usages[0]==="verify"&&a.name==="RSA-PSS"&&a.hash.name==="SHA-256"&&a.modulusLength>=3072&&Array.from(a.publicExponent).join(",")==="1,0,1"};
export function createOfflineRightsVerifier(input:{trust:readonly Trust[];consumeNonce(value:{nonce:string;claimsDigest:string;issuer:string;keyId:string;keyVersion:string;expiresAt:number}):Promise<boolean>}):OfflineRightsVerifier{if(input.trust.length<1||input.trust.length>8)throw new Error("offline_rights_trust_invalid");const seen=new Set<string>();for(const t of input.trust){const id=`${t.issuer}:${t.keyId}:${t.keyVersion}`;if(seen.has(id)||!/^https:\/\/[A-Za-z0-9.-]+$/.test(t.issuer)||!/^rights_[A-Za-z0-9_-]{3,64}$/.test(t.keyId)||!/^[1-9][0-9]{0,8}$/.test(t.keyVersion)||!HASH.test(t.fingerprint)||!keyOk(t.key)||!Number.isSafeInteger(t.validFrom)||!Number.isSafeInteger(t.validUntil)||t.validFrom>=t.validUntil||t.status==="revoked"!==(t.revokedAt!==null))throw new Error("offline_rights_trust_invalid");seen.add(id)}return Object.freeze({[BRAND]:true as const,async verify(value,expected){try{if(!value||Object.getPrototypeOf(value)!==Object.prototype)throw 0;const r=value as RightsReceipt,keys=Object.keys(r).sort(),exact=["accountBinding","deviceIdHash","entitlementId","expiresAt","issuedAt","issuer","keyId","keyVersion","mediaId","nonce","purpose","rightsVersion","signature","version"].sort();if(keys.join()!=exact.join()||r.version!==1||r.purpose!=="nearyou-offline-rights"||!HASH.test(r.deviceIdHash)||!HASH.test(r.accountBinding)||r.deviceIdHash!==expected.deviceIdHash||r.accountBinding!==expected.accountBinding||r.entitlementId!==expected.entitlementId||r.mediaId!==expected.mediaId||r.rightsVersion!==expected.rightsVersion||!Number.isSafeInteger(r.rightsVersion)||r.rightsVersion<1||![r.issuedAt,r.expiresAt,expected.now,expected.lastTrustedTime].every(Number.isSafeInteger)||r.issuedAt>expected.now+30000||r.expiresAt<=expected.now||r.expiresAt-r.issuedAt>86400000||expected.now<expected.lastTrustedTime-300000||!/^[A-Za-z0-9_-]{22,128}$/.test(r.nonce))throw 0;const trust=input.trust.find(t=>t.issuer===r.issuer&&t.keyId===r.keyId&&t.keyVersion===r.keyVersion);if(!trust||trust.status==="revoked"||expected.now<trust.validFrom||expected.now>=trust.validUntil||await fingerprint(trust.key)!==trust.fingerprint)throw 0;const {signature,...claims}=r,canonical=JSON.stringify(claims),sig=b64(signature);if(sig.byteLength!==(trust.key.algorithm as RsaHashedKeyAlgorithm).modulusLength/8||!await crypto.subtle.verify({name:"RSA-PSS",saltLength:32},trust.key,sig,enc.encode(canonical)))throw 0;const claimsDigest=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(canonical))),v=>v.toString(16).padStart(2,"0")).join("");if(!await input.consumeNonce({nonce:r.nonce,claimsDigest,issuer:r.issuer,keyId:r.keyId,keyVersion:r.keyVersion,expiresAt:r.expiresAt}))throw 0;return{expiresAt:r.expiresAt}}catch{throw new Error("offline_rights_invalid")}}})}
export function isOfflineRightsVerifier(value:unknown):value is OfflineRightsVerifier{return !!value&&typeof value==="object"&&(value as OfflineRightsVerifier)[BRAND]===true}
export async function resumePurgeJournal(store:{load():Promise<{phase:"files"|"key"}|null>;save(value:{phase:"files"|"key"}):Promise<void>;clear():Promise<void>},files:()=>Promise<void>,key:()=>Promise<void>){const state=await store.load()??{phase:"files" as const};if(state.phase==="files"){await store.save({phase:"files"});await files();await store.save({phase:"key"})}await key();await store.clear()}
