import type {VerifiedMobileOidcExchange,VerifiedOidcClaims} from "./mobile-oauth";
const verifiedExchanges=new WeakSet<object>();
export function isProductionJwksExchange(value:unknown):value is VerifiedMobileOidcExchange{return typeof value==="object"&&value!==null&&verifiedExchanges.has(value)}
type Provider="apple"|"google";const MAX=65536,te=new TextEncoder(),tuples={apple:["https://appleid.apple.com","https://appleid.apple.com/auth/keys"],google:["https://accounts.google.com","https://www.googleapis.com/oauth2/v3/certs"]}as const;
const decode=(s:string)=>{if(!/^[A-Za-z0-9_-]+$/.test(s)||s.length%4===1)throw 0;const b=Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));if(btoa(String.fromCharCode(...b)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")!==s)throw 0;return b};
const rejectDuplicates=(text:string)=>{const stack:{keys:Set<string>;expectKey:boolean}[]=[],MAX_DEPTH=12;let i=0;while(i<text.length){const ch=text[i];if(ch==="{"){if(stack.length>=MAX_DEPTH)throw 0;stack.push({keys:new Set(),expectKey:true});i++;continue}if(ch==="}"){if(!stack.length)throw 0;stack.pop();i++;continue}if(ch===","){if(stack.length)stack[stack.length-1]!.expectKey=true;i++;continue}if(ch==='"'){const start=i++;let escaped=false;while(i<text.length){const c=text[i++]!;if(escaped){escaped=false;continue}if(c==="\\"){escaped=true;continue}if(c==='"')break}if(text[i-1]!=='"')throw 0;let j=i;while(/\s/.test(text[j]??""))j++;if(stack.length&&stack[stack.length-1]!.expectKey&&text[j]===":"){const key=JSON.parse(text.slice(start,i))as string,top=stack[stack.length-1]!;if(top.keys.has(key))throw 0;top.keys.add(key);top.expectKey=false}continue}i++}if(stack.length)throw 0};
const parse=(s:string)=>{const text=new TextDecoder("utf-8",{fatal:true}).decode(decode(s));rejectDuplicates(text);const value=JSON.parse(text);if(!value||Object.getPrototypeOf(value)!==Object.prototype)throw 0;return value as Record<string,unknown>};
const exact=(v:Record<string,unknown>,keys:string[])=>{if(Object.keys(v).sort().join()!==keys.sort().join())throw 0};
const jwks=(value:unknown)=>{if(!value||Object.getPrototypeOf(value)!==Object.prototype)throw 0;const root=value as Record<string,unknown>;exact(root,["keys"]);if(!Array.isArray(root.keys)||root.keys.length<1||root.keys.length>20)throw 0;const seen=new Set<string>();for(const raw of root.keys){if(!raw||Object.getPrototypeOf(raw)!==Object.prototype)throw 0;const k=raw as Record<string,unknown>;exact(k,["alg","e","kid","kty","n","use"]);if(typeof k.kid!=="string"||seen.has(k.kid)||k.alg!=="RS256"||k.kty!=="RSA"||k.use!=="sig"||k.e!=="AQAB"||typeof k.n!=="string"||decode(k.n).byteLength<256)throw 0;seen.add(k.kid)}return root.keys as JsonWebKey[]};
export function createJwksOidcExchange(o:{fetch:typeof fetch;clock:{now():Promise<number>};exchangeCode(i:{provider:Provider;code:string;redirectUri:string;verifier:string}):Promise<{idToken:string}>;providers:Record<Provider,{issuer:string;audience:string;jwksUrl:string}>}){for(const p of ["apple","google"]as const)if(o.providers[p].issuer!==tuples[p][0]||o.providers[p].jwksUrl!==tuples[p][1])throw new Error("mobile_oidc_config_invalid");const cache=new Map<string,{until:number;keys:JsonWebKey[]}>();const result=Object.freeze({async exchange(i){try{const token=(await o.exchangeCode(i)).idToken,parts=token.split(".");if(parts.length!==3||token.length>16384)throw 0;const h=parse(parts[0]!),c=parse(parts[1]!),cfg=o.providers[i.provider],now=await o.clock.now(),aud=c.aud;exact(h,["alg","kid","typ"]);if(h.alg!=="RS256"||h.typ!=="JWT"||typeof h.kid!=="string"||c.iss!==cfg.issuer||!(aud===cfg.audience||(Array.isArray(aud)&&aud.includes(cfg.audience)&&c.azp===cfg.audience))||typeof c.sub!=="string"||typeof c.nonce!=="string"||!Number.isSafeInteger(c.iat)||!Number.isSafeInteger(c.exp)||Number(c.exp)-Number(c.iat)>3600||Number(c.exp)<=now/1000)throw 0;let set=cache.get(cfg.jwksUrl);if(!set||set.until<=now){const r=await o.fetch(cfg.jwksUrl,{redirect:"error",signal:AbortSignal.timeout(5000)});if(!r.ok||r.redirected||r.url!==cfg.jwksUrl||r.headers.get("content-type")?.split(";")[0]!=="application/json"||Number(r.headers.get("content-length")||0)>MAX)throw 0;const text=await r.text();if(te.encode(text).byteLength>MAX)throw 0;set={until:now+300000,keys:jwks(JSON.parse(text))};cache.set(cfg.jwksUrl,set)}const raw=set.keys.find(k=>(k as JsonWebKey&{kid?:string}).kid===h.kid);if(!raw)throw 0;const key=await crypto.subtle.importKey("jwk",raw,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]),sig=decode(parts[2]!);if(sig.byteLength!==(key.algorithm as RsaHashedKeyAlgorithm).modulusLength/8||!await crypto.subtle.verify("RSASSA-PKCS1-v1_5",key,sig,te.encode(`${parts[0]}.${parts[1]}`)))throw 0;return{issuer:String(c.iss),audience:cfg.audience,subject:String(c.sub),nonce:String(c.nonce),emailVerified:c.email_verified===true,issuedAt:Number(c.iat)*1000,expiresAt:Number(c.exp)*1000}satisfies VerifiedOidcClaims}catch{throw new Error("mobile_oidc_verification_failed")}}})as VerifiedMobileOidcExchange;verifiedExchanges.add(result);return result}
