import {createHash} from "node:crypto";
export type RevenueCatRuntimeEvent={id:string;appId:string;appUserId:string;environment:"SANDBOX"|"PRODUCTION";productId:string;entitlementId:string;eventType:string;occurredAtMs:number;expiresAtMs:number|null};
const digest=(v:string)=>createHash("sha256").update(v).digest("hex"),types=new Set(["INITIAL_PURCHASE","RENEWAL","UNCANCELLATION","CANCELLATION","EXPIRATION","BILLING_ISSUE"]),MAX=262144;
export function parseRevenueCatEnvelope(raw:string):RevenueCatRuntimeEvent{if(new TextEncoder().encode(raw).byteLength>MAX)throw new Error("revenuecat_payload_invalid");const value=JSON.parse(raw)as Record<string,unknown>,expected=["appId","appUserId","entitlementId","environment","eventType","expiresAtMs","id","occurredAtMs","productId"];if(!value||Object.getPrototypeOf(value)!==Object.prototype||Object.keys(value).sort().join()!==expected.sort().join()||typeof value.id!=="string"||typeof value.appId!=="string"||typeof value.appUserId!=="string"||(value.environment!=="SANDBOX"&&value.environment!=="PRODUCTION")||typeof value.productId!=="string"||typeof value.entitlementId!=="string"||typeof value.eventType!=="string"||!Number.isSafeInteger(value.occurredAtMs)||(value.expiresAtMs!==null&&!Number.isSafeInteger(value.expiresAtMs)))throw new Error("revenuecat_payload_invalid");return value as unknown as RevenueCatRuntimeEvent}
const projected=(e:RevenueCatRuntimeEvent)=>{if(!types.has(e.eventType))throw new Error("revenuecat_event_type_unsupported");if(e.eventType==="EXPIRATION")return"expired";if(e.eventType==="BILLING_ISSUE")return"grace";if(e.eventType==="CANCELLATION")return e.expiresAtMs!==null&&e.expiresAtMs>e.occurredAtMs?"canceled":"expired";return"active"};
export async function applyRevenueCatEvent(db:D1Database,e:RevenueCatRuntimeEvent,providerRaw:string,clock:{now():Promise<number>}={now:async()=>Date.now()},heldLease?:string,providerChecksumOverride?:string){
 const canonical=JSON.stringify(e),parsed=parseRevenueCatEnvelope(canonical);e=parsed;const checksum=providerChecksumOverride??digest(providerRaw),canonicalChecksum=digest(canonical),userHash=digest(e.appUserId),token=crypto.randomUUID(),now=await clock.now();if(!Number.isSafeInteger(now))throw new Error("revenuecat_clock_invalid");
 const prior=(await db.prepare("SELECT payload_checksum,status,attempt_token FROM mobile_entitlement_event_claims WHERE id=?").bind(e.id).all()).results[0] as {payload_checksum?:string;status?:string;attempt_token?:string}|undefined;
 if(prior){if(prior.payload_checksum!==checksum)throw new Error("revenuecat_event_conflict");if(prior.status==="completed"||prior.status==="ignored")return{status:"replayed"}as const;if(prior.status==="processing"&&prior.attempt_token!==heldLease)return{status:"busy"}as const;if(prior.status!=="failed"&&prior.status!=="processing")return{status:"busy"}as const}
 const binding=(await db.prepare("SELECT household_id FROM mobile_account_bindings WHERE app_user_id_hash=? AND revoked_at IS NULL AND status='active' AND app_id=? AND environment=?").bind(userHash,e.appId,e.environment).all()).results[0];
 if(!binding){if(heldLease){const attempts=Number(((await db.prepare("SELECT attempts FROM mobile_entitlement_event_claims WHERE id=? AND status='processing' AND attempt_token=?").bind(e.id,heldLease).all()).results[0] as {attempts?:number}|undefined)?.attempts??0)+1,dead=attempts>=8,updated=await db.prepare("UPDATE mobile_entitlement_event_claims SET status=?,attempt_token=NULL,lease_expires_at=NULL,attempts=?,next_attempt_at=?,error_code='revenuecat_unbound',updated_at=? WHERE id=? AND status='processing' AND attempt_token=?").bind(dead?"dead_letter":"failed",attempts,dead?null:now+Math.min(3600000,1000*2**attempts),now,e.id,heldLease).run();return updated.meta.changes===1?{status:dead?"dead_letter":"retry_wait"}as const:{status:"busy"}as const}if(!prior)await db.prepare("INSERT INTO mobile_entitlement_event_claims(id,payload_checksum,canonical_payload,canonical_payload_checksum,status,attempts,next_attempt_at,error_code,created_at,updated_at) VALUES(?,?,?,?,'failed',1,?,'revenuecat_unbound',?,?)").bind(e.id,checksum,canonical,canonicalChecksum,now+1000,now,now).run();return{status:"retry_wait"}as const}
 const activeToken=heldLease??token,state=projected(e),claim=heldLease?db.prepare("UPDATE mobile_entitlement_event_claims SET updated_at=? WHERE id=? AND status='processing' AND attempt_token=? AND lease_expires_at>?").bind(now,e.id,heldLease,now):prior?db.prepare("UPDATE mobile_entitlement_event_claims SET status='processing',attempt_token=?,attempts=attempts+1,lease_expires_at=?,next_attempt_at=NULL,error_code=NULL,updated_at=? WHERE id=? AND status='failed'").bind(token,now+30000,now,e.id):db.prepare("INSERT INTO mobile_entitlement_event_claims(id,payload_checksum,canonical_payload,canonical_payload_checksum,status,attempt_token,attempts,lease_expires_at,created_at,updated_at) VALUES(?,?,?,?,'processing',?,1,?,?,?)").bind(e.id,checksum,canonical,canonicalChecksum,token,now+30000,now,now);
 const results=await db.batch([claim,db.prepare("INSERT INTO mobile_entitlement_events(id,household_id,app_id,environment,product_id,entitlement_id,app_user_id_hash,event_type,occurred_at,payload_checksum,processed_at) SELECT ?,household_id,?,?,?,?,?,?,?,?,? FROM mobile_account_bindings WHERE app_user_id_hash=? AND revoked_at IS NULL AND status='active' AND app_id=? AND environment=?").bind(e.id,e.appId,e.environment,e.productId,e.entitlementId,userHash,e.eventType,e.occurredAtMs,checksum,now,userHash,e.appId,e.environment),db.prepare("INSERT INTO mobile_entitlement_projection(household_id,entitlement_id,status,product_id,environment,last_occurred_at,last_event_id,rights_version,valid_until,updated_at) SELECT household_id,?,?,?,?,?,?,1,?,? FROM mobile_account_bindings WHERE app_user_id_hash=? AND revoked_at IS NULL AND status='active' AND app_id=? AND environment=? ON CONFLICT(household_id,entitlement_id) DO UPDATE SET status=excluded.status,product_id=excluded.product_id,environment=excluded.environment,last_occurred_at=excluded.last_occurred_at,last_event_id=excluded.last_event_id,rights_version=mobile_entitlement_projection.rights_version+1,valid_until=excluded.valid_until,updated_at=excluded.updated_at WHERE (excluded.last_occurred_at,excluded.last_event_id)>(mobile_entitlement_projection.last_occurred_at,mobile_entitlement_projection.last_event_id)").bind(e.entitlementId,state,e.productId,e.environment,e.occurredAtMs,e.id,e.expiresAtMs,now,userHash,e.appId,e.environment),db.prepare("UPDATE mobile_entitlement_event_claims SET status=CASE WHEN EXISTS(SELECT 1 FROM mobile_entitlement_events WHERE id=?) THEN 'completed' ELSE 'ignored' END,attempt_token=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND status='processing' AND attempt_token=?").bind(e.id,now,e.id,activeToken)]);
 if(results[0]?.meta.changes!==1||results[1]?.meta.changes!==1||results[3]?.meta.changes!==1)throw new Error("revenuecat_atomic_transition_failed");return results[2]?.meta.changes===1?{status:"applied"}as const:{status:"ignored_stale"}as const;
}
export function offlineEntitlementDecision(i:{status:"active"|"grace"|"expired"|"revoked"|"canceled";validUntil:number|null;now:number;lastVerifiedAt:number}){if(![i.now,i.lastVerifiedAt].every(Number.isSafeInteger)||i.now<i.lastVerifiedAt-300000)return{allowed:false,purge:true,reason:"clock_rollback"}as const;if(i.status==="revoked"||i.status==="expired"||(i.validUntil!==null&&i.validUntil<=i.now))return{allowed:false,purge:true}as const;if(i.now-i.lastVerifiedAt>86400000)return{allowed:false,purge:false,reason:"online_verification_required"}as const;return{allowed:true,purge:false}as const}
export async function reconcileRevenueCatClaim(db:D1Database,clock:{now():Promise<number>}={now:async()=>Date.now()}){
 const now=await clock.now();if(!Number.isSafeInteger(now))throw new Error("revenuecat_clock_invalid");
 const row=(await db.prepare("SELECT id,attempts,canonical_payload,canonical_payload_checksum,payload_checksum FROM mobile_entitlement_event_claims WHERE (status='failed' AND next_attempt_at<=?) OR (status='processing' AND lease_expires_at<=?) ORDER BY COALESCE(next_attempt_at,lease_expires_at),id LIMIT 1").bind(now,now).all()).results[0] as {id?:string;attempts?:number;canonical_payload?:string;canonical_payload_checksum?:string;payload_checksum?:string}|undefined;if(!row?.id)return{status:"idle"}as const;
 const lease=crypto.randomUUID(),claimed=await db.prepare("UPDATE mobile_entitlement_event_claims SET status='processing',attempt_token=?,lease_expires_at=?,updated_at=? WHERE id=? AND ((status='failed' AND next_attempt_at<=?) OR (status='processing' AND lease_expires_at<=?))").bind(lease,now+30000,now,row.id,now,now).run();if(claimed.meta.changes!==1)return{status:"busy"}as const;
 try{if(typeof row.canonical_payload!=="string"||digest(row.canonical_payload)!==row.canonical_payload_checksum)throw 0;const event=parseRevenueCatEnvelope(row.canonical_payload);if(event.id!==row.id||typeof row.payload_checksum!=="string")throw 0;return await applyRevenueCatEvent(db,event,row.canonical_payload,clock,lease,row.payload_checksum)}catch{const attempts=Number(row.attempts??0)+1,dead=attempts>=8,updated=await db.prepare("UPDATE mobile_entitlement_event_claims SET status=?,attempt_token=NULL,lease_expires_at=NULL,attempts=?,next_attempt_at=?,error_code=?,updated_at=? WHERE id=? AND status='processing' AND attempt_token=?").bind(dead?"dead_letter":"failed",attempts,dead?null:now+Math.min(3600000,1000*2**attempts),dead?"revenuecat_dead_letter":"revenuecat_retry",now,row.id,lease).run();return updated.meta.changes===1?{status:dead?"dead_letter":"retry",id:row.id}as const:{status:"busy"}as const}
}
