import {captureSitesD1PhaseASchemaCheckpoint} from "./sites-d1-phase-a-operation";
import {D1_CONVERGENCE_PROBES} from "./private-tester-baseline-gateway";
import {type ForwardMigration,type SchemaCheckpoint} from "./sites-d1-forward-operation";
type S={bind(...v:unknown[]):S;all<T>():Promise<{results:T[]}>;first<T>():Promise<T|null>;run():Promise<unknown>};type DB={prepare(sql:string):S;batch(s:S[]):Promise<unknown[]>};type Ledger={id:number;name:string;applied_at:string};
const HASH=/^[a-f0-9]{64}$/,ID=/^[A-Za-z0-9:_-]{8,128}$/,canonical=(v:unknown)=>JSON.stringify(v),sha=async(v:string)=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))].map(x=>x.toString(16).padStart(2,"0")).join("");
export const splitD1PhaseBMigration=(sql:string)=>{const statements=sql.split(/\s*-->\s*statement-breakpoint\s*/g).map(x=>x.trim()).filter(Boolean);if(!statements.length)throw new Error("phase b migration empty");return statements};
type PhaseAMigration={id:string;sha256:string};
export type PhaseBProbeStage={stage:string;rowCount:number;violationCount:number;projectionSha256:string};
const PROBE_KEYS=[
 ["identity","target"],["rowCount","violationCount"],["identity","target"],
 ["identity","stripe_customer_id","subscription_id","subscription_price_id","subscription_status","subscription_event_created_at","checkout_pending_at","last_credited_invoice_id","last_credited_period_start","created_at","updated_at"],
 ["identity","subscription_id","stripe_customer_id","subscription_price_id","subscription_status","subscription_event_created_at","created_at","updated_at"],
 ["identity","prior","target"],["identity","target"],["identity","household_id","media_asset_id","byte_size","target","created_at","updated_at"],["identity","target"],
 ["rowCount","violationCount"],["rowCount","violationCount"],["rowCount","violationCount"],["rowCount","violationCount"],
] as const;
type ProbeCapture={index:number;stage:PhaseBProbeStage;rows:Record<string,unknown>[]};
async function captureProbes(db:DB,indexes:number[]){const captures:ProbeCapture[]=[];for(const index of indexes){const[stage,sql]=D1_CONVERGENCE_PROBES[index],rows=(await db.prepare(sql).all<Record<string,unknown>>()).results;if(rows.length>1000||rows.some(row=>canonical(Object.keys(row))!==canonical(PROBE_KEYS[index])))throw new Error("phase b probe invalid");let rowCount=rows.length,violationCount=0;if(stage.endsWith("preflight")){if(rows.length!==1||!Number.isSafeInteger(rows[0].rowCount)||!Number.isSafeInteger(rows[0].violationCount))throw new Error("phase b probe invalid");rowCount=Number(rows[0].rowCount);violationCount=Number(rows[0].violationCount)}captures.push({index,rows,stage:{stage,rowCount,violationCount,projectionSha256:await sha(canonical(rows))}})}return captures}
export async function captureSitesD1PhaseBProbeBinding(db:DB){return{version:1 as const,stages:(await captureProbes(db,D1_CONVERGENCE_PROBES.map((_,i)=>i))).map(x=>x.stage)}}
export type SitesD1PhaseBInput={operationId:string;releaseId:string;issuedAt:number;phaseAOperationId:string;phaseAManifestSha256:string;expectedProviderLedger:Ledger[];phaseAMigrations:PhaseAMigration[];phaseAPredecessor:SchemaCheckpoint;probeContentSha256:string;probeAffectedSetSha256:string;probeBinding:{version:1;stages:PhaseBProbeStage[]};bootstrap:string[];migrations:ForwardMigration[];schemaCheckpoints:SchemaCheckpoint[]};
export class SitesD1PhaseBOperation{
 constructor(private db:DB){}
 private providerGuard(x:SitesD1PhaseBInput){const clauses=x.expectedProviderLedger.map(()=>"EXISTS(SELECT 1 FROM __appgarden_migrations WHERE id=? AND name=? AND applied_at=?)").join(" AND "),values=x.expectedProviderLedger.flatMap(r=>[r.id,r.name,r.applied_at]);return this.db.prepare(`SELECT CASE WHEN (SELECT COUNT(*) FROM __appgarden_migrations)=? AND ${clauses} THEN 1 ELSE abs(-9223372036854775808) END`).bind(x.expectedProviderLedger.length,...values)}
 private phaseAGuard(x:SitesD1PhaseBInput){const clauses=x.phaseAMigrations.map(()=>"EXISTS(SELECT 1 FROM nearyou_d1_phase_a_migrations WHERE operation_id=? AND migration_id=? AND source_sha256=?)").join(" AND "),values=x.phaseAMigrations.flatMap(m=>[x.phaseAOperationId,m.id,m.sha256]);return this.db.prepare(`SELECT CASE WHEN EXISTS(SELECT 1 FROM nearyou_d1_phase_a_operations WHERE phase='0007-0009' AND operation_id=? AND manifest_sha256=? AND status='complete') AND (SELECT COUNT(*) FROM nearyou_d1_phase_a_migrations WHERE operation_id=?)=? AND ${clauses} THEN 1 ELSE abs(-9223372036854775808) END`).bind(x.phaseAOperationId,x.phaseAManifestSha256,x.phaseAOperationId,x.phaseAMigrations.length,...values)}
 private guards(x:SitesD1PhaseBInput){return[this.providerGuard(x),this.phaseAGuard(x)]}
 private assertion(capture:ProbeCapture){const[,query]=D1_CONVERGENCE_PROBES[capture.index],pairs=PROBE_KEYS[capture.index].flatMap(key=>[`'${key}'`,`"${key}"`]).join(",");return this.db.prepare(`SELECT CASE WHEN COALESCE((SELECT json_group_array(json_object(${pairs})) FROM (${query})),'[]')=? THEN 1 ELSE abs(-9223372036854775808) END`).bind(canonical(capture.rows))}
 private async phaseCaptures(x:SitesD1PhaseBInput,index:number){const ranges=[[0],[1,2,3,4,5],[6,7,8,9,10,11,12]],captures=await captureProbes(this.db,ranges[index]);for(const capture of captures){const expected=x.probeBinding.stages[capture.index];if(!expected||canonical(capture.stage)!==canonical(expected))throw new Error(`phase b affected set drift:${capture.stage.stage}`)}return captures}
 private async schema(x:SitesD1PhaseBInput,head:string){const got=await captureSitesD1PhaseASchemaCheckpoint(this.db,head),want=x.schemaCheckpoints.find(y=>y.head===head)??(head==="0009"?x.phaseAPredecessor:undefined);if(!want||got.objectCount!==want.objectCount||got.definitionsSha256!==want.definitionsSha256)throw new Error(`phase b schema drift:${head}`)}
 private async receipts(x:SitesD1PhaseBInput){const provider=(await this.db.prepare("SELECT id,name,applied_at FROM __appgarden_migrations ORDER BY id").all<Ledger>()).results;if(canonical(provider)!==canonical(x.expectedProviderLedger))throw new Error("phase b provider ledger drift");const op=await this.db.prepare("SELECT operation_id,manifest_sha256,status FROM nearyou_d1_phase_a_operations WHERE phase='0007-0009'").first<{operation_id:string;manifest_sha256:string;status:string}>(),rows=(await this.db.prepare("SELECT migration_id AS id,source_sha256 AS sha256 FROM nearyou_d1_phase_a_migrations WHERE operation_id=? ORDER BY ordinal").bind(x.phaseAOperationId).all<PhaseAMigration>()).results;if(!op||op.operation_id!==x.phaseAOperationId||op.manifest_sha256!==x.phaseAManifestSha256||op.status!=="complete"||canonical(rows)!==canonical(x.phaseAMigrations))throw new Error("phase b phase a receipt drift")}
 async run(x:SitesD1PhaseBInput){
  if(!ID.test(x.operationId)||!ID.test(x.releaseId)||!ID.test(x.phaseAOperationId)||!Number.isSafeInteger(x.issuedAt)||x.expectedProviderLedger.length!==7||x.phaseAMigrations.length!==3||x.migrations.length!==3||x.bootstrap.length!==6||x.probeBinding.version!==1||x.probeBinding.stages.length!==13||![x.phaseAManifestSha256,x.probeContentSha256,x.probeAffectedSetSha256].every(v=>HASH.test(v))||x.migrations.some((m,i)=>!m.id.startsWith(`001${i}_`)||!HASH.test(m.sha256)))throw new Error("phase b input invalid");
  for(const m of x.migrations)if(await sha(m.sql)!==m.sha256)throw new Error("phase b source drift");await this.receipts(x);
  let boot=false,applied:{migration_id:string;source_sha256:string}[]=[];try{await this.schema(x,"0009");const actual=await captureSitesD1PhaseBProbeBinding(this.db);if(canonical(actual)!==canonical(x.probeBinding)||await sha(canonical(actual))!==x.probeContentSha256||await sha(canonical(actual.stages))!==x.probeAffectedSetSha256)throw new Error("phase b probe drift")}catch(error){if(error instanceof Error&&error.message==="phase b probe drift")throw error;boot=true;try{applied=(await this.db.prepare("SELECT migration_id,source_sha256 FROM nearyou_d1_phase_b_migrations ORDER BY applied_at").all<{migration_id:string;source_sha256:string}>()).results}catch{throw new Error("phase b predecessor drift")}const prefix=x.migrations.slice(0,applied.length).map(m=>({migration_id:m.id,source_sha256:m.sha256}));if(canonical(applied)!==canonical(prefix))throw new Error("phase b ledger conflict");await this.schema(x,applied.at(-1)?.migration_id.slice(0,4)??"0009+phase-b-operation")}
  const manifest=await sha(canonical({operationId:x.operationId,releaseId:x.releaseId,issuedAt:x.issuedAt,phaseAOperationId:x.phaseAOperationId,phaseAManifestSha256:x.phaseAManifestSha256,probeContentSha256:x.probeContentSha256,probeAffectedSetSha256:x.probeAffectedSetSha256,migrations:x.migrations.map(({id,sha256})=>({id,sha256}))})),insert=this.db.prepare("INSERT INTO nearyou_d1_phase_b_operations(operation_id,release_id,manifest_sha256,probe_content_sha256,probe_affected_set_sha256,status,created_at) VALUES(?,?,?,?,?,'running',?) ON CONFLICT(operation_id) DO NOTHING").bind(x.operationId,x.releaseId,manifest,x.probeContentSha256,x.probeAffectedSetSha256,x.issuedAt);
  await this.db.batch(boot?[...this.guards(x),insert]:[...this.guards(x),...x.bootstrap.map(s=>this.db.prepare(s)),insert]);const op=await this.db.prepare("SELECT operation_id,release_id,manifest_sha256,status FROM nearyou_d1_phase_b_operations").first<{operation_id:string;release_id:string;manifest_sha256:string;status:string}>();if(!op||op.operation_id!==x.operationId||op.release_id!==x.releaseId||op.manifest_sha256!==manifest)throw new Error("phase b operation conflict");await this.schema(x,boot?(applied.at(-1)?.migration_id.slice(0,4)??"0009+phase-b-operation"):"0009+phase-b-operation");
  for(const[i,m]of x.migrations.entries()){const prior=await this.db.prepare("SELECT migration_id,source_sha256 FROM nearyou_d1_phase_b_migrations WHERE migration_id=?").bind(m.id).first<{migration_id:string;source_sha256:string}>();if(prior){if(prior.source_sha256!==m.sha256)throw new Error("phase b ledger conflict");continue}const checkpoint=x.schemaCheckpoints.find(y=>y.head===m.id.slice(0,4));if(!checkpoint)throw new Error("phase b checkpoint missing");const captures=await this.phaseCaptures(x,i);await this.db.batch([...this.guards(x),...captures.map(c=>this.assertion(c)),...splitD1PhaseBMigration(m.sql).map(s=>this.db.prepare(s)),this.db.prepare("INSERT INTO nearyou_d1_phase_b_migrations VALUES(?,?,?,?,?,?)").bind(m.id,x.operationId,m.sha256,checkpoint.definitionsSha256,checkpoint.objectCount,x.issuedAt+i+1)]);await this.schema(x,m.id.slice(0,4));await this.receipts(x)}
  const rows=(await this.db.prepare("SELECT migration_id,source_sha256 FROM nearyou_d1_phase_b_migrations ORDER BY applied_at").all<{migration_id:string;source_sha256:string}>()).results;if(canonical(rows)!==canonical(x.migrations.map(m=>({migration_id:m.id,source_sha256:m.sha256}))))throw new Error("phase b incomplete");if(op.status!=="complete")await this.db.batch([...this.guards(x),this.db.prepare("UPDATE nearyou_d1_phase_b_operations SET status='complete',completed_at=? WHERE operation_id=? AND status='running'").bind(x.issuedAt,x.operationId)]);await this.receipts(x);return{operationId:x.operationId,status:"complete" as const,manifestSha256:manifest,migrations:rows};
 }
}
