type D1StatementLike={bind(...values:unknown[]):D1StatementLike;all<T>():Promise<{results:T[]}>;first<T>():Promise<T|null>;run():Promise<{meta?:{changes?:number}}>};
type D1Like={prepare(sql:string):D1StatementLike;batch(statements:D1StatementLike[]):Promise<unknown[]>};
type ProviderLedgerRow={id:number;name:string;applied_at:string};
export type ForwardMigration={id:string;sha256:string;sql:string};
export type SchemaCheckpoint={head:string;objectCount:number;definitionsSha256:string;providerObjects?:ReadonlyArray<{type:string;name:string;tableName:string}>};
type Phase="0017-0025"|"0026";
type Authorization={purpose:"d1-0026-separate-authorization";releaseId:string;operationId:string;migrationSha256:string};
export type SitesD1ForwardInput={operationId:string;releaseId:string;phase:Phase;issuedAt:number;expectedProviderLedger:ProviderLedgerRow[];migrations:ForwardMigration[];schemaCheckpoints:SchemaCheckpoint[];authorization?:Authorization};
const HASH=/^[a-f0-9]{64}$/;
const ID=/^[A-Za-z0-9:_-]{8,128}$/;
const FORBIDDEN=/^\s*(?:BEGIN(?:\s+TRANSACTION)?|COMMIT|ROLLBACK|SAVEPOINT|RELEASE)\b/i;
const canonical=(value:unknown)=>JSON.stringify(value);
const PROVIDER_OBJECTS=[{type:"index",name:"sqlite_autoindex_d1_migrations_1",tableName:"d1_migrations"},{type:"table",name:"_cf_METADATA",tableName:"_cf_METADATA"},{type:"table",name:"d1_migrations",tableName:"d1_migrations"},{type:"table",name:"sqlite_sequence",tableName:"sqlite_sequence"},{type:"table",name:"sqlite_stat1",tableName:"sqlite_stat1"}];
async function sha256(value:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(v=>v.toString(16).padStart(2,"0")).join("")}

export function splitD1Migration(sql:string){const statements=sql.split(/^\s*-->\s*statement-breakpoint\s*$/m).map(value=>value.trim()).filter(Boolean);if(!statements.length)throw new Error("migration empty");if(statements.some(value=>FORBIDDEN.test(value)))throw new Error("migration transaction control forbidden");return statements}

export const SITES_D1_OPERATION_BOOTSTRAP=[
 "CREATE TABLE IF NOT EXISTS nearyou_sites_d1_operations(phase TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,release_id TEXT NOT NULL,manifest_sha256 TEXT NOT NULL,issued_at INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN('running','complete')),completed_at INTEGER)",
 "CREATE TABLE IF NOT EXISTS nearyou_sites_d1_operation_migrations(operation_id TEXT NOT NULL,ordinal INTEGER NOT NULL,migration_id TEXT NOT NULL,source_sha256 TEXT NOT NULL,applied_at INTEGER NOT NULL,PRIMARY KEY(operation_id,ordinal),UNIQUE(operation_id,migration_id))",
 "CREATE TRIGGER IF NOT EXISTS nearyou_sites_d1_operation_migrations_update_guard BEFORE UPDATE ON nearyou_sites_d1_operation_migrations BEGIN SELECT RAISE(ABORT,'operation migration immutable'); END",
 "CREATE TRIGGER IF NOT EXISTS nearyou_sites_d1_operation_migrations_delete_guard BEFORE DELETE ON nearyou_sites_d1_operation_migrations BEGIN SELECT RAISE(ABORT,'operation migration immutable'); END",
 "CREATE TRIGGER IF NOT EXISTS nearyou_sites_d1_operations_delete_guard BEFORE DELETE ON nearyou_sites_d1_operations BEGIN SELECT RAISE(ABORT,'operation immutable'); END",
 "CREATE TRIGGER IF NOT EXISTS nearyou_sites_d1_operations_update_guard BEFORE UPDATE ON nearyou_sites_d1_operations WHEN NOT(OLD.operation_id=NEW.operation_id AND OLD.release_id=NEW.release_id AND OLD.phase=NEW.phase AND OLD.manifest_sha256=NEW.manifest_sha256 AND OLD.issued_at=NEW.issued_at AND OLD.status='running' AND NEW.status='complete' AND OLD.completed_at IS NULL AND NEW.completed_at=OLD.issued_at) BEGIN SELECT RAISE(ABORT,'operation immutable'); END"
];

function validate(input:SitesD1ForwardInput){if(!ID.test(input.operationId)||!ID.test(input.releaseId)||!Number.isSafeInteger(input.issuedAt)||input.issuedAt<1||!input.expectedProviderLedger.length||!input.migrations.length||!input.schemaCheckpoints?.length)throw new Error("operation input invalid");for(const [index,m] of input.migrations.entries()){if(!HASH.test(m.sha256))throw new Error("source checksum invalid");const expected=input.phase==="0017-0025"?17+index:26;if(!m.id.startsWith(String(expected).padStart(4,"0")+"_"))throw new Error("phase boundary invalid")}const finalId=input.migrations[input.migrations.length-1]?.id??"";if(input.phase==="0017-0025"&&(input.migrations[0]?.id.slice(0,4)!=="0017"||finalId.slice(0,4)>"0025"))throw new Error("phase boundary invalid");if(input.phase==="0026"){const a=input.authorization;if(input.migrations.length!==1||!a||a.purpose!=="d1-0026-separate-authorization"||a.releaseId!==input.releaseId||a.operationId!==input.operationId||a.migrationSha256!==input.migrations[0]?.sha256)throw new Error("0026 authorization invalid")}}

export class SitesD1ForwardOperation{
 constructor(private readonly db:D1Like){}
 private async assertSchema(checkpoints:SchemaCheckpoint[],head:string){
  const expected=checkpoints.find(value=>value.head===head);if(!expected)throw new Error("schema checkpoint missing");
  const rows=(await this.db.prepare("SELECT type,name,tbl_name AS tableName,rootpage AS rootPage,sql FROM sqlite_schema WHERE type IN ('table','index','trigger','view') ORDER BY type,name,tbl_name").all<{type:string;name:string;tableName:string;rootPage:number;sql:string|null}>()).results;
  const expectedProvider=expected.providerObjects??PROVIDER_OBJECTS,isProvider=(row:{type:string;name:string;tableName:string})=>expectedProvider.some(value=>value.type===row.type&&value.name===row.name&&value.tableName===row.tableName);
  const provider=rows.filter(isProvider).map(({type,name,tableName})=>({type,name,tableName}));if(canonical(provider)!==canonical(expectedProvider))throw new Error("provider schema drift");
  const source=rows.filter(row=>!isProvider(row)).map(({type,name,tableName,sql})=>({type,name,tableName,sql}));if(source.length!==expected.objectCount||await sha256(canonical(source))!==expected.definitionsSha256)throw new Error(`schema checkpoint drift:${head}`)
 }
 async run(input:SitesD1ForwardInput){validate(input);for(const migration of input.migrations)if(await sha256(migration.sql)!==migration.sha256)throw new Error("source checksum invalid");const ledger=(await this.db.prepare("SELECT id,name,applied_at FROM d1_migrations ORDER BY id").all<ProviderLedgerRow>()).results;const manifestSha=await sha256(canonical({operationId:input.operationId,releaseId:input.releaseId,phase:input.phase,issuedAt:input.issuedAt,providerLedger:input.expectedProviderLedger,migrations:input.migrations.map(({id,sha256})=>({id,sha256})),authorization:input.authorization??null}));
  const baselineHead=input.expectedProviderLedger[input.expectedProviderLedger.length-1],timestamp=/^(?:\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}|\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?Z)$/;if(!baselineHead||ledger.some(row=>!Number.isSafeInteger(row.id)||typeof row.name!=="string"||!timestamp.test(row.applied_at))||input.expectedProviderLedger.some(row=>!Number.isSafeInteger(row.id)||typeof row.name!=="string"||!timestamp.test(row.applied_at)))throw new Error("provider ledger drift");const baseline=ledger.slice(0,input.expectedProviderLedger.length);if(canonical(baseline)!==canonical(input.expectedProviderLedger))throw new Error("provider ledger drift");const suffix=ledger.slice(input.expectedProviderLedger.length).map(({id,name})=>({id,name})),expectedSuffix=input.migrations.slice(0,suffix.length).map((migration,index)=>({id:baselineHead.id+index+1,name:migration.id}));if(canonical(suffix)!==canonical(expectedSuffix)||ledger.length>input.expectedProviderLedger.length+input.migrations.length)throw new Error("provider ledger drift");
  const currentHead=ledger.at(-1)?.name.slice(0,4)??"";let bootstrapPresent=false;try{await this.assertSchema(input.schemaCheckpoints,currentHead)}catch{await this.assertSchema(input.schemaCheckpoints,currentHead==="0016"?"0016+operation":currentHead);bootstrapPresent=true}if(!bootstrapPresent)await this.db.batch([...SITES_D1_OPERATION_BOOTSTRAP.map(sql=>this.db.prepare(sql)),this.db.prepare("INSERT INTO nearyou_sites_d1_operations(phase,operation_id,release_id,manifest_sha256,issued_at,status) VALUES(?,?,?,?,?,'running') ON CONFLICT(phase) DO NOTHING").bind(input.phase,input.operationId,input.releaseId,manifestSha,input.issuedAt)])
  const operation=await this.db.prepare("SELECT operation_id,release_id,phase,manifest_sha256,status FROM nearyou_sites_d1_operations WHERE phase=?").bind(input.phase).first<{operation_id:string;release_id:string;phase:string;manifest_sha256:string;status:string}>();if(!operation||operation.operation_id!==input.operationId||operation.release_id!==input.releaseId||operation.phase!==input.phase||operation.manifest_sha256!==manifestSha)throw new Error("operation conflict");if(input.phase==="0026"){const prior=await this.db.prepare("SELECT status FROM nearyou_sites_d1_operations WHERE phase='0017-0025' AND release_id=?").bind(input.releaseId).first<{status:string}>();if(prior?.status!=="complete"||ledger.at(-1)?.name.slice(0,4)!=="0025")throw new Error("0026 predecessor invalid")}
  await this.assertSchema(input.schemaCheckpoints,currentHead==="0016"?"0016+operation":currentHead);for(const [ordinal,migration] of input.migrations.entries()){const prior=await this.db.prepare("SELECT migration_id,source_sha256 FROM nearyou_sites_d1_operation_migrations WHERE operation_id=? AND ordinal=?").bind(input.operationId,ordinal+1).first<{migration_id:string;source_sha256:string}>();if(prior){if(prior.migration_id!==migration.id||prior.source_sha256!==migration.sha256)throw new Error("operation migration conflict");await this.assertSchema(input.schemaCheckpoints,migration.id.slice(0,4));continue}const statements=splitD1Migration(migration.sql).map(sql=>this.db.prepare(sql));statements.push(this.db.prepare("INSERT INTO d1_migrations(name,applied_at) VALUES(?,CURRENT_TIMESTAMP)").bind(migration.id));statements.push(this.db.prepare("INSERT INTO nearyou_sites_d1_operation_migrations(operation_id,ordinal,migration_id,source_sha256,applied_at) VALUES(?,?,?,?,?)").bind(input.operationId,ordinal+1,migration.id,migration.sha256,input.issuedAt+ordinal+1));await this.db.batch(statements);await this.assertSchema(input.schemaCheckpoints,migration.id.slice(0,4))}
  const rows=(await this.db.prepare("SELECT migration_id,source_sha256 FROM nearyou_sites_d1_operation_migrations WHERE operation_id=? ORDER BY ordinal").bind(input.operationId).all<{migration_id:string;source_sha256:string}>()).results;if(canonical(rows)!==canonical(input.migrations.map(({id,sha256})=>({migration_id:id,source_sha256:sha256}))))throw new Error("operation ledger incomplete");if(operation.status!=="complete")await this.db.batch([this.db.prepare("UPDATE nearyou_sites_d1_operations SET status='complete',completed_at=issued_at WHERE phase=? AND operation_id=? AND status='running'").bind(input.phase,input.operationId)]);return{operationId:input.operationId,status:"complete" as const,manifestSha256:manifestSha,migrations:rows};
 }
}
