import { env } from "cloudflare:workers";
import { requireApiAuthContext } from "@/lib/auth";
import { assertTrustedMutationOrigin, jsonNoStore, readJsonObject } from "@/lib/http";
import { base32, protectTotpSecret, revealTotpSecret, verifyTotp } from "@/lib/legacy-mfa";
import { legacyHash } from "@/lib/nearlegacy-route";
import { requireLegacyFreshAuth } from "../production";

function key(){const value=process.env.NEARYOU_MFA_ENCRYPTION_KEY||"";if(!/^[0-9a-f]{64}$/i.test(value))throw new Error("legacy_mfa_key_invalid");return value;}
async function rate(userId:string,operation:string,limit:number){const now=Date.now(),rows=await env.DB.prepare("INSERT INTO legacy_mfa_rate_limits (user_id,operation,window_started_at,request_count) VALUES (?,?,?,1) ON CONFLICT(user_id,operation) DO UPDATE SET window_started_at=CASE WHEN window_started_at+3600000<=? THEN ? ELSE window_started_at END,request_count=CASE WHEN window_started_at+3600000<=? THEN 1 ELSE request_count+1 END RETURNING request_count").bind(userId,operation,now,now,now,now).all();return Number((rows.results?.[0] as Record<string,unknown>|undefined)?.request_count||limit+1)>limit;}
async function freshWithoutMfa(request:Request,userId:string){const challengeId=request.headers.get("x-nearyou-reauth-challenge")?.trim()||"",auth=await requireApiAuthContext(request);if(auth.user.userId!==userId)return null;const rows=await env.DB.prepare("SELECT id FROM account_reauth_challenges WHERE id=? AND user_id=? AND status='verified' AND verified_session_id=? AND expires_at>?").bind(challengeId,userId,auth.sessionId,Date.now()).all();return rows.results?.length?{challengeId,sessionId:auth.sessionId}:null;}
async function householdFor(request:Request,userId:string){const householdId=request.headers.get("x-nearyou-household-id")?.trim()||"";if(!/^[A-Za-z0-9:_-]{1,200}$/.test(householdId))return null;const member=await env.DB.prepare("SELECT id FROM household_members WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,userId).all();return member.results?.length?householdId:null;}

export async function GET(request:Request){try{const{user}=await requireApiAuthContext(request),rows=await env.DB.prepare("SELECT id,method,status,created_at,verified_at FROM legacy_mfa_enrollments WHERE user_id=? AND status IN ('pending','active') ORDER BY created_at DESC LIMIT 1").bind(user.userId).all();return jsonNoStore({enrollment:rows.results?.[0]||null});}catch(error){return error instanceof Response?error:jsonNoStore({error:"MFA status could not be loaded."},{status:500});}}

export async function POST(request:Request){try{assertTrustedMutationOrigin(request);const{user}=await requireApiAuthContext(request);if(await rate(user.userId,"enroll",3))return jsonNoStore({error:"Too many MFA enrollment attempts."},{status:429,headers:{"retry-after":"3600"}});const householdId=await householdFor(request,user.userId),fresh=await freshWithoutMfa(request,user.userId);if(!householdId||!fresh)return jsonNoStore({error:"Complete a fresh sign-in before enrolling MFA."},{status:403});const active=await env.DB.prepare("SELECT id FROM legacy_mfa_enrollments WHERE user_id=? AND status='active'").bind(user.userId).all();if(active.results?.length)return jsonNoStore({error:"MFA is already active."},{status:409});await env.DB.prepare("UPDATE legacy_mfa_enrollments SET status='revoked',revoked_at=? WHERE user_id=? AND status='pending'").bind(Date.now(),user.userId).run();const secret=crypto.getRandomValues(new Uint8Array(20)),protectedSecret=await protectTotpSecret(secret,key()),id=crypto.randomUUID(),now=Date.now();await env.DB.prepare("INSERT INTO legacy_mfa_enrollments (id,user_id,method,status,secret_ciphertext,secret_iv,last_used_counter,reauth_challenge_id,reauth_session_id,created_at) VALUES (?,?,'totp','pending',?,?,-1,?,?,?)").bind(id,user.userId,protectedSecret.ciphertext,protectedSecret.iv,fresh.challengeId,fresh.sessionId,now).run();const issuer=encodeURIComponent("NearYou"),account=encodeURIComponent(user.email),uri=`otpauth://totp/${issuer}:${account}?secret=${base32(secret)}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`;return jsonNoStore({enrollmentId:id,otpauthUri:uri},{status:201});}catch(error){return error instanceof Response?error:jsonNoStore({error:"MFA enrollment could not be started."},{status:500});}}

export async function PUT(request:Request){try{assertTrustedMutationOrigin(request);const{user}=await requireApiAuthContext(request);if(await rate(user.userId,"verify",6))return jsonNoStore({error:"Too many MFA verification attempts."},{status:429,headers:{"retry-after":"3600"}});const householdId=await householdFor(request,user.userId);if(!householdId)return jsonNoStore({error:"An active household is required."},{status:403});const body=await readJsonObject(request,1000),id=String(body.enrollmentId||""),code=String(body.code||""),found=await env.DB.prepare("SELECT secret_ciphertext,secret_iv,last_used_counter,status,reauth_challenge_id,reauth_session_id FROM legacy_mfa_enrollments WHERE id=? AND user_id=?").bind(id,user.userId).all(),row=found.results?.[0] as Record<string,unknown>|undefined;if(!row||row.status!=="pending")return jsonNoStore({error:"MFA enrollment is invalid."},{status:410});const secret=await revealTotpSecret(String(row.secret_ciphertext),String(row.secret_iv),key()),counter=await verifyTotp(secret,code,Date.now(),Number(row.last_used_counter));if(counter===null)return jsonNoStore({error:"The authenticator code is invalid."},{status:403});const now=Date.now(),requestHash=await legacyHash(id),recoveryCodes=Array.from({length:8},()=>crypto.randomUUID().replaceAll("-","").slice(0,12).toUpperCase()),recoveryRows=await Promise.all(recoveryCodes.map(async recovery=>({id:crypto.randomUUID(),hash:await legacyHash(recovery)})));await env.DB.batch([env.DB.prepare("INSERT INTO legacy_security_actions (id,household_id,actor_user_id,action,target_kind,target_id,request_hash,reauth_challenge_id,reauth_session_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(`${id}:activate`,householdId,user.userId,"mfa_enroll","mfa",id,requestHash,row.reauth_challenge_id,row.reauth_session_id,now),env.DB.prepare("UPDATE legacy_mfa_enrollments SET status='active',last_used_counter=?,verified_at=? WHERE id=? AND user_id=? AND status='pending'").bind(counter,now,id,user.userId),...recoveryRows.map(item=>env.DB.prepare("INSERT INTO legacy_mfa_recovery_codes (id,enrollment_id,user_id,code_hash,created_at) VALUES (?,?,?,?,?)").bind(item.id,id,user.userId,item.hash,now))]);return jsonNoStore({enrollment:{id,status:"active",verifiedAt:now},recoveryCodes});}catch(error){return error instanceof Response?error:jsonNoStore({error:"MFA enrollment could not be verified."},{status:500});}}

export async function DELETE(request:Request){try{assertTrustedMutationOrigin(request);const{user}=await requireApiAuthContext(request);if(await rate(user.userId,"revoke",3))return jsonNoStore({error:"Too many MFA changes."},{status:429,headers:{"retry-after":"3600"}});const householdId=await householdFor(request,user.userId),fresh=await requireLegacyFreshAuth(request,user.userId);if(!householdId||!fresh)return jsonNoStore({error:"Fresh sign-in and MFA are required."},{status:403});const active=await env.DB.prepare("SELECT id FROM legacy_mfa_enrollments WHERE user_id=? AND status='active'").bind(user.userId).all(),id=String((active.results?.[0] as Record<string,unknown>|undefined)?.id||"");if(!id)return jsonNoStore({error:"Active MFA was not found."},{status:404});const now=Date.now(),hash=await legacyHash(id);await env.DB.batch([env.DB.prepare("INSERT INTO legacy_security_actions (id,household_id,actor_user_id,action,target_kind,target_id,request_hash,reauth_challenge_id,reauth_session_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(`${crypto.randomUUID()}:security`,householdId,user.userId,"mfa_revoke","mfa",id,hash,fresh.challengeId,fresh.sessionId,now),env.DB.prepare("UPDATE legacy_mfa_enrollments SET status='revoked',revoked_at=? WHERE id=? AND user_id=? AND status='active'").bind(now,id,user.userId)]);return jsonNoStore({status:"revoked"});}catch(error){return error instanceof Response?error:jsonNoStore({error:"MFA could not be revoked."},{status:500});}}
