BEGIN;
DO $$ BEGIN CREATE ROLE nearyou_cutover_policy_owner NOLOGIN NOINHERIT NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE nearyou_cutover_runner NOLOGIN NOINHERIT NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER ROLE nearyou_cutover_policy_owner NOLOGIN NOINHERIT NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER ROLE nearyou_cutover_runner NOLOGIN NOINHERIT NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;

ALTER TABLE nearyou.release_evidence_audit ADD COLUMN claims_projection jsonb;
CREATE TABLE nearyou.release_evidence_transition_uses(
 claims_digest text PRIMARY KEY REFERENCES nearyou.release_evidence_audit(claims_digest),
 release_id text NOT NULL, operation_id text NOT NULL, used_at timestamptz NOT NULL DEFAULT statement_timestamp(),
 UNIQUE(release_id,operation_id)
);
REVOKE ALL ON nearyou.release_evidence_transition_uses FROM PUBLIC,nearyou_cutover_runner,nearyou_release_verifier;
GRANT SELECT,INSERT ON nearyou.release_evidence_transition_uses TO nearyou_cutover_policy_owner;
DROP TRIGGER release_evidence_audit_immutable ON nearyou.release_evidence_audit;
CREATE FUNCTION nearyou.guard_release_evidence_transition_binding() RETURNS trigger LANGUAGE plpgsql SET search_path=nearyou,pg_temp AS $$ BEGIN RAISE EXCEPTION 'release_evidence_audit_immutable'; END $$;
CREATE TRIGGER release_evidence_audit_immutable BEFORE UPDATE OR DELETE ON nearyou.release_evidence_audit FOR EACH ROW EXECUTE FUNCTION nearyou.guard_release_evidence_transition_binding();
ALTER FUNCTION nearyou.guard_release_evidence_transition_binding() OWNER TO nearyou_release_policy_owner;
REVOKE ALL ON FUNCTION nearyou.guard_release_evidence_transition_binding() FROM PUBLIC;
REVOKE ALL ON FUNCTION nearyou.consume_evidence_nonce(text,text,text,text,integer,text,timestamptz) FROM nearyou_release_verifier;
CREATE FUNCTION nearyou.consume_release_evidence(p_nonce text,p_digest text,p_canonical text,p_principal text,p_key text,p_version integer,p_release text,p_expiry timestamptz) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,nearyou_crypto,pg_temp AS $$
DECLARE inserted boolean:=false; claims jsonb; server_now timestamptz:=statement_timestamp(); gate record; result_keys text[];
BEGIN
  IF octet_length(p_canonical)>262144 OR encode(nearyou_crypto.digest(p_canonical,'sha256'),'hex')<>p_digest THEN RETURN false; END IF;
  BEGIN claims:=p_canonical::jsonb; EXCEPTION WHEN others THEN RETURN false; END;
  IF (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(claims) key) IS DISTINCT FROM ARRAY['backfill','expiresAt','fence','gates','highWater','issuedAt','keyId','keyVersion','nonce','notBefore','principal','releaseId','schema','shadow','version']::text[] THEN RETURN false; END IF;
  IF p_nonce!~'^[A-Za-z0-9_-]{22,128}$' OR p_digest!~'^[a-f0-9]{64}$' OR p_release!~'^[A-Za-z0-9_:/.@-]{3,200}$' OR p_expiry<=server_now OR p_expiry>server_now+interval '10 minutes' OR jsonb_typeof(claims->'nonce') IS DISTINCT FROM 'string' OR claims->>'nonce' IS DISTINCT FROM p_nonce OR jsonb_typeof(claims->'releaseId') IS DISTINCT FROM 'string' OR claims->>'releaseId' IS DISTINCT FROM p_release OR jsonb_typeof(claims->'principal') IS DISTINCT FROM 'string' OR claims->>'principal' IS DISTINCT FROM p_principal OR jsonb_typeof(claims->'keyId') IS DISTINCT FROM 'string' OR claims->>'keyId' IS DISTINCT FROM p_key OR jsonb_typeof(claims->'keyVersion') IS DISTINCT FROM 'number' OR (claims->>'keyVersion')::integer IS DISTINCT FROM p_version OR jsonb_typeof(claims->'expiresAt') IS DISTINCT FROM 'number' OR (claims->>'expiresAt')::bigint IS DISTINCT FROM floor(extract(epoch FROM p_expiry)*1000)::bigint OR jsonb_typeof(claims->'gates') IS DISTINCT FROM 'object' OR jsonb_typeof(claims->'shadow') IS DISTINCT FROM 'object' THEN RETURN false; END IF;
  IF (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(claims->'gates') key) IS DISTINCT FROM ARRAY['accessibility','load','media','restore','rls','security']::text[] OR (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(claims->'shadow') key) IS DISTINCT FROM ARRAY['artifact','endedAt','kind','mismatchCount','observedRows','policyVersion','releaseId','sampleCount','schema','sourceChecksum','startedAt','targetChecksum']::text[] THEN RETURN false; END IF;
  IF jsonb_typeof(claims->'version') IS DISTINCT FROM 'number' OR (claims->>'version')::integer IS DISTINCT FROM 1 OR coalesce(claims->>'schema','')!~'^[a-f0-9]{64}$' OR coalesce(claims->>'backfill','')!~'^[a-f0-9]{64}$' OR jsonb_typeof(claims->'notBefore') IS DISTINCT FROM 'number' OR jsonb_typeof(claims->'issuedAt') IS DISTINCT FROM 'number' OR (claims->>'notBefore')::bigint>(claims->>'issuedAt')::bigint OR claims->'shadow'->>'kind' IS DISTINCT FROM 'shadow' OR jsonb_typeof(claims->'shadow'->'policyVersion') IS DISTINCT FROM 'number' OR (claims->'shadow'->>'policyVersion')::integer IS DISTINCT FROM 1 OR claims->'shadow'->>'releaseId' IS DISTINCT FROM p_release OR claims->'shadow'->>'schema' IS DISTINCT FROM claims->>'schema' OR coalesce(claims->'shadow'->>'artifact','')!~'^[a-f0-9]{64}$' OR claims->'shadow'->>'sourceChecksum' IS DISTINCT FROM claims->>'backfill' OR claims->'shadow'->>'targetChecksum' IS DISTINCT FROM claims->>'backfill' OR jsonb_typeof(claims->'shadow'->'startedAt') IS DISTINCT FROM 'number' OR jsonb_typeof(claims->'shadow'->'endedAt') IS DISTINCT FROM 'number' OR (claims->'shadow'->>'startedAt')::bigint<(claims->>'notBefore')::bigint OR (claims->'shadow'->>'endedAt')::bigint>(claims->>'issuedAt')::bigint OR (claims->'shadow'->>'endedAt')::bigint-(claims->'shadow'->>'startedAt')::bigint<60000 OR jsonb_typeof(claims->'shadow'->'sampleCount') IS DISTINCT FROM 'number' OR (claims->'shadow'->>'sampleCount')::bigint<3 OR jsonb_typeof(claims->'shadow'->'observedRows') IS DISTINCT FROM 'number' OR (claims->'shadow'->>'observedRows')::bigint<0 OR jsonb_typeof(claims->'shadow'->'mismatchCount') IS DISTINCT FROM 'number' OR (claims->'shadow'->>'mismatchCount')::bigint IS DISTINCT FROM 0 OR jsonb_typeof(claims->'highWater') IS DISTINCT FROM 'number' OR (claims->>'highWater')::bigint<0 OR jsonb_typeof(claims->'fence') IS DISTINCT FROM 'number' OR (claims->>'fence')::bigint<1 THEN RETURN false; END IF;
  FOR gate IN SELECT key,value FROM jsonb_each(claims->'gates') LOOP
    IF jsonb_typeof(gate.value) IS DISTINCT FROM 'object' OR (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(gate.value) key) IS DISTINCT FROM ARRAY['artifact','kind','policyVersion','releaseId','results','schema','verifiedAt']::text[] OR gate.value->>'kind' IS DISTINCT FROM gate.key OR gate.value->>'releaseId' IS DISTINCT FROM p_release OR gate.value->>'schema' IS DISTINCT FROM claims->>'schema' OR coalesce(gate.value->>'artifact','')!~'^[a-f0-9]{64}$' OR jsonb_typeof(gate.value->'policyVersion') IS DISTINCT FROM 'number' OR (gate.value->>'policyVersion')::integer IS DISTINCT FROM 1 OR jsonb_typeof(gate.value->'verifiedAt') IS DISTINCT FROM 'number' OR (gate.value->>'verifiedAt')::bigint NOT BETWEEN (claims->>'notBefore')::bigint AND (claims->>'issuedAt')::bigint OR jsonb_typeof(gate.value->'results') IS DISTINCT FROM 'object' THEN RETURN false; END IF;
    SELECT array_agg(key ORDER BY key) INTO result_keys FROM jsonb_object_keys(gate.value->'results') key;
    IF gate.key='rls' AND (result_keys IS DISTINCT FROM ARRAY['crossTenantViolations','negativeTests']::text[] OR (gate.value->'results'->>'negativeTests')::bigint<1 OR (gate.value->'results'->>'crossTenantViolations')::bigint IS DISTINCT FROM 0) THEN RETURN false;
    ELSIF gate.key='media' AND (result_keys IS DISTINCT FROM ARRAY['canaries','failed']::text[] OR (gate.value->'results'->>'canaries')::bigint<1 OR (gate.value->'results'->>'failed')::bigint IS DISTINCT FROM 0) THEN RETURN false;
    ELSIF gate.key='restore' AND (result_keys IS DISTINCT FROM ARRAY['checksumMismatches','restoredObjects']::text[] OR (gate.value->'results'->>'restoredObjects')::bigint<1 OR (gate.value->'results'->>'checksumMismatches')::bigint IS DISTINCT FROM 0) THEN RETURN false;
    ELSIF gate.key='accessibility' AND (result_keys IS DISTINCT FROM ARRAY['checks','violations']::text[] OR (gate.value->'results'->>'checks')::bigint<1 OR (gate.value->'results'->>'violations')::bigint IS DISTINCT FROM 0) THEN RETURN false;
    ELSIF gate.key='security' AND (result_keys IS DISTINCT FROM ARRAY['critical','high','penTestArtifact','scanArtifact']::text[] OR (gate.value->'results'->>'critical')::bigint IS DISTINCT FROM 0 OR (gate.value->'results'->>'high')::bigint IS DISTINCT FROM 0 OR coalesce(gate.value->'results'->>'scanArtifact','')!~'^[a-f0-9]{64}$' OR coalesce(gate.value->'results'->>'penTestArtifact','')!~'^[a-f0-9]{64}$') THEN RETURN false;
    ELSIF gate.key='load' AND (result_keys IS DISTINCT FROM ARRAY['errorRateBps','maxErrorRateBps','maxP95Ms','p95Ms','requests']::text[] OR (gate.value->'results'->>'requests')::bigint<1 OR (gate.value->'results'->>'errorRateBps')::bigint NOT BETWEEN 0 AND 10000 OR (gate.value->'results'->>'maxErrorRateBps')::bigint NOT BETWEEN 0 AND 10000 OR (gate.value->'results'->>'errorRateBps')::bigint>(gate.value->'results'->>'maxErrorRateBps')::bigint OR (gate.value->'results'->>'p95Ms')::bigint NOT BETWEEN 1 AND 600000 OR (gate.value->'results'->>'maxP95Ms')::bigint NOT BETWEEN 1 AND 600000 OR (gate.value->'results'->>'p95Ms')::bigint>(gate.value->'results'->>'maxP95Ms')::bigint) THEN RETURN false;
    END IF;
  END LOOP;
  INSERT INTO nearyou.consumed_evidence_nonces(nonce,claims_digest,principal,key_id,key_version,release_id,expires_at,consumed_at) VALUES(p_nonce,p_digest,p_principal,p_key,p_version,p_release,p_expiry,server_now) ON CONFLICT DO NOTHING RETURNING true INTO inserted;
  IF inserted THEN INSERT INTO nearyou.release_evidence_audit(nonce_hash,claims_digest,principal,key_id,key_version,release_id,consumed_at,claims_projection) VALUES(encode(nearyou_crypto.digest(p_nonce,'sha256'),'hex'),p_digest,p_principal,p_key,p_version,p_release,server_now,claims); END IF;
  RETURN coalesce(inserted,false);
EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RETURN false;
END $$;
ALTER FUNCTION nearyou.consume_release_evidence(text,text,text,text,text,integer,text,timestamptz) OWNER TO nearyou_release_policy_owner;
REVOKE ALL ON FUNCTION nearyou.consume_release_evidence(text,text,text,text,text,integer,text,timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.consume_release_evidence(text,text,text,text,text,integer,text,timestamptz) TO nearyou_release_verifier;

CREATE TABLE nearyou.cutover_runtime_state (
 release_id text PRIMARY KEY CHECK (release_id ~ '^[A-Za-z0-9_.:@/-]{3,200}$'), routing_mode text NOT NULL DEFAULT 'd1' CHECK (routing_mode IN ('d1','postgres')),
 lease_owner text, lease_fence bigint NOT NULL DEFAULT 0 CHECK (lease_fence>=0), lease_expires_at timestamptz,
 snapshot_high_water bigint CHECK (snapshot_high_water>=0), snapshot_cursor bigint CHECK (snapshot_cursor>=0),
 transition_operation_id text, transition_freeze_token text, transition_high_water bigint CHECK (transition_high_water>=0), transition_evidence_digest text CHECK (transition_evidence_digest ~ '^[a-f0-9]{64}$'), updated_at timestamptz NOT NULL DEFAULT statement_timestamp()
);
CREATE TABLE nearyou.cutover_operation_manifests (
 kind text NOT NULL CHECK(kind IN ('freeze','backfill_page','delta','transition','rollback_capture','rollback_page','rollback_transition')), operation_id text NOT NULL,
 release_id text NOT NULL REFERENCES nearyou.cutover_runtime_state(release_id), fence bigint NOT NULL CHECK(fence>0), manifest jsonb NOT NULL,
 created_at timestamptz NOT NULL DEFAULT statement_timestamp(), PRIMARY KEY(release_id,kind,operation_id)
);
CREATE TABLE nearyou.cutover_target_rows(release_id text NOT NULL REFERENCES nearyou.cutover_runtime_state(release_id),household_id text NOT NULL,source_table text NOT NULL,source_id text NOT NULL,payload jsonb NOT NULL,source_sequence bigint NOT NULL CHECK(source_sequence>0),source_page_checksum text NOT NULL CHECK(source_page_checksum~'^[a-f0-9]{64}$'),PRIMARY KEY(release_id,household_id,source_table,source_id));
ALTER TABLE nearyou.cutover_target_rows ADD COLUMN canonical_row_digest bytea CHECK(octet_length(canonical_row_digest)=32);
CREATE FUNCTION nearyou.cutover_state_checksum(p_release text) RETURNS TABLE(checksum text,row_count bigint) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=nearyou,nearyou_crypto,pg_temp AS $$ SELECT encode(digest(coalesce(string_agg(canonical_row_digest,'' ORDER BY convert_to(household_id,E'UTF8'),convert_to(source_table,E'UTF8'),convert_to(source_id,E'UTF8')),''::bytea),'sha256'),'hex'),count(*) FROM nearyou.cutover_target_rows WHERE release_id=p_release HAVING count(*)=count(canonical_row_digest) $$;
ALTER FUNCTION nearyou.cutover_state_checksum(text) OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON FUNCTION nearyou.cutover_state_checksum(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.cutover_state_checksum(text) TO nearyou_cutover_policy_owner;
CREATE TABLE nearyou.rollback_runtime_state (
 release_id text PRIMARY KEY REFERENCES nearyou.cutover_runtime_state(release_id), capture_id text NOT NULL, drain_token text NOT NULL, status text NOT NULL CHECK(status IN ('drained','completed')),
 fence bigint NOT NULL CHECK(fence>0), high_water bigint NOT NULL CHECK(high_water>=0), cursor bigint, prior_manifest_checksum text NOT NULL CHECK(prior_manifest_checksum ~ '^[a-f0-9]{64}$'),
 manifest_checksum text, row_count bigint NOT NULL DEFAULT 0 CHECK(row_count>=0), updated_at timestamptz NOT NULL DEFAULT statement_timestamp(), CHECK(cursor IS NULL OR cursor BETWEEN 0 AND high_water)
);
REVOKE ALL ON nearyou.cutover_runtime_state,nearyou.cutover_operation_manifests,nearyou.cutover_target_rows,nearyou.rollback_runtime_state FROM PUBLIC,nearyou_cutover_runner;
GRANT USAGE ON SCHEMA nearyou TO nearyou_cutover_policy_owner,nearyou_cutover_runner;
GRANT SELECT,INSERT,UPDATE ON nearyou.cutover_runtime_state,nearyou.cutover_operation_manifests,nearyou.rollback_runtime_state TO nearyou_cutover_policy_owner;
GRANT SELECT,INSERT,UPDATE,DELETE ON nearyou.cutover_target_rows TO nearyou_cutover_policy_owner;
GRANT SELECT ON nearyou.release_evidence_audit TO nearyou_cutover_policy_owner;

CREATE FUNCTION nearyou.current_cutover_time() RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT floor(extract(epoch FROM statement_timestamp())*1000)::bigint $$;
CREATE FUNCTION nearyou.acquire_cutover_lease(p_release text,p_owner text) RETURNS TABLE(owner text,fence bigint,expires_at_ms bigint) LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN INSERT INTO nearyou.cutover_runtime_state(release_id) VALUES(p_release) ON CONFLICT DO NOTHING; UPDATE nearyou.cutover_runtime_state SET lease_owner=p_owner,lease_fence=CASE WHEN lease_owner=p_owner AND lease_expires_at>statement_timestamp() THEN lease_fence ELSE lease_fence+1 END,lease_expires_at=statement_timestamp()+interval '2 minutes',updated_at=statement_timestamp() WHERE release_id=p_release AND (lease_expires_at IS NULL OR lease_expires_at<=statement_timestamp() OR lease_owner=p_owner); RETURN QUERY SELECT lease_owner,lease_fence,floor(extract(epoch FROM lease_expires_at)*1000)::bigint FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner FOR UPDATE; END $$;
CREATE FUNCTION nearyou.renew_cutover_lease(p_release text,p_owner text,p_fence bigint) RETURNS TABLE(owner text,fence bigint,expires_at_ms bigint) LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN UPDATE nearyou.cutover_runtime_state SET lease_expires_at=statement_timestamp()+interval '2 minutes',updated_at=statement_timestamp() WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp(); RETURN QUERY SELECT lease_owner,lease_fence,floor(extract(epoch FROM lease_expires_at)*1000)::bigint FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence FOR UPDATE; END $$;
CREATE FUNCTION nearyou.initialize_cutover_snapshot(p_release text,p_owner text,p_fence bigint,p_high_water bigint) RETURNS TABLE(high_water bigint,cursor bigint,fence bigint) LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN UPDATE nearyou.cutover_runtime_state SET snapshot_high_water=coalesce(snapshot_high_water,p_high_water),snapshot_cursor=coalesce(snapshot_cursor,0),updated_at=statement_timestamp() WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND (snapshot_high_water IS NULL OR snapshot_high_water=p_high_water); RETURN QUERY SELECT snapshot_high_water,NULLIF(snapshot_cursor,0),lease_fence FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence FOR UPDATE; END $$;
CREATE FUNCTION nearyou.record_cutover_operation(p_release text,p_kind text,p_operation text,p_fence bigint,p_manifest jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN INSERT INTO nearyou.cutover_operation_manifests(kind,operation_id,release_id,fence,manifest) SELECT p_kind,p_operation,p_release,p_fence,p_manifest FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() ON CONFLICT DO NOTHING; RETURN (SELECT manifest FROM nearyou.cutover_operation_manifests WHERE release_id=p_release AND kind=p_kind AND operation_id=p_operation); END $$;
CREATE FUNCTION nearyou.transition_cutover(p_release text,p_operation text,p_fence bigint,p_freeze text,p_high_water bigint,p_evidence text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN UPDATE nearyou.cutover_runtime_state SET routing_mode='postgres',transition_operation_id=p_operation,transition_freeze_token=p_freeze,transition_high_water=p_high_water,transition_evidence_digest=p_evidence,updated_at=statement_timestamp() WHERE release_id=p_release AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND routing_mode='d1' AND EXISTS(SELECT 1 FROM nearyou.release_evidence_audit WHERE claims_digest=p_evidence AND release_id=p_release); RETURN FOUND; END $$;
CREATE FUNCTION nearyou.begin_rollback_capture(p_release text,p_capture text,p_fence bigint,p_drain text,p_high_water bigint,p_prior text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN INSERT INTO nearyou.rollback_runtime_state(release_id,capture_id,drain_token,status,fence,high_water,prior_manifest_checksum) SELECT p_release,p_capture,p_drain,'drained',p_fence,p_high_water,p_prior FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND routing_mode='postgres' AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() ON CONFLICT(release_id) DO NOTHING; RETURN (SELECT to_jsonb(r) FROM nearyou.rollback_runtime_state r WHERE release_id=p_release FOR UPDATE); END $$;
CREATE FUNCTION nearyou.refence_rollback(p_release text,p_capture text,p_previous bigint,p_fence bigint) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN UPDATE nearyou.rollback_runtime_state SET fence=p_fence,updated_at=statement_timestamp() WHERE release_id=p_release AND capture_id=p_capture AND fence=p_previous AND EXISTS(SELECT 1 FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_fence=p_fence AND lease_expires_at>statement_timestamp()); RETURN (SELECT jsonb_build_object('capture',to_jsonb(r),'manifest',(SELECT manifest FROM nearyou.cutover_operation_manifests WHERE release_id=p_release AND kind='rollback_page' ORDER BY created_at DESC LIMIT 1)) FROM nearyou.rollback_runtime_state r WHERE release_id=p_release FOR UPDATE); END $$;
CREATE FUNCTION nearyou.record_rollback_manifest(p_release text,p_capture text,p_fence bigint,p_operation text,p_manifest jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN INSERT INTO nearyou.cutover_operation_manifests(kind,operation_id,release_id,fence,manifest) SELECT 'rollback_page',p_operation,p_release,p_fence,p_manifest FROM nearyou.rollback_runtime_state WHERE release_id=p_release AND capture_id=p_capture AND fence=p_fence ON CONFLICT DO NOTHING; RETURN (SELECT manifest FROM nearyou.cutover_operation_manifests WHERE release_id=p_release AND kind='rollback_page' AND operation_id=p_operation); END $$;
CREATE FUNCTION nearyou.transition_rollback(p_release text,p_capture text,p_fence bigint,p_operation text,p_manifest jsonb) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ BEGIN UPDATE nearyou.cutover_runtime_state SET routing_mode='d1',updated_at=statement_timestamp() WHERE release_id=p_release AND routing_mode='postgres' AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND EXISTS(SELECT 1 FROM nearyou.rollback_runtime_state WHERE release_id=p_release AND capture_id=p_capture AND fence=p_fence AND status='drained'); IF FOUND THEN INSERT INTO nearyou.cutover_operation_manifests(kind,operation_id,release_id,fence,manifest) VALUES('rollback_transition',p_operation,p_release,p_fence,p_manifest) ON CONFLICT DO NOTHING; UPDATE nearyou.rollback_runtime_state SET status='completed',updated_at=statement_timestamp() WHERE release_id=p_release; END IF; RETURN FOUND; END $$;

CREATE FUNCTION nearyou.load_cutover_checkpoint(p_release text,p_owner text,p_fence bigint) RETURNS TABLE(high_water bigint,cursor bigint,fence bigint) LANGUAGE sql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ SELECT snapshot_high_water,NULLIF(snapshot_cursor,0),lease_fence FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() $$;
CREATE FUNCTION nearyou.cutover_node_count(value jsonb,depth integer DEFAULT 0) RETURNS integer
LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE total integer:=1; child jsonb; tag text;
BEGIN
  IF depth>32 OR jsonb_typeof(value)<>'array' OR jsonb_array_length(value)<1 THEN RAISE EXCEPTION 'cutover value invalid'; END IF;
  tag:=value->>0;
  IF tag='array' AND jsonb_array_length(value)=2 AND jsonb_typeof(value->1)='array' THEN FOR child IN SELECT element FROM jsonb_array_elements(value->1) AS parts(element) LOOP total:=total+nearyou.cutover_node_count(child,depth+1); IF total>10000 THEN RAISE EXCEPTION 'cutover node budget exceeded'; END IF; END LOOP;
  ELSIF tag='object' AND jsonb_array_length(value)=2 AND jsonb_typeof(value->1)='array' THEN FOR child IN SELECT element->1 FROM jsonb_array_elements(value->1) AS parts(element) LOOP total:=total+1+nearyou.cutover_node_count(child,depth+1); IF total>10000 THEN RAISE EXCEPTION 'cutover node budget exceeded'; END IF; END LOOP;
  END IF;
  RETURN total;
END $$;
CREATE FUNCTION nearyou.decode_cutover_value(value jsonb,depth integer DEFAULT 0,node_budget integer DEFAULT 10000) RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE tag text; result jsonb; entry jsonb; prior_key text; nodes integer;
BEGIN
  IF depth=0 AND nearyou.cutover_node_count(value,0)>10000 THEN RAISE EXCEPTION 'cutover node budget exceeded'; END IF;
  IF depth>32 OR node_budget<1 OR jsonb_typeof(value)<>'array' OR jsonb_array_length(value)<1 THEN RAISE EXCEPTION 'cutover value invalid'; END IF;
  tag:=value->>0;
  IF tag='null' AND jsonb_array_length(value)=1 THEN RETURN 'null'::jsonb;
  ELSIF tag='string' AND jsonb_array_length(value)=2 AND jsonb_typeof(value->1)='string' THEN RETURN value->1;
  ELSIF tag='boolean' AND jsonb_array_length(value)=2 AND jsonb_typeof(value->1)='boolean' THEN RETURN value->1;
  ELSIF tag='number' AND jsonb_array_length(value)=2 AND value->>1~'^(0|-?[1-9][0-9]{0,15})$' AND abs((value->>1)::numeric)<=9007199254740991 THEN RETURN to_jsonb((value->>1)::numeric);
  ELSIF tag='array' AND jsonb_array_length(value)=2 AND jsonb_typeof(value->1)='array' THEN nodes:=jsonb_array_length(value->1); IF nodes+1>node_budget THEN RAISE EXCEPTION 'cutover node budget exceeded'; END IF; SELECT coalesce(jsonb_agg(nearyou.decode_cutover_value(element,depth+1,node_budget-nodes-1) ORDER BY ordinal),'[]'::jsonb) INTO result FROM jsonb_array_elements(value->1) WITH ORDINALITY AS parts(element,ordinal); RETURN result;
  ELSIF tag='object' AND jsonb_array_length(value)=2 AND jsonb_typeof(value->1)='array' THEN nodes:=jsonb_array_length(value->1); IF nodes*2+1>node_budget THEN RAISE EXCEPTION 'cutover node budget exceeded'; END IF; result:='{}'::jsonb; FOR entry IN SELECT element FROM jsonb_array_elements(value->1) AS parts(element) LOOP IF jsonb_typeof(entry)<>'array' OR jsonb_array_length(entry)<>2 OR jsonb_typeof(entry->0)<>'string' OR (prior_key IS NOT NULL AND convert_to(prior_key,'UTF8')>=convert_to(entry->>0,'UTF8')) THEN RAISE EXCEPTION 'cutover object invalid'; END IF; prior_key:=entry->>0; result:=result||jsonb_build_object(entry->>0,nearyou.decode_cutover_value(entry->1,depth+1,node_budget-nodes*2-1)); END LOOP; RETURN result;
  END IF;
  RAISE EXCEPTION 'cutover value invalid';
END $$;
CREATE FUNCTION nearyou.apply_cutover_page(p_release text,p_owner text,p_fence bigint,p_high_water bigint,p_cursor bigint,p_next bigint,p_operation text,p_rows jsonb,p_canonical_rows text,p_count integer,p_checksum text,p_transports jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,nearyou_crypto,pg_temp AS $$
DECLARE
  item jsonb; transport jsonb; row_bytes bytea; reconstructed bytea:=convert_to('[','UTF8'); ordinal bigint; prior bigint:=coalesce(p_cursor,0); canonical_bytes bytea; canonical_json jsonb;
  expected_manifest jsonb:=jsonb_build_object('releaseId',p_release,'fence',p_fence,'highWater',p_high_water,'cursor',coalesce(p_cursor,0),'nextCursor',p_next,'operationId',p_operation,'checksum',p_checksum,'rowCount',p_count,'rowsChecksum',p_checksum);
  saved_manifest jsonb; inserted boolean:=false;
BEGIN
  IF p_operation<>format('backfill:%s:%s:%s',p_fence,coalesce(p_cursor,0),p_next) OR length(p_canonical_rows)>1400000 OR p_canonical_rows!~'^[A-Za-z0-9+/]*={0,2}$' THEN RETURN NULL; END IF;
  BEGIN canonical_bytes:=decode(p_canonical_rows,'base64'); canonical_json:=convert_from(canonical_bytes,'UTF8')::jsonb; EXCEPTION WHEN others THEN RETURN NULL; END;
  IF jsonb_typeof(p_rows)<>'array' OR p_rows<>canonical_json OR jsonb_array_length(p_rows)<>p_count OR p_count<1 OR p_count>1000 OR octet_length(canonical_bytes)>1048576 OR p_checksum!~'^[a-f0-9]{64}$' OR encode(digest(canonical_bytes,'sha256'),'hex')<>p_checksum THEN RETURN NULL; END IF;
  IF jsonb_typeof(p_transports)<>'array' OR jsonb_array_length(p_transports)<>p_count OR octet_length(p_transports::text)>6000000 THEN RETURN NULL; END IF;
  FOR item,ordinal IN SELECT value,ordinality FROM jsonb_array_elements(p_rows) WITH ORDINALITY LOOP transport:=p_transports->(ordinal-1); IF jsonb_typeof(transport)<>'object' OR (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(transport) key) IS DISTINCT FROM ARRAY['canonicalBase64','deleted','digest','key']::text[] OR jsonb_typeof(transport->'canonicalBase64')<>'string' OR length(transport->>'canonicalBase64')>400000 OR transport->>'canonicalBase64'!~'^[A-Za-z0-9+/]*={0,2}$' OR jsonb_typeof(transport->'digest')<>'string' OR transport->>'digest'!~'^[a-f0-9]{64}$' OR jsonb_typeof(transport->'key')<>'array' OR jsonb_array_length(transport->'key')<>3 OR EXISTS(SELECT 1 FROM jsonb_array_elements(transport->'key') v WHERE jsonb_typeof(v)<>'string' OR octet_length(v#>>'{}') NOT BETWEEN 1 AND 200) OR transport->'key'<>jsonb_build_array(item->>1,item->>2,item->>3) OR jsonb_typeof(transport->'deleted')<>'boolean' OR (transport->>'deleted')::boolean<>(item->>5)::boolean THEN RETURN NULL; END IF; BEGIN row_bytes:=decode(transport->>'canonicalBase64','base64'); IF replace(encode(row_bytes,'base64'),E'\n','')<>transport->>'canonicalBase64' OR convert_from(row_bytes,'UTF8') IS NULL THEN RETURN NULL; END IF; EXCEPTION WHEN others THEN RETURN NULL; END; IF octet_length(row_bytes)<3 OR octet_length(row_bytes)>300000 OR get_byte(row_bytes,0)<>91 OR get_byte(row_bytes,octet_length(row_bytes)-1)<>93 OR encode(digest(row_bytes,'sha256'),'hex')<>transport->>'digest' THEN RETURN NULL; END IF; reconstructed:=reconstructed||CASE WHEN ordinal>1 THEN convert_to(',','UTF8') ELSE ''::bytea END||substring(row_bytes FROM 2 FOR octet_length(row_bytes)-2); END LOOP; reconstructed:=reconstructed||convert_to(']','UTF8'); IF reconstructed<>canonical_bytes THEN RETURN NULL; END IF;
  FOR item IN SELECT value FROM jsonb_array_elements(p_rows) LOOP
    IF jsonb_typeof(item)<>'array' OR jsonb_array_length(item)<>7 OR item->>0<>'row' OR coalesce(octet_length(item->>1),0) NOT BETWEEN 1 AND 200 OR coalesce(octet_length(item->>2),0) NOT BETWEEN 1 AND 200 OR coalesce(octet_length(item->>3),0) NOT BETWEEN 1 AND 200 OR jsonb_typeof(item->4)<>'number' OR jsonb_typeof(item->5)<>'boolean' OR (item->>4)::bigint<>prior+1 OR octet_length(nearyou.decode_cutover_value(item->6)::text)>262144 THEN RETURN NULL; END IF;
    prior:=(item->>4)::bigint;
  END LOOP;
  IF prior<>p_next THEN RETURN NULL; END IF;
  SELECT manifest INTO saved_manifest FROM nearyou.cutover_operation_manifests WHERE release_id=p_release AND kind='backfill_page' AND operation_id=p_operation;
  IF FOUND THEN IF saved_manifest=expected_manifest THEN RETURN saved_manifest; END IF; RETURN NULL; END IF;
  PERFORM 1 FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND snapshot_high_water=p_high_water AND coalesce(snapshot_cursor,0)=coalesce(p_cursor,0) FOR UPDATE;
  IF NOT FOUND THEN RETURN NULL; END IF;
  INSERT INTO nearyou.cutover_operation_manifests(kind,operation_id,release_id,fence,manifest) VALUES('backfill_page',p_operation,p_release,p_fence,expected_manifest) ON CONFLICT DO NOTHING RETURNING true INTO inserted;
  IF NOT coalesce(inserted,false) THEN SELECT manifest INTO saved_manifest FROM nearyou.cutover_operation_manifests WHERE release_id=p_release AND kind='backfill_page' AND operation_id=p_operation; IF saved_manifest=expected_manifest THEN RETURN saved_manifest; END IF; RETURN NULL; END IF;
  FOR item IN SELECT value FROM jsonb_array_elements(p_rows) LOOP
    prior:=(item->>4)::bigint;
    IF (item->>5)::boolean THEN DELETE FROM nearyou.cutover_target_rows WHERE release_id=p_release AND household_id=item->>1 AND source_table=item->>2 AND source_id=item->>3;
    ELSE transport:=p_transports->(prior-coalesce(p_cursor,0)-1); INSERT INTO nearyou.cutover_target_rows(release_id,household_id,source_table,source_id,payload,source_sequence,source_page_checksum,canonical_row_digest) VALUES(p_release,item->>1,item->>2,item->>3,nearyou.decode_cutover_value(item->6),prior,p_checksum,decode(transport->>'digest','hex')) ON CONFLICT(release_id,household_id,source_table,source_id) DO UPDATE SET payload=excluded.payload,source_sequence=excluded.source_sequence,source_page_checksum=excluded.source_page_checksum,canonical_row_digest=excluded.canonical_row_digest WHERE nearyou.cutover_target_rows.source_sequence<=excluded.source_sequence;
    END IF;
  END LOOP;
  UPDATE nearyou.cutover_runtime_state SET snapshot_cursor=p_next,updated_at=statement_timestamp() WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND snapshot_high_water=p_high_water AND coalesce(snapshot_cursor,0)=coalesce(p_cursor,0);
  IF NOT FOUND THEN RAISE EXCEPTION 'cutover page fence lost'; END IF;
  RETURN expected_manifest;
END $$;
ALTER TABLE nearyou.cutover_runtime_state ADD COLUMN delta_freeze_token text, ADD COLUMN delta_cursor bigint CHECK(delta_cursor>=0), ADD COLUMN delta_final_high_water bigint CHECK(delta_final_high_water>=0);
ALTER TABLE nearyou.cutover_runtime_state ADD COLUMN shadow_evidence_digest text CHECK(shadow_evidence_digest~'^[a-f0-9]{64}$');
CREATE FUNCTION nearyou.load_cutover_delta(p_release text,p_owner text,p_fence bigint,p_freeze text,p_final bigint) RETURNS TABLE(freeze_token text,delta_cursor bigint,final_high_water bigint,fence bigint) LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$
BEGIN UPDATE nearyou.cutover_runtime_state SET delta_freeze_token=coalesce(delta_freeze_token,p_freeze),delta_cursor=coalesce(delta_cursor,snapshot_high_water),delta_final_high_water=coalesce(delta_final_high_water,p_final),updated_at=statement_timestamp() WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND snapshot_cursor=snapshot_high_water AND p_final>=snapshot_high_water AND (delta_freeze_token IS NULL OR delta_freeze_token=p_freeze) AND (delta_final_high_water IS NULL OR delta_final_high_water=p_final); RETURN QUERY SELECT delta_freeze_token,delta_cursor,delta_final_high_water,lease_fence FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND delta_freeze_token=p_freeze AND delta_final_high_water=p_final FOR UPDATE; END $$;
CREATE FUNCTION nearyou.apply_cutover_delta(p_release text,p_owner text,p_fence bigint,p_freeze text,p_from bigint,p_to bigint,p_final bigint,p_operation text,p_rows jsonb,p_canonical text,p_count integer,p_checksum text,p_manifest_checksum text,p_transports jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,nearyou_crypto,pg_temp AS $$
DECLARE item jsonb; transport jsonb; row_bytes bytea; reconstructed bytea:=convert_to('[','UTF8'); ordinal bigint; prior bigint:=p_from; bytes bytea; expected jsonb:=jsonb_build_object('releaseId',p_release,'fence',p_fence,'freezeToken',p_freeze,'from',p_from,'to',p_to,'finalHighWater',p_final,'operationId',p_operation,'rowCount',p_count,'rowsChecksum',p_checksum); saved jsonb;
BEGIN IF p_operation<>format('delta:%s:%s:%s',p_fence,p_from,p_to) OR p_count<1 OR p_count>1000 OR p_to<>p_from+p_count OR p_to>p_final OR p_checksum!~'^[a-f0-9]{64}$' OR p_manifest_checksum<>p_checksum OR length(p_canonical)>1400000 OR p_canonical!~'^[A-Za-z0-9+/]*={0,2}$' THEN RETURN NULL; END IF; BEGIN bytes:=decode(p_canonical,'base64'); IF octet_length(bytes)>1048576 THEN RETURN NULL; END IF; IF convert_from(bytes,'UTF8')::jsonb<>p_rows THEN RETURN NULL; END IF; EXCEPTION WHEN others THEN RETURN NULL; END; IF jsonb_typeof(p_rows)<>'array' OR encode(digest(bytes,'sha256'),'hex')<>p_checksum OR jsonb_array_length(p_rows)<>p_count THEN RETURN NULL; END IF;
IF jsonb_typeof(p_transports)<>'array' OR jsonb_array_length(p_transports)<>p_count OR octet_length(p_transports::text)>6000000 THEN RETURN NULL; END IF;
FOR item,ordinal IN SELECT value,ordinality FROM jsonb_array_elements(p_rows) WITH ORDINALITY LOOP transport:=p_transports->(ordinal-1); IF jsonb_typeof(transport)<>'object' OR (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(transport) key) IS DISTINCT FROM ARRAY['canonicalBase64','deleted','digest','key']::text[] OR jsonb_typeof(transport->'canonicalBase64')<>'string' OR length(transport->>'canonicalBase64')>400000 OR transport->>'canonicalBase64'!~'^[A-Za-z0-9+/]*={0,2}$' OR jsonb_typeof(transport->'digest')<>'string' OR transport->>'digest'!~'^[a-f0-9]{64}$' OR jsonb_typeof(transport->'key')<>'array' OR jsonb_array_length(transport->'key')<>3 OR EXISTS(SELECT 1 FROM jsonb_array_elements(transport->'key') v WHERE jsonb_typeof(v)<>'string' OR octet_length(v#>>'{}') NOT BETWEEN 1 AND 200) OR transport->'key'<>jsonb_build_array(item->>1,item->>2,item->>3) OR jsonb_typeof(transport->'deleted')<>'boolean' OR (transport->>'deleted')::boolean<>(item->>5)::boolean THEN RETURN NULL; END IF; BEGIN row_bytes:=decode(transport->>'canonicalBase64','base64'); IF replace(encode(row_bytes,'base64'),E'\n','')<>transport->>'canonicalBase64' OR convert_from(row_bytes,'UTF8') IS NULL THEN RETURN NULL; END IF; EXCEPTION WHEN others THEN RETURN NULL; END; IF octet_length(row_bytes)<3 OR octet_length(row_bytes)>300000 OR get_byte(row_bytes,0)<>91 OR get_byte(row_bytes,octet_length(row_bytes)-1)<>93 OR encode(digest(row_bytes,'sha256'),'hex')<>transport->>'digest' THEN RETURN NULL; END IF; reconstructed:=reconstructed||CASE WHEN ordinal>1 THEN convert_to(',','UTF8') ELSE ''::bytea END||substring(row_bytes FROM 2 FOR octet_length(row_bytes)-2); END LOOP; reconstructed:=reconstructed||convert_to(']','UTF8'); IF reconstructed<>bytes THEN RETURN NULL; END IF;
FOR item IN SELECT value FROM jsonb_array_elements(p_rows) LOOP IF jsonb_typeof(item)<>'array' OR jsonb_array_length(item)<>7 OR item->>0<>'row' OR coalesce(octet_length(item->>1),0) NOT BETWEEN 1 AND 200 OR coalesce(octet_length(item->>2),0) NOT BETWEEN 1 AND 200 OR coalesce(octet_length(item->>3),0) NOT BETWEEN 1 AND 200 OR jsonb_typeof(item->4)<>'number' OR jsonb_typeof(item->5)<>'boolean' OR (item->>4)::bigint<>prior+1 OR octet_length(nearyou.decode_cutover_value(item->6)::text)>262144 THEN RETURN NULL; END IF; prior:=(item->>4)::bigint; END LOOP; IF prior<>p_to THEN RETURN NULL; END IF; prior:=p_from;
SELECT manifest INTO saved FROM nearyou.cutover_operation_manifests WHERE release_id=p_release AND kind='delta' AND operation_id=p_operation; IF FOUND THEN RETURN CASE WHEN saved=expected THEN saved ELSE NULL END; END IF;
PERFORM 1 FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND delta_freeze_token=p_freeze AND delta_cursor=p_from AND delta_final_high_water=p_final FOR UPDATE; IF NOT FOUND THEN RETURN NULL; END IF;
FOR item IN SELECT value FROM jsonb_array_elements(p_rows) LOOP prior:=(item->>4)::bigint; transport:=p_transports->(prior-p_from-1); IF (item->>5)::boolean THEN DELETE FROM nearyou.cutover_target_rows WHERE release_id=p_release AND household_id=item->>1 AND source_table=item->>2 AND source_id=item->>3; ELSE INSERT INTO nearyou.cutover_target_rows(release_id,household_id,source_table,source_id,payload,source_sequence,source_page_checksum,canonical_row_digest) VALUES(p_release,item->>1,item->>2,item->>3,nearyou.decode_cutover_value(item->6),prior,p_checksum,decode(transport->>'digest','hex')) ON CONFLICT(release_id,household_id,source_table,source_id) DO UPDATE SET payload=excluded.payload,source_sequence=excluded.source_sequence,source_page_checksum=excluded.source_page_checksum,canonical_row_digest=excluded.canonical_row_digest WHERE nearyou.cutover_target_rows.source_sequence<=excluded.source_sequence; END IF; END LOOP;
INSERT INTO nearyou.cutover_operation_manifests(kind,operation_id,release_id,fence,manifest) VALUES('delta',p_operation,p_release,p_fence,expected); UPDATE nearyou.cutover_runtime_state SET delta_cursor=p_to,updated_at=statement_timestamp() WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND delta_freeze_token=p_freeze AND delta_cursor=p_from; IF NOT FOUND THEN RAISE EXCEPTION 'delta fence lost'; END IF; RETURN expected; END $$;
ALTER FUNCTION nearyou.load_cutover_delta(text,text,bigint,text,bigint) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.apply_cutover_delta(text,text,bigint,text,bigint,bigint,bigint,text,jsonb,text,integer,text,text,jsonb) OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON FUNCTION nearyou.load_cutover_delta(text,text,bigint,text,bigint),nearyou.apply_cutover_delta(text,text,bigint,text,bigint,bigint,bigint,text,jsonb,text,integer,text,text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.load_cutover_delta(text,text,bigint,text,bigint),nearyou.apply_cutover_delta(text,text,bigint,text,bigint,bigint,bigint,text,jsonb,text,integer,text,text,jsonb) TO nearyou_cutover_runner;
CREATE TABLE nearyou.cutover_shadow_observations(release_id text PRIMARY KEY,operation_id text NOT NULL,fence bigint NOT NULL,freeze_token text NOT NULL,final_high_water bigint NOT NULL,state_checksum text NOT NULL,row_count bigint NOT NULL,source_checksum text NOT NULL,source_row_count bigint NOT NULL,started_at timestamptz NOT NULL DEFAULT statement_timestamp(),last_observed_at timestamptz NOT NULL DEFAULT statement_timestamp(),observation_count integer NOT NULL DEFAULT 1,status text NOT NULL DEFAULT 'observing',finalized_at timestamptz,evidence_digest text,final_result jsonb);
CREATE FUNCTION nearyou.begin_cutover_shadow(p_release text,p_owner text,p_fence bigint,p_freeze text,p_high_water bigint,p_operation text,p_source_checksum text,p_source_count bigint) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ DECLARE c text;n bigint; BEGIN SELECT checksum,row_count INTO c,n FROM nearyou.cutover_state_checksum(p_release); IF c IS NULL OR c<>p_source_checksum OR n<>p_source_count OR NOT EXISTS(SELECT 1 FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND lease_owner=p_owner AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND delta_freeze_token=p_freeze AND delta_cursor=delta_final_high_water AND delta_final_high_water=p_high_water) THEN RETURN NULL; END IF; INSERT INTO nearyou.cutover_shadow_observations(release_id,operation_id,fence,freeze_token,final_high_water,state_checksum,row_count,source_checksum,source_row_count) VALUES(p_release,p_operation,p_fence,p_freeze,p_high_water,c,n,p_source_checksum,p_source_count) ON CONFLICT DO NOTHING; RETURN (SELECT to_jsonb(o) FROM nearyou.cutover_shadow_observations o WHERE release_id=p_release AND operation_id=p_operation); END $$;
CREATE FUNCTION nearyou.observe_cutover_shadow(p_release text,p_owner text,p_fence bigint,p_operation text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ DECLARE current_checksum text;current_count bigint; BEGIN SELECT checksum,row_count INTO current_checksum,current_count FROM nearyou.cutover_state_checksum(p_release); UPDATE nearyou.cutover_shadow_observations o SET last_observed_at=statement_timestamp(),observation_count=o.observation_count+1 WHERE o.release_id=p_release AND o.operation_id=p_operation AND o.status='observing' AND statement_timestamp()-o.last_observed_at>=interval '20 seconds' AND current_checksum=o.state_checksum AND current_count=o.row_count AND EXISTS(SELECT 1 FROM nearyou.cutover_runtime_state s WHERE s.release_id=p_release AND s.lease_owner=p_owner AND s.lease_fence=p_fence AND s.lease_expires_at>statement_timestamp()); RETURN (SELECT to_jsonb(o) FROM nearyou.cutover_shadow_observations o WHERE o.release_id=p_release AND o.operation_id=p_operation); END $$;
CREATE FUNCTION nearyou.finalize_cutover_shadow(p_release text,p_owner text,p_fence bigint,p_freeze text,p_high_water bigint,p_operation text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ DECLARE o nearyou.cutover_shadow_observations%ROWTYPE;e nearyou.release_evidence_audit%ROWTYPE;current_checksum text;current_count bigint;result jsonb; BEGIN SELECT * INTO o FROM nearyou.cutover_shadow_observations x WHERE x.release_id=p_release AND x.operation_id=p_operation FOR UPDATE; IF o.status='complete' AND o.fence=p_fence AND o.freeze_token=p_freeze AND o.final_high_water=p_high_water THEN RETURN o.final_result; END IF; SELECT checksum,row_count INTO current_checksum,current_count FROM nearyou.cutover_state_checksum(p_release); IF o.release_id IS NULL OR o.observation_count<3 OR statement_timestamp()-o.started_at<interval '60 seconds' OR statement_timestamp()-o.started_at>interval '15 minutes' OR current_checksum<>o.state_checksum OR current_count<>o.row_count OR o.fence<>p_fence OR o.freeze_token<>p_freeze OR o.final_high_water<>p_high_water OR NOT EXISTS(SELECT 1 FROM nearyou.cutover_runtime_state s WHERE s.release_id=p_release AND s.lease_owner=p_owner AND s.lease_fence=p_fence AND s.lease_expires_at>statement_timestamp() AND s.delta_freeze_token=p_freeze) THEN RETURN NULL; END IF; SELECT * INTO e FROM nearyou.release_evidence_audit a WHERE a.release_id=p_release AND a.claims_projection->'shadow'->>'sourceChecksum'=o.source_checksum AND a.claims_projection->'shadow'->>'targetChecksum'=o.state_checksum AND (a.claims_projection->'shadow'->>'sampleCount')::bigint=o.observation_count AND (a.claims_projection->'shadow'->>'observedRows')::bigint=o.row_count AND abs((a.claims_projection->'shadow'->>'startedAt')::bigint-floor(extract(epoch FROM o.started_at)*1000)::bigint)<=5000 AND abs((a.claims_projection->'shadow'->>'endedAt')::bigint-floor(extract(epoch FROM statement_timestamp())*1000)::bigint)<=5000 ORDER BY a.consumed_at DESC LIMIT 1; IF NOT FOUND THEN RETURN NULL; END IF; result:=jsonb_build_object('sourceChecksum',o.source_checksum,'targetChecksum',o.state_checksum,'sampleCount',o.observation_count,'observedRows',o.row_count,'mismatchCount',0,'startedAt',floor(extract(epoch FROM o.started_at)*1000)::bigint,'endedAt',floor(extract(epoch FROM statement_timestamp())*1000)::bigint); UPDATE nearyou.cutover_shadow_observations x SET status='complete',finalized_at=statement_timestamp(),evidence_digest=e.claims_digest,final_result=result WHERE x.release_id=p_release; UPDATE nearyou.cutover_runtime_state s SET shadow_evidence_digest=e.claims_digest WHERE s.release_id=p_release; RETURN result; END $$;
ALTER FUNCTION nearyou.begin_cutover_shadow(text,text,bigint,text,bigint,text,text,bigint) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.observe_cutover_shadow(text,text,bigint,text) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.finalize_cutover_shadow(text,text,bigint,text,bigint,text) OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON nearyou.cutover_shadow_observations FROM PUBLIC,nearyou_cutover_runner; GRANT SELECT,INSERT,UPDATE ON nearyou.cutover_shadow_observations TO nearyou_cutover_policy_owner;
REVOKE ALL ON FUNCTION nearyou.begin_cutover_shadow(text,text,bigint,text,bigint,text,text,bigint),nearyou.observe_cutover_shadow(text,text,bigint,text),nearyou.finalize_cutover_shadow(text,text,bigint,text,bigint,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.begin_cutover_shadow(text,text,bigint,text,bigint,text,text,bigint),nearyou.observe_cutover_shadow(text,text,bigint,text),nearyou.finalize_cutover_shadow(text,text,bigint,text,bigint,text) TO nearyou_cutover_runner;
CREATE FUNCTION nearyou.load_cutover_evidence(p_release text,p_fence bigint,p_high_water bigint) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ SELECT jsonb_build_object('digest',a.claims_digest,'nonce',a.claims_projection->>'nonce','releaseId',a.release_id) FROM nearyou.cutover_runtime_state s JOIN nearyou.release_evidence_audit a ON a.claims_digest=s.shadow_evidence_digest WHERE s.release_id=p_release AND s.lease_fence=p_fence AND s.delta_cursor=p_high_water AND s.delta_final_high_water=p_high_water AND a.release_id=p_release $$;
CREATE FUNCTION nearyou.cutover_mode(p_release text) RETURNS text LANGUAGE sql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ SELECT routing_mode FROM nearyou.cutover_runtime_state WHERE release_id=p_release $$;
CREATE FUNCTION nearyou.load_cutover_transition(p_release text) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ SELECT manifest FROM nearyou.cutover_operation_manifests WHERE release_id=p_release AND kind='transition' AND operation_id=(SELECT transition_operation_id FROM nearyou.cutover_runtime_state WHERE release_id=p_release) $$;
CREATE FUNCTION nearyou.transition_cutover_exact(p_release text,p_operation text,p_fence bigint,p_freeze text,p_high_water bigint,p_digest text,p_nonce text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,nearyou_crypto,pg_temp AS $$
DECLARE claims jsonb; manifest jsonb;
BEGIN SELECT claims_projection INTO claims FROM nearyou.release_evidence_audit WHERE release_id=p_release AND claims_digest=p_digest AND nonce_hash=encode(nearyou_crypto.digest(p_nonce,'sha256'),'hex') FOR SHARE; IF NOT FOUND OR claims->>'releaseId'<>p_release OR (claims->>'highWater')::bigint<>p_high_water OR (claims->>'fence')::bigint<>p_fence OR NOT (claims->'gates' ?& array['rls','media','restore','load','accessibility','security']) OR claims->'shadow'->>'sourceChecksum'<>claims->'shadow'->>'targetChecksum' OR (claims->'shadow'->>'mismatchCount')::bigint<>0 THEN RETURN NULL; END IF;
 PERFORM 1 FROM nearyou.cutover_shadow_observations o WHERE o.release_id=p_release AND o.status='complete' AND o.fence=p_fence AND o.freeze_token=p_freeze AND o.final_high_water=p_high_water AND o.evidence_digest=p_digest AND o.final_result->>'sourceChecksum'=claims->'shadow'->>'sourceChecksum' AND o.final_result->>'targetChecksum'=claims->'shadow'->>'targetChecksum' AND (o.final_result->>'sampleCount')::bigint=(claims->'shadow'->>'sampleCount')::bigint AND (o.final_result->>'observedRows')::bigint=(claims->'shadow'->>'observedRows')::bigint AND (o.final_result->>'mismatchCount')::bigint=0 FOR SHARE; IF NOT FOUND THEN RETURN NULL; END IF;
 manifest:=jsonb_build_object('operationId',p_operation,'freezeToken',p_freeze,'highWater',p_high_water,'fence',p_fence,'evidenceDigest',p_digest);
 PERFORM 1 FROM nearyou.cutover_runtime_state WHERE release_id=p_release AND routing_mode='d1' AND lease_fence=p_fence AND lease_expires_at>statement_timestamp() AND delta_freeze_token=p_freeze AND delta_cursor=delta_final_high_water AND delta_final_high_water=p_high_water AND shadow_evidence_digest=p_digest FOR UPDATE; IF NOT FOUND THEN SELECT m.manifest INTO manifest FROM nearyou.cutover_operation_manifests m WHERE m.release_id=p_release AND m.kind='transition' AND m.operation_id=p_operation; RETURN manifest; END IF;
 INSERT INTO nearyou.release_evidence_transition_uses(claims_digest,release_id,operation_id) VALUES(p_digest,p_release,p_operation) ON CONFLICT DO NOTHING; IF NOT EXISTS(SELECT 1 FROM nearyou.release_evidence_transition_uses WHERE claims_digest=p_digest AND release_id=p_release AND operation_id=p_operation) THEN RETURN NULL; END IF; INSERT INTO nearyou.cutover_operation_manifests(kind,operation_id,release_id,fence,manifest) VALUES('transition',p_operation,p_release,p_fence,manifest); UPDATE nearyou.cutover_runtime_state SET routing_mode='postgres',transition_operation_id=p_operation,transition_freeze_token=p_freeze,transition_high_water=p_high_water,transition_evidence_digest=p_digest,updated_at=statement_timestamp() WHERE release_id=p_release AND lease_fence=p_fence AND delta_cursor=delta_final_high_water AND delta_final_high_water=p_high_water; RETURN manifest;
EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RETURN NULL; END $$;
ALTER FUNCTION nearyou.load_cutover_evidence(text,bigint,bigint) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.cutover_mode(text) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.load_cutover_transition(text) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.transition_cutover_exact(text,text,bigint,text,bigint,text,text) OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON FUNCTION nearyou.load_cutover_evidence(text,bigint,bigint),nearyou.cutover_mode(text),nearyou.load_cutover_transition(text),nearyou.transition_cutover_exact(text,text,bigint,text,bigint,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.load_cutover_evidence(text,bigint,bigint),nearyou.cutover_mode(text),nearyou.load_cutover_transition(text),nearyou.transition_cutover_exact(text,text,bigint,text,bigint,text,text) TO nearyou_cutover_runner;
ALTER FUNCTION nearyou.load_cutover_checkpoint(text,text,bigint) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.cutover_node_count(jsonb,integer) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.decode_cutover_value(jsonb,integer,integer) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.apply_cutover_page(text,text,bigint,bigint,bigint,bigint,text,jsonb,text,integer,text,jsonb) OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON FUNCTION nearyou.cutover_node_count(jsonb,integer),nearyou.decode_cutover_value(jsonb,integer,integer),nearyou.load_cutover_checkpoint(text,text,bigint),nearyou.apply_cutover_page(text,text,bigint,bigint,bigint,bigint,text,jsonb,text,integer,text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.load_cutover_checkpoint(text,text,bigint),nearyou.apply_cutover_page(text,text,bigint,bigint,bigint,bigint,text,jsonb,text,integer,text,jsonb) TO nearyou_cutover_runner;
GRANT EXECUTE ON FUNCTION nearyou.cutover_node_count(jsonb,integer),nearyou.decode_cutover_value(jsonb,integer,integer) TO nearyou_cutover_policy_owner;

CREATE TABLE nearyou.inventory_verified_claims(
 claims_digest text PRIMARY KEY CHECK(claims_digest~'^[a-f0-9]{64}$'), purpose text NOT NULL CHECK(purpose IN('d1-inventory-page','d1-inventory-complete')),
 operation_id text NOT NULL, registry_checksum text NOT NULL CHECK(registry_checksum~'^[a-f0-9]{64}$'), canonical_claims text NOT NULL CHECK(octet_length(canonical_claims)<=262144),claims jsonb NOT NULL,
 principal text NOT NULL,key_id text NOT NULL,key_version bigint NOT NULL,nonce_hash text NOT NULL UNIQUE CHECK(nonce_hash~'^[a-f0-9]{64}$'),expires_at timestamptz NOT NULL,verified_at timestamptz NOT NULL DEFAULT statement_timestamp()
);
CREATE TABLE nearyou.inventory_page_grants(
 operation_id text NOT NULL,pass smallint NOT NULL CHECK(pass IN(1,2)),table_index integer NOT NULL,page_ordinal bigint NOT NULL CHECK(page_ordinal>=0),table_name text NOT NULL,from_cursor text NOT NULL,to_cursor text NOT NULL,
 row_count integer NOT NULL CHECK(row_count BETWEEN 1 AND 500),event_from bigint,event_to bigint,page_checksum text NOT NULL CHECK(page_checksum~'^[a-f0-9]{64}$'),events_digest text NOT NULL CHECK(events_digest~'^[a-f0-9]{64}$'),
 claims_digest text NOT NULL UNIQUE REFERENCES nearyou.inventory_verified_claims(claims_digest),created_at timestamptz NOT NULL DEFAULT statement_timestamp(),PRIMARY KEY(operation_id,pass,table_index,page_ordinal),UNIQUE(operation_id,pass,table_index,from_cursor)
);
CREATE TABLE nearyou.inventory_completion_attestations(operation_id text PRIMARY KEY,registry_checksum text NOT NULL,inventory_checksum text NOT NULL,row_count bigint NOT NULL,page_count bigint NOT NULL,ordered_page_digest text NOT NULL,claims_digest text NOT NULL UNIQUE REFERENCES nearyou.inventory_verified_claims(claims_digest),created_at timestamptz NOT NULL DEFAULT statement_timestamp());
CREATE FUNCTION nearyou.record_inventory_verified_claim(p_digest text,p_purpose text,p_operation text,p_registry text,p_canonical text,p_principal text,p_key text,p_version bigint,p_nonce_hash text,p_expires_at timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,nearyou_crypto,pg_temp AS $$ DECLARE p_claims jsonb; BEGIN IF octet_length(p_canonical)>262144 OR encode(nearyou_crypto.digest(p_canonical,'sha256'),'hex')<>p_digest THEN RETURN false; END IF; BEGIN p_claims:=p_canonical::jsonb; EXCEPTION WHEN others THEN RETURN false; END; IF p_digest!~'^[a-f0-9]{64}$' OR p_registry!~'^[a-f0-9]{64}$' OR p_nonce_hash!~'^[a-f0-9]{64}$' OR p_purpose NOT IN('d1-inventory-page','d1-inventory-complete') OR p_expires_at<=statement_timestamp() OR p_expires_at>statement_timestamp()+interval '5 minutes' OR p_claims->>'purpose'<>p_purpose OR p_claims->>'operationId'<>p_operation OR p_claims->>'registryChecksum'<>p_registry THEN RETURN false; END IF; INSERT INTO nearyou.inventory_verified_claims VALUES(p_digest,p_purpose,p_operation,p_registry,p_canonical,p_claims,p_principal,p_key,p_version,p_nonce_hash,p_expires_at,statement_timestamp()) ON CONFLICT DO NOTHING; IF FOUND THEN RETURN true; END IF; RETURN EXISTS(SELECT 1 FROM nearyou.inventory_verified_claims WHERE claims_digest=p_digest AND purpose=p_purpose AND operation_id=p_operation AND registry_checksum=p_registry AND canonical_claims=p_canonical AND principal=p_principal AND key_id=p_key AND key_version=p_version AND nonce_hash=p_nonce_hash AND expires_at=p_expires_at); END $$;
CREATE FUNCTION nearyou.consume_inventory_page_grant(p_digest text,p_operation text,p_registry text,p_pass smallint,p_table_index integer,p_ordinal bigint,p_table text,p_from text,p_to text,p_count integer,p_event_from bigint,p_event_to bigint,p_checksum text,p_events_digest text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,pg_temp AS $$ DECLARE c jsonb; BEGIN SELECT claims INTO c FROM nearyou.inventory_verified_claims WHERE claims_digest=p_digest AND purpose='d1-inventory-page' AND operation_id=p_operation AND registry_checksum=p_registry AND expires_at>statement_timestamp() FOR SHARE; IF NOT FOUND OR c->>'pageChecksum'<>p_checksum OR c->>'eventsDigest'<>p_events_digest OR (c->>'pass')::smallint<>p_pass OR (c->>'tableIndex')::integer<>p_table_index OR (c->>'pageOrdinal')::bigint<>p_ordinal OR c->>'table'<>p_table OR c->>'fromCursor'<>p_from OR c->>'toCursor'<>p_to OR (c->>'rowCount')::integer<>p_count OR (c->>'eventFrom')::bigint IS DISTINCT FROM p_event_from OR (c->>'eventTo')::bigint IS DISTINCT FROM p_event_to THEN RETURN NULL; END IF; INSERT INTO nearyou.inventory_page_grants VALUES(p_operation,p_pass,p_table_index,p_ordinal,p_table,p_from,p_to,p_count,p_event_from,p_event_to,p_checksum,p_events_digest,p_digest,statement_timestamp()) ON CONFLICT DO NOTHING; IF EXISTS(SELECT 1 FROM nearyou.inventory_page_grants WHERE claims_digest=p_digest AND operation_id=p_operation AND page_checksum=p_checksum AND events_digest=p_events_digest) THEN RETURN p_digest; END IF; RETURN NULL; EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RETURN NULL; END $$;
CREATE FUNCTION nearyou.consume_inventory_completion(p_digest text,p_operation text,p_registry text,p_inventory text,p_count bigint,p_page_count bigint,p_ordered_digest text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=nearyou,nearyou_crypto,pg_temp AS $$ DECLARE c jsonb;actual text;pages bigint; BEGIN SELECT claims INTO c FROM nearyou.inventory_verified_claims WHERE claims_digest=p_digest AND purpose='d1-inventory-complete' AND operation_id=p_operation AND registry_checksum=p_registry AND expires_at>statement_timestamp() FOR SHARE; SELECT encode(nearyou_crypto.digest(coalesce(string_agg(claims_digest,'' ORDER BY pass,table_index,page_ordinal),''),'sha256'),'hex'),count(*) INTO actual,pages FROM nearyou.inventory_page_grants WHERE operation_id=p_operation; IF c IS NULL OR actual<>p_ordered_digest OR pages<>p_page_count OR c->>'inventoryChecksum'<>p_inventory OR (c->>'rowCount')::bigint<>p_count OR c->>'orderedPageDigest'<>p_ordered_digest THEN RETURN NULL; END IF; INSERT INTO nearyou.inventory_completion_attestations VALUES(p_operation,p_registry,p_inventory,p_count,p_page_count,p_ordered_digest,p_digest,statement_timestamp()) ON CONFLICT DO NOTHING; RETURN CASE WHEN EXISTS(SELECT 1 FROM nearyou.inventory_completion_attestations WHERE operation_id=p_operation AND claims_digest=p_digest) THEN p_digest END; END $$;
ALTER TABLE nearyou.inventory_verified_claims OWNER TO nearyou_cutover_policy_owner;
ALTER TABLE nearyou.inventory_page_grants OWNER TO nearyou_cutover_policy_owner;
ALTER TABLE nearyou.inventory_completion_attestations OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON nearyou.inventory_verified_claims,nearyou.inventory_page_grants,nearyou.inventory_completion_attestations FROM PUBLIC,nearyou_cutover_runner,nearyou_release_verifier;
GRANT SELECT,INSERT ON nearyou.inventory_verified_claims,nearyou.inventory_page_grants,nearyou.inventory_completion_attestations TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.record_inventory_verified_claim(text,text,text,text,text,text,text,bigint,text,timestamptz) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.consume_inventory_page_grant(text,text,text,smallint,integer,bigint,text,text,text,integer,bigint,bigint,text,text) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.consume_inventory_completion(text,text,text,text,bigint,bigint,text) OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON FUNCTION nearyou.record_inventory_verified_claim(text,text,text,text,text,text,text,bigint,text,timestamptz),nearyou.consume_inventory_page_grant(text,text,text,smallint,integer,bigint,text,text,text,integer,bigint,bigint,text,text),nearyou.consume_inventory_completion(text,text,text,text,bigint,bigint,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.record_inventory_verified_claim(text,text,text,text,text,text,text,bigint,text,timestamptz) TO nearyou_release_verifier; GRANT EXECUTE ON FUNCTION nearyou.consume_inventory_page_grant(text,text,text,smallint,integer,bigint,text,text,text,integer,bigint,bigint,text,text),nearyou.consume_inventory_completion(text,text,text,text,bigint,bigint,text) TO nearyou_cutover_runner;

ALTER FUNCTION nearyou.current_cutover_time() OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.acquire_cutover_lease(text,text) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.renew_cutover_lease(text,text,bigint) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.initialize_cutover_snapshot(text,text,bigint,bigint) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.record_cutover_operation(text,text,text,bigint,jsonb) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.transition_cutover(text,text,bigint,text,bigint,text) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.begin_rollback_capture(text,text,bigint,text,bigint,text) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.refence_rollback(text,text,bigint,bigint) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.record_rollback_manifest(text,text,bigint,text,jsonb) OWNER TO nearyou_cutover_policy_owner;
ALTER FUNCTION nearyou.transition_rollback(text,text,bigint,text,jsonb) OWNER TO nearyou_cutover_policy_owner;
REVOKE ALL ON FUNCTION nearyou.transition_cutover(text,text,bigint,text,bigint,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION nearyou.current_cutover_time(),nearyou.acquire_cutover_lease(text,text),nearyou.renew_cutover_lease(text,text,bigint),nearyou.initialize_cutover_snapshot(text,text,bigint,bigint),nearyou.record_cutover_operation(text,text,text,bigint,jsonb),nearyou.transition_cutover(text,text,bigint,text,bigint,text),nearyou.begin_rollback_capture(text,text,bigint,text,bigint,text),nearyou.refence_rollback(text,text,bigint,bigint),nearyou.record_rollback_manifest(text,text,bigint,text,jsonb),nearyou.transition_rollback(text,text,bigint,text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION nearyou.current_cutover_time(),nearyou.acquire_cutover_lease(text,text),nearyou.renew_cutover_lease(text,text,bigint),nearyou.initialize_cutover_snapshot(text,text,bigint,bigint),nearyou.record_cutover_operation(text,text,text,bigint,jsonb),nearyou.transition_cutover(text,text,bigint,text,bigint,text),nearyou.begin_rollback_capture(text,text,bigint,text,bigint,text),nearyou.refence_rollback(text,text,bigint,bigint),nearyou.record_rollback_manifest(text,text,bigint,text,jsonb),nearyou.transition_rollback(text,text,bigint,text,jsonb) TO nearyou_cutover_runner;
COMMIT;
