BEGIN;
CREATE TABLE nearyou.operational_worker_attempts(release_id text NOT NULL,release_version bigint NOT NULL,product text NOT NULL,job_id text NOT NULL CHECK(job_id~'^(?:[A-Za-z0-9_-]{8,200}|job:[a-f0-9]{64})$'),household_id text NOT NULL,attempt_token text NOT NULL,input_checksum text NOT NULL CHECK(input_checksum~'^[a-f0-9]{64}$'),evidence_checksum text NOT NULL CHECK(evidence_checksum~'^[a-f0-9]{64}$'),started_at timestamptz NOT NULL DEFAULT statement_timestamp(),terminal_status text CHECK(terminal_status IN('succeeded','failed','dead_letter')),terminal_at timestamptz,PRIMARY KEY(release_id,product,job_id,attempt_token));ALTER TABLE nearyou.operational_worker_attempts OWNER TO nearyou_policy_owner;REVOKE ALL ON nearyou.operational_worker_attempts FROM PUBLIC,nearyou_app;
CREATE TABLE nearyou.operational_job_outcomes(
 release_id text NOT NULL CHECK(release_id~'^rel_[A-Za-z0-9_-]{8,100}$'),release_version bigint NOT NULL CHECK(release_version>0),product text NOT NULL CHECK(product IN('nearstory','nearlegacy')),job_id text NOT NULL CHECK(job_id~'^(?:[A-Za-z0-9_-]{8,200}|job:[a-f0-9]{64})$'),household_id text NOT NULL CHECK(household_id~'^[A-Za-z0-9_-]{8,200}$'),attempt_token text NOT NULL CHECK(attempt_token~'^[A-Za-z0-9_-]{8,200}$'),evidence_checksum text NOT NULL CHECK(evidence_checksum~'^[a-f0-9]{64}$'),event_at timestamptz NOT NULL DEFAULT statement_timestamp(),status text NOT NULL CHECK(status IN('succeeded','failed','dead_letter')),PRIMARY KEY(release_id,product,job_id,attempt_token)
);ALTER TABLE nearyou.operational_job_outcomes OWNER TO nearyou_policy_owner;REVOKE ALL ON nearyou.operational_job_outcomes FROM PUBLIC,nearyou_app;
CREATE FUNCTION nearyou.record_operational_worker_attempt(p_release text,p_version bigint,p_product text,p_job text,p_household text,p_attempt text,p_checksum text,p_evidence text,p_operation text,p_status text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nearyou AS $$DECLARE v_changed bigint;BEGIN
 IF current_setting('nearyou.service_principal',true) IS NULL OR p_release!~'^rel_[A-Za-z0-9_-]{8,100}$' OR p_version<1 OR p_product NOT IN('nearstory','nearlegacy') OR p_job!~'^(?:[A-Za-z0-9_-]{8,200}|job:[a-f0-9]{64})$' OR p_household!~'^[A-Za-z0-9_-]{8,200}$' OR p_attempt!~'^[A-Za-z0-9_-]{8,200}$' OR p_status NOT IN('succeeded','failed','dead_letter') THEN RAISE EXCEPTION 'outcome invalid';END IF;
 IF p_checksum!~'^[a-f0-9]{64}$' OR p_evidence!~'^[a-f0-9]{64}$' OR p_operation NOT IN('attempt_started','terminal') THEN RAISE EXCEPTION 'outcome invalid';END IF;
 IF p_operation='attempt_started' THEN INSERT INTO nearyou.operational_worker_attempts VALUES(p_release,p_version,p_product,p_job,p_household,p_attempt,p_checksum,p_evidence,statement_timestamp(),NULL,NULL) ON CONFLICT(release_id,product,job_id,attempt_token) DO UPDATE SET input_checksum=EXCLUDED.input_checksum,evidence_checksum=EXCLUDED.evidence_checksum WHERE operational_worker_attempts.release_version=EXCLUDED.release_version AND operational_worker_attempts.household_id=EXCLUDED.household_id AND operational_worker_attempts.input_checksum=EXCLUDED.input_checksum AND operational_worker_attempts.evidence_checksum=EXCLUDED.evidence_checksum AND operational_worker_attempts.terminal_status IS NULL;RETURN FOUND;END IF;
 UPDATE nearyou.operational_worker_attempts SET terminal_status=p_status,terminal_at=statement_timestamp() WHERE release_id=p_release AND release_version=p_version AND product=p_product AND job_id=p_job AND household_id=p_household AND attempt_token=p_attempt AND input_checksum=p_checksum AND evidence_checksum=p_evidence AND terminal_status IS NULL;GET DIAGNOSTICS v_changed=ROW_COUNT;IF v_changed<>1 THEN RETURN false;END IF;INSERT INTO nearyou.operational_job_outcomes(release_id,release_version,product,job_id,household_id,attempt_token,evidence_checksum,status) VALUES(p_release,p_version,p_product,p_job,p_household,p_attempt,p_evidence,p_status);RETURN true;END$$;
ALTER FUNCTION nearyou.record_operational_worker_attempt(text,bigint,text,text,text,text,text,text,text,text) OWNER TO nearyou_policy_owner;REVOKE ALL ON FUNCTION nearyou.record_operational_worker_attempt(text,bigint,text,text,text,text,text,text,text,text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION nearyou.record_operational_worker_attempt(text,bigint,text,text,text,text,text,text,text,text) TO nearyou_release_verifier;
CREATE FUNCTION nearyou.load_operational_outcome_reconciliation(p_release text) RETURNS TABLE(terminal_count bigint,terminal_digest text) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,nearyou AS $$SELECT count(*),encode(digest(convert_to(COALESCE(string_agg(evidence_checksum,'' ORDER BY product,job_id,attempt_token),''),'UTF8'),'sha256'),'hex') FROM nearyou.operational_job_outcomes WHERE release_id=p_release$$;ALTER FUNCTION nearyou.load_operational_outcome_reconciliation(text) OWNER TO nearyou_policy_owner;REVOKE ALL ON FUNCTION nearyou.load_operational_outcome_reconciliation(text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION nearyou.load_operational_outcome_reconciliation(text) TO nearyou_release_verifier;
CREATE TABLE nearyou.canary_evidence_samples(release_id text NOT NULL CHECK(release_id~'^rel_[A-Za-z0-9_-]{8,100}$'),observed_at timestamptz NOT NULL,minute_bucket timestamptz NOT NULL,heartbeat_id text NOT NULL CHECK(length(heartbeat_id) BETWEEN 16 AND 200),dead_letters bigint NOT NULL CHECK(dead_letters>=0),completed_jobs bigint NOT NULL CHECK(completed_jobs>=0),failed_jobs bigint NOT NULL CHECK(failed_jobs>=0),sample_digest text NOT NULL CHECK(sample_digest~'^[a-f0-9]{64}$'),PRIMARY KEY(release_id,minute_bucket),UNIQUE(release_id,heartbeat_id),UNIQUE(release_id,sample_digest));
ALTER TABLE nearyou.canary_evidence_samples OWNER TO nearyou_policy_owner;REVOKE ALL ON nearyou.canary_evidence_samples FROM PUBLIC,nearyou_app,nearyou_release_verifier;
CREATE FUNCTION nearyou.record_canary_evidence_sample(p_release text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nearyou AS $$DECLARE v_now timestamptz:=statement_timestamp();v_bucket timestamptz:=date_trunc('minute',v_now);v_dead bigint;v_completed bigint;v_failed bigint;v_heartbeat text;v_digest text;BEGIN
 IF p_release!~'^rel_[A-Za-z0-9_-]{8,100}$' OR current_setting('nearyou.service_principal',true) IS NULL THEN RAISE EXCEPTION 'canary sample invalid';END IF;SELECT count(*) FILTER(WHERE status='dead_letter'),count(*) FILTER(WHERE status='succeeded'),count(*) FILTER(WHERE status='failed') INTO v_dead,v_completed,v_failed FROM nearyou.operational_job_outcomes WHERE release_id=p_release AND event_at>=v_now-interval '26 hours' AND event_at<=v_now;v_heartbeat:=p_release||':'||to_char(v_bucket,'YYYYMMDDHH24MI');v_digest:=encode(digest(convert_to(concat_ws('|',p_release,v_bucket,v_heartbeat,v_dead,v_completed,v_failed),'UTF8'),'sha256'),'hex');INSERT INTO nearyou.canary_evidence_samples(release_id,observed_at,minute_bucket,heartbeat_id,dead_letters,completed_jobs,failed_jobs,sample_digest) VALUES(p_release,v_now,v_bucket,v_heartbeat,v_dead,v_completed,v_failed,v_digest) ON CONFLICT(release_id,minute_bucket) DO NOTHING;RETURN FOUND;END$$;
ALTER FUNCTION nearyou.record_canary_evidence_sample(text) OWNER TO nearyou_policy_owner;REVOKE ALL ON FUNCTION nearyou.record_canary_evidence_sample(text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION nearyou.record_canary_evidence_sample(text) TO nearyou_release_verifier;
CREATE FUNCTION nearyou.load_canary_evidence_samples(p_release text) RETURNS TABLE(observed_at timestamptz,dead_letters bigint,completed_jobs bigint,failed_jobs bigint) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,nearyou AS $$SELECT s.observed_at,s.dead_letters,s.completed_jobs,s.failed_jobs FROM nearyou.canary_evidence_samples s WHERE s.release_id=p_release AND s.observed_at>=statement_timestamp()-interval '26 hours' ORDER BY s.minute_bucket$$;
ALTER FUNCTION nearyou.load_canary_evidence_samples(text) OWNER TO nearyou_policy_owner;REVOKE ALL ON FUNCTION nearyou.load_canary_evidence_samples(text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION nearyou.load_canary_evidence_samples(text) TO nearyou_release_verifier;
COMMIT;
