import { env } from "cloudflare:workers";
import { apiV1Failure, badRequest, requireHouseholdContext } from "@/lib/api-v1-context";
import { assertTrustedMutationOrigin, jsonNoStore, readJsonObject } from "@/lib/http";
import { legacyHash, legacyInternalId, legacyText, legacyUuid } from "@/lib/nearlegacy-route";
import { nearLegacyReady, requireLegacyEntitlement } from "../production";

export async function GET(request:Request){try{if(!await nearLegacyReady("read"))return jsonNoStore({error:"NearLegacy is not available."},{status:404});const{householdId}=await requireHouseholdContext(request,"archive:read");if(!await requireLegacyEntitlement(householdId,"read"))return jsonNoStore({error:"NearLegacy is required."},{status:403});const[m,p,l,t,c]=await Promise.all([env.DB.prepare("SELECT id,contributor_id,title,summary,source_segment_id,status FROM legacy_memories WHERE household_id=? AND status<>'deleted' ORDER BY updated_at DESC LIMIT 100").bind(householdId).all(),env.DB.prepare("SELECT id,display_name,relationship FROM legacy_people WHERE household_id=? ORDER BY updated_at DESC LIMIT 100").bind(householdId).all(),env.DB.prepare("SELECT id,name,description FROM legacy_places WHERE household_id=? ORDER BY updated_at DESC LIMIT 100").bind(householdId).all(),env.DB.prepare("SELECT id,name FROM legacy_tags WHERE household_id=? ORDER BY name LIMIT 100").bind(householdId).all(),env.DB.prepare("SELECT id,name,description FROM legacy_collections WHERE household_id=? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 100").bind(householdId).all()]);return jsonNoStore({memories:m.results||[],people:p.results||[],places:l.results||[],tags:t.results||[],collections:c.results||[]});}catch(error){return apiV1Failure(error,"Archive metadata could not be loaded.");}}

export async function POST(request:Request){try{assertTrustedMutationOrigin(request);if(!await nearLegacyReady())return jsonNoStore({error:"NearLegacy is not available."},{status:404});const{householdId,user}=await requireHouseholdContext(request,"archive:write");if(!await requireLegacyEntitlement(householdId))return jsonNoStore({error:"NearLegacy is required."},{status:403});let body:Record<string,unknown>;try{body=await readJsonObject(request,6000);}catch(error){return error instanceof Response?error:badRequest(error);}const kind=String(body.kind||"");if(!["memory","person","place","tag","timeline","collection"].includes(kind))return badRequest(new Error("Archive data kind is invalid."));const key=request.headers.get("idempotency-key")||"",id=await legacyInternalId(`archive-${kind}`,householdId,key),now=Date.now(),requestHash=await legacyHash(JSON.stringify(body)),prior=await env.DB.prepare("SELECT request_hash FROM legacy_audit_events WHERE id=? AND household_id=?").bind(`${id}:created`,householdId).all();if(prior.results?.length){if((prior.results[0]as Record<string,unknown>).request_hash!==requestHash)return jsonNoStore({error:"That idempotency key belongs to different archive data."},{status:409});return jsonNoStore({id,duplicate:true});}let insert;
if(kind==="person")insert=env.DB.prepare("INSERT INTO legacy_people (id,household_id,display_name,relationship,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(id,householdId,legacyText(body.name,"name",120),body.relationship?legacyText(body.relationship,"relationship",120):null,now,now);
else if(kind==="place")insert=env.DB.prepare("INSERT INTO legacy_places (id,household_id,name,description,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(id,householdId,legacyText(body.name,"name",160),body.description?legacyText(body.description,"description",1000):null,now,now);
else if(kind==="tag"){const name=legacyText(body.name,"name",80);insert=env.DB.prepare("INSERT INTO legacy_tags (id,household_id,name,normalized_name,created_at) VALUES (?,?,?,?,?)").bind(id,householdId,name,name.normalize("NFKC").toLocaleLowerCase("en-US"),now);}
else if(kind==="collection")insert=env.DB.prepare("INSERT INTO legacy_collections (id,household_id,created_by_user_id,name,description,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(id,householdId,user.userId,legacyText(body.name,"name",160),body.description?legacyText(body.description,"description",1000):null,now,now);
else if(kind==="memory")insert=env.DB.prepare("INSERT INTO legacy_memories (id,household_id,contributor_id,title,summary,source_segment_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?,'active',?,?)").bind(id,householdId,legacyUuid(body.contributorId,"contributorId"),legacyText(body.title,"title",200),body.summary?legacyText(body.summary,"summary",2000):null,legacyUuid(body.sourceSegmentId,"sourceSegmentId"),now,now);
else insert=env.DB.prepare("INSERT INTO legacy_timeline_events (id,household_id,memory_id,occurred_on,precision,title,created_at) VALUES (?,?,?,?,?,?,?)").bind(id,householdId,legacyUuid(body.memoryId,"memoryId"),body.occurredOn?legacyText(body.occurredOn,"occurredOn",40):null,["exact","month","year","unknown"].includes(String(body.precision))?body.precision:"unknown",legacyText(body.title,"title",200),now);
await env.DB.batch([insert,env.DB.prepare("INSERT INTO legacy_audit_events (id,household_id,actor_user_id,event_type,target_kind,target_id,request_hash,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(`${id}:created`,householdId,user.userId,`${kind}_created`,kind,id,requestHash,now)]);return jsonNoStore({id,kind},{status:201});}catch(error){return apiV1Failure(error,"Archive metadata could not be saved.");}}
