import { createHash } from "node:crypto";
import { constants, readFileSync } from "node:fs";
import { open, readFile, writeFile } from "node:fs/promises";
import type { KeyRecord } from "../lib/asymmetric-release-evidence";
import { EXACT_D1_PROVIDER_INTERNAL_OBJECTS, validateExactD1ProviderObjects } from "../lib/private-tester-baseline-gateway";
import {
  canonicalPrivateTesterDeploymentClaims,
  parsePrivateTesterDeploymentManifest,
  verifyPrivateTesterDeploymentManifest,
  type PrivateTesterDeploymentEnvelope,
  type PrivateTesterDeploymentNonce,
  type PrivateTesterDeploymentResource,
} from "../lib/private-tester-deployment-manifest";
import { parsePrivateTesterRelease, type PrivateTesterRelease } from "../lib/private-tester-release";
import { CloudKmsPublicKeyClient, PostgresPrivateTesterDeploymentManifestNonceStore } from "../lib/release-evidence-adapters";
import { LIVE_CATALOG_QUERY } from "./postgres-catalog";
import { verifyPrivateTesterD1LiveState } from "./private-tester-d1-live-state";
import { validatePrivateTesterBaselineCandidate } from "./promote-private-tester-baseline";
import { parseSitesManagedResourceReceiptV3 } from "../lib/sites-managed-resource-receipt";
import { SITES_D1_FORWARD_ARTIFACT } from "../lib/sites-d1-forward-artifact.generated";
import { completeEvidence, type EvidencePage } from "../lib/private-tester-sites-evidence";
import { createSitesBuildReceipt, readSitesArchiveBytesBuildIdentity } from "./read-sites-build-identity";

const HASH = /^[a-f0-9]{64}$/, ID = /^[A-Za-z][A-Za-z0-9_.:/@-]{2,511}$/, NAME = /^[a-z][a-z0-9_-]{2,127}$/;
const SECRET_VERSION = /^projects\/[a-z][a-z0-9-]{2,62}\/secrets\/[A-Za-z0-9_-]{1,255}\/versions\/[1-9][0-9]*$/;
const MAX_AGE_MS = 300_000, MAX_FUTURE_MS = 30_000;
const SITES_GATEWAY_ORIGIN = "https://nearyoustill.com";
const GOOGLE_ISSUER = "https://accounts.google.com";
const GOOGLE_CLIENT_ID = "619793096923-2hspnuckl0j99p3jrfb6qd21aatb0pep.apps.googleusercontent.com";
const GOOGLE_REDIRECT = `${SITES_GATEWAY_ORIGIN}/api/auth/callback/google`;
const MAX_READER_JSON_BYTES = 1_048_576;
const MAX_MANIFEST_BYTES = 32 * 1024;
const POSTGRES_READER_USER = "nearyou-pt-baseline@nearnight.iam";
const POSTGRES_READER_IDENTITY = `database:${POSTGRES_READER_USER}`;
const REVIEWED_SECRETS = Object.freeze(["nearyou-prod-app", "nearyou-prod-legacy", "nearyou-prod-pad", "nearyou-prod-migration-admin"]);
type RecordValue = Record<string, unknown>;
type LedgerEntry = { id: string; checksum: string };
type SitesDeploymentReceipt = { version: 1; provider: "openai-sites-control-plane"; projectId: string; deploymentId: string; versionId: string; commitSha: string; deployedAt: string };
type Meta = { provider: string; identity: string; observedAt: number; rayId?: string };
type Observed = { provider: string; identity: string; observedAt: number; rayId?: string; body: unknown };
type AppliedMigration = { sequence: number; name: string; appliedAt: string };
type SchemaObject = { type: string; name: string; tableName: string; rootPage: number; sql: string | null };
type ResourceIdentity = PrivateTesterDeploymentResource;
type DeploymentVerification = {
  trust: unknown;
  lookupKey(principal: string, keyId: string, version: number): Promise<KeyRecord>;
  nonceStore: { consumeDeploymentManifestNonce(input: PrivateTesterDeploymentNonce): Promise<boolean> };
};
type Readers = {
  d1: { readLedger(): Promise<unknown>; readSchema(): Promise<unknown>; readLedgerPage(cursor: string | null): Promise<unknown>; readSchemaPage(cursor: string | null): Promise<unknown> };
  runtime: { readHtml(): Promise<unknown> };
  postgres: { readMigrations(): Promise<unknown>; readCatalog(): Promise<unknown> };
  dns: { readIdentifiers(): Promise<unknown> }; oauth: { readIdentifiers(): Promise<unknown> };
  secretManager: { listVersions(): Promise<unknown> }; gates: { read(): Promise<unknown> };
};
export type PrivateTesterBaseline = {
  version: 1; reviewRequired: true; capturedAt: number; release: PrivateTesterRelease;
  sites: { projectId: string; current: { version: string; commitSha: string }; rollback: { version: string; commitSha: string }; resources: ResourceIdentity[]; deployment: SitesDeploymentReceipt; buildReceipt: RecordValue };
  d1: { appliedMigrations: AppliedMigration[]; appliedLedgerHash: string; reviewedSourceHash: string; schemaHash: string; schemaObjectCount: number; sourceSchemaDefinitionHash: string; sourceSchemaObjectCount: number; providerInternalSchemaHash: string; providerInternalSchemaObjectCount: number };
  postgres: { migrationsHash: string; catalogHash: string };
  dns: { records: { name: string; recordId: string; type: string }[] };
  oauth: { issuer: string; audience: string; clientId: string; providerAcceptedRedirectUri: string; proof: "interaction_required" };
  bindings: { bindings: ResourceIdentity[] };
  secretVersions: string[]; gates: { nearfamily: false; nearstory: false; scheduler: false };
  observations: Record<string, Meta>;
};
export type PrivateTesterBaselineInput = { release: unknown; deploymentManifest: unknown; deploymentVerification: DeploymentVerification; sitesDeploymentReceipt: unknown; expectedSitesDeploymentReceiptHash: unknown; sitesResourceReceiptRaw:string; expectedSitesResourceReceiptHash:string; sitesArchiveBytes: Uint8Array; sitesProviderLogRaw:string; expectedSitesProviderLogSha256:string; expectedD1Ledger: unknown; expectedD1SourceHash: unknown; expectedD1SchemaDefinitionHash: unknown; expectedD1SchemaObjectCount: unknown; outputPath: string; now(): number; readers: Readers };

function exactRecord(value: unknown, keys: readonly string[]): value is RecordValue {
  if (!value || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) return false;
  const own = Reflect.ownKeys(value); return own.length === keys.length && own.every((key) => { const d = Object.getOwnPropertyDescriptor(value, key); return typeof key === "string" && keys.includes(key) && !!d && d.enumerable && Object.hasOwn(d, "value") && !d.get && !d.set; });
}
function exactArray(value: unknown, max = 1_000): value is unknown[] {
  if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype || value.length < 1 || value.length > max) return false;
  const keys = Reflect.ownKeys(value); if (keys.length !== value.length + 1 || !keys.includes("length") || keys.some((key) => typeof key === "symbol")) return false;
  for (let index = 0; index < value.length; index += 1) { const d = Object.getOwnPropertyDescriptor(value, String(index)); if (!d || !d.enumerable || !Object.hasOwn(d, "value") || d.get || d.set) return false; }
  return true;
}
function canonical(value: unknown): string { return JSON.stringify(value); }
function hash(value: unknown): string { return createHash("sha256")["up\u0064ate"](canonical(value)).digest("hex"); }
function text(value: unknown, pattern = ID): value is string { return typeof value === "string" && pattern.test(value); }
function observation(value: unknown, nowMs: number): { meta: Meta; body: unknown } {
  const withRay=exactRecord(value,["provider","identity","observedAt","rayId","body"]),withoutRay=exactRecord(value,["provider","identity","observedAt","body"]),observedAt=withRay||withoutRay?value.observedAt:undefined;if((!withRay&&!withoutRay)||!text(value.provider,NAME)||!text(value.identity)||!Number.isSafeInteger(observedAt)||Number(observedAt)<nowMs-MAX_AGE_MS||Number(observedAt)>nowMs+MAX_FUTURE_MS||(withRay&&!text(value.rayId,/^[a-f0-9]{16}-[A-Z]{3}$/)))throw new Error("private tester baseline invalid");
  return { meta: { provider: value.provider, identity: value.identity, observedAt: Number(observedAt),...(withRay?{rayId:String(value.rayId)}:{}) }, body: value.body };
}
function sitesDeploymentReceipt(value: unknown, expectedHash: unknown, nowMs: number): SitesDeploymentReceipt { if(!exactRecord(value,["version","provider","projectId","deploymentId","versionId","commitSha","deployedAt"])||value.version!==1||value.provider!=="openai-sites-control-plane"||!text(value.projectId,/^appgprj_[a-f0-9]{32}$/)||!text(value.deploymentId,/^[A-Za-z0-9_-]{8,160}$/)||!text(value.versionId,/^appgprj_[a-f0-9]{32}~appgver_[A-Za-z0-9_-]{3,160}$/)||!text(value.commitSha,/^[a-f0-9]{40}$/)||typeof value.deployedAt!=="string"||typeof expectedHash!=="string"||!HASH.test(expectedHash)||hash(value)!==expectedHash)throw new Error("private tester baseline invalid");const deployedAt=Date.parse(value.deployedAt);if(!Number.isFinite(deployedAt)||deployedAt>nowMs+MAX_FUTURE_MS)throw new Error("private tester baseline invalid");return value as unknown as SitesDeploymentReceipt; }
function ledger(value: unknown): LedgerEntry[] {
  if (!exactArray(value)) throw new Error("private tester baseline invalid"); const seen = new Set<string>();
  return value.map((entry) => { if (!exactRecord(entry, ["id", "checksum"]) || !text(entry.id, /^[0-9]{4}_[a-z0-9_]{1,200}$/) || typeof entry.checksum !== "string" || !HASH.test(entry.checksum) || seen.has(entry.id)) throw new Error("private tester baseline invalid"); seen.add(entry.id); return { id: entry.id, checksum: entry.checksum }; });
}
function d1Applied(value: unknown, expected: LedgerEntry[]): AppliedMigration[] {
  if (!exactRecord(value, ["appliedMigrations"]) || !exactArray(value.appliedMigrations) || value.appliedMigrations.length !== expected.length) throw new Error("private tester baseline invalid");
  return value.appliedMigrations.map((entry, index) => {
    if (!exactRecord(entry, ["sequence", "name", "appliedAt"]) || entry.sequence !== index + 1 || entry.name !== `${expected[index]?.id}.sql` || typeof entry.appliedAt !== "string" || !/^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]{1,6})?$/.test(entry.appliedAt)) throw new Error("private tester baseline invalid");
    return { sequence: entry.sequence, name: entry.name, appliedAt: entry.appliedAt };
  });
}
function d1Schema(value: unknown, expectedDefinitionHash: string, expectedObjectCount: number): { objects: SchemaObject[]; sourceObjects: SchemaObject[]; providerInternalObjects: SchemaObject[]; definitionHash: string } {
  if (!exactRecord(value, ["schema", "objects"]) || value.schema !== "sqlite_schema" || !exactArray(value.objects,2_000)) throw new Error("private tester baseline invalid");
  let previous = "";
  const objects = value.objects.map((item) => {
    if (!exactRecord(item, ["type", "name", "tableName", "rootPage", "sql"]) || !text(item.type, /^(?:table|index|trigger|view)$/) || !text(item.name, /^[A-Za-z_][A-Za-z0-9_]{0,127}$/) || !text(item.tableName, /^[A-Za-z_][A-Za-z0-9_]{0,127}$/) || !Number.isSafeInteger(item.rootPage) || Number(item.rootPage) < 0 || (item.sql !== null && (typeof item.sql !== "string" || item.sql.length < 1 || item.sql.length > 1_048_576))) throw new Error("private tester baseline invalid");
    const key = `${item.type}\u0000${item.name}\u0000${item.tableName}`;
    if (key <= previous) throw new Error("private tester baseline invalid");
    previous = key;
    return { type: item.type, name: item.name, tableName: item.tableName, rootPage: Number(item.rootPage), sql: item.sql };
  });
  const liveCheckpoint=SITES_D1_FORWARD_ARTIFACT.schemaCheckpoints.find(({head})=>head==="0026"),liveReviewed=liveCheckpoint?.definitionsSha256===expectedDefinitionHash&&liveCheckpoint.objectCount===expectedObjectCount;
  const providerDefinitions=liveReviewed?liveCheckpoint.providerObjects:EXACT_D1_PROVIDER_INTERNAL_OBJECTS;
  const providerIdentities = new Set(providerDefinitions.map(({ type, name, tableName }) => `${type}\u0000${name}\u0000${tableName}`));
  const sourceObjects = objects.filter(({ type, name, tableName }) => !providerIdentities.has(`${type}\u0000${name}\u0000${tableName}`));
  const providerInternalObjects = objects.filter(({ type, name, tableName }) => providerIdentities.has(`${type}\u0000${name}\u0000${tableName}`));
  if(liveReviewed){if(providerInternalObjects.length>providerDefinitions.length)throw new Error("private tester baseline invalid")}else try{validateExactD1ProviderObjects(objects)}catch{throw new Error("private tester baseline invalid")}
  if (sourceObjects.length !== expectedObjectCount) throw new Error("private tester baseline invalid");
  const definitionHash = hash(sourceObjects.map(({ type, name, tableName, sql }) => ({ type, name, tableName, sql })));
  if (definitionHash !== expectedDefinitionHash) throw new Error("private tester baseline invalid");
  return { objects, sourceObjects, providerInternalObjects, definitionHash };
}
function pgCatalog(value: unknown): { schema: string; relations: { name: string; kind: string; checksum: string }[] } {
  if (!exactRecord(value, ["schema", "relations"]) || value.schema !== "nearyou" || !exactArray(value.relations)) throw new Error("private tester baseline invalid");
  const seen = new Set<string>(); const relations = value.relations.map((relation) => { if (!exactRecord(relation, ["name", "kind", "checksum"]) || !text(relation.name, /^[A-Za-z0-9_.:() ,=-]{1,511}$/) || !text(relation.kind, /^[a-z_]{1,40}$/) || typeof relation.checksum !== "string" || !HASH.test(relation.checksum) || seen.has(`${relation.kind}:${relation.name}`)) throw new Error("private tester baseline invalid"); seen.add(`${relation.kind}:${relation.name}`); return { name: relation.name, kind: relation.kind, checksum: relation.checksum }; });
  return { schema: "nearyou", relations };
}
function dns(value: unknown): { records: { name: string; recordId: string; type: string }[] } {
  if (!exactRecord(value, ["records"]) || !exactArray(value.records)) throw new Error("private tester baseline invalid"); const seen = new Set<string>(); const records = value.records.map((record) => { if (!exactRecord(record, ["name", "recordId", "type"]) || !text(record.name, /^(?:[a-z0-9-]+\.)+[a-z]{2,63}$/) || !text(record.recordId) || !text(record.type, /^(?:A|AAAA|CNAME|MX|NS|SOA|TXT)$/) || seen.has(record.recordId)) throw new Error("private tester baseline invalid"); seen.add(record.recordId); return { name: record.name, recordId: record.recordId, type: record.type }; }); return { records };
}
function oauth(value: unknown): { issuer: string; audience: string; clientId: string; providerAcceptedRedirectUri: string; proof: "interaction_required" } { if (!exactRecord(value, ["issuer", "audience", "clientId", "providerAcceptedRedirectUri", "proof"]) || value.issuer !== GOOGLE_ISSUER || value.audience !== GOOGLE_CLIENT_ID || value.clientId !== GOOGLE_CLIENT_ID || value.audience !== value.clientId || value.providerAcceptedRedirectUri !== GOOGLE_REDIRECT || value.proof !== "interaction_required") throw new Error("private tester baseline invalid"); return { issuer: GOOGLE_ISSUER, audience: GOOGLE_CLIENT_ID, clientId: GOOGLE_CLIENT_ID, providerAcceptedRedirectUri: GOOGLE_REDIRECT, proof: "interaction_required" }; }
function versions(value: unknown): string[] { if (!exactRecord(value, ["versions"]) || !exactArray(value.versions)) throw new Error("private tester baseline invalid"); const result = value.versions.map((name) => { if (typeof name !== "string" || !SECRET_VERSION.test(name)) throw new Error("private tester baseline invalid"); return name; }).sort(); if (new Set(result).size !== result.length) throw new Error("private tester baseline invalid"); return result; }
function gates(value: unknown): { nearfamily: false; nearstory: false; scheduler: false } { if (!exactRecord(value, ["nearfamily", "nearstory", "scheduler"]) || value.nearfamily !== false || value.nearstory !== false || value.scheduler !== false) throw new Error("private tester baseline invalid"); return { nearfamily: false, nearstory: false, scheduler: false }; }
function deploymentVerification(value: unknown): DeploymentVerification { if (!exactRecord(value, ["trust", "lookupKey", "nonceStore"]) || typeof value.lookupKey !== "function" || !exactRecord(value.nonceStore, ["consumeDeploymentManifestNonce"]) || typeof value.nonceStore.consumeDeploymentManifestNonce !== "function") throw new Error("private tester baseline invalid"); return value as unknown as DeploymentVerification; }
function readers(value: unknown): Readers { if (!exactRecord(value, ["d1", "runtime", "postgres", "dns", "oauth", "secretManager", "gates"])) throw new Error("private tester baseline invalid"); const methods = (item: unknown, keys: string[]) => exactRecord(item, keys) && keys.every((key) => typeof item[key] === "function"); if (!methods(value.d1, ["readLedger", "readSchema", "readLedgerPage", "readSchemaPage"]) || !methods(value.runtime, ["readHtml"]) || !methods(value.postgres, ["readMigrations", "readCatalog"]) || !methods(value.dns, ["readIdentifiers"]) || !methods(value.oauth, ["readIdentifiers"]) || !methods(value.secretManager, ["listVersions"]) || !methods(value.gates, ["read"])) throw new Error("private tester baseline invalid"); return value as unknown as Readers; }
function bytesHash(value: Uint8Array): string { return createHash("sha256").update(value).digest("hex"); }
function runtimeHtml(value: unknown, nowMs: number): { meta: Meta; html: string } { const observed = observation(value, nowMs); if (observed.meta.provider !== "sites-runtime" || !exactRecord(observed.body, ["html"]) || typeof observed.body.html !== "string" || new TextEncoder().encode(observed.body.html).byteLength < 1 || new TextEncoder().encode(observed.body.html).byteLength > MAX_READER_JSON_BYTES) throw new Error("private tester baseline invalid"); return { meta: observed.meta, html: observed.body.html }; }
async function pages(kind: "d1-schema" | "d1-ledger", read: (cursor: string | null) => Promise<unknown>) { const collected: EvidencePage[] = []; let cursor: string | null = null; for (let count = 0; count < 50_000; count += 1) { const page = await read(cursor); collected.push(page as EvidencePage); if ((page as RecordValue).nextCursor === null) return completeEvidence(kind, collected); if (typeof (page as RecordValue).nextCursor !== "string") throw new Error("private tester baseline invalid"); cursor = (page as RecordValue).nextCursor as string; } throw new Error("private tester baseline invalid"); }
function providerLog(value: unknown, expectedHash: unknown, nowMs: number) { if (typeof value !== "string" || typeof expectedHash !== "string" || !HASH.test(expectedHash) || bytesHash(new TextEncoder().encode(value)) !== expectedHash) throw new Error("private tester baseline invalid"); let parsed: unknown; try { parsed = JSON.parse(value); } catch { throw new Error("private tester baseline invalid"); } if (!exactRecord(parsed, ["version", "provider", "scriptName", "scriptVersionId", "observedAt", "rays"]) || parsed.version !== 1 || parsed.provider !== "sites-worker-logs" || !text(parsed.scriptName, /^site---[a-f0-9]{32}$/) || !text(parsed.scriptVersionId, /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/) || !Number.isSafeInteger(parsed.observedAt) || Number(parsed.observedAt) > nowMs || Number(parsed.observedAt) < nowMs - MAX_AGE_MS || !exactArray(parsed.rays, 32) || new Set(parsed.rays).size !== parsed.rays.length || parsed.rays.some((ray) => !text(ray, /^[a-f0-9]{16}-[A-Z]{3}$/))) throw new Error("private tester baseline invalid"); return parsed; }

export async function capturePrivateTesterBaseline(input: PrivateTesterBaselineInput): Promise<PrivateTesterBaseline> {
  if (!exactRecord(input, ["release", "deploymentManifest", "deploymentVerification", "sitesDeploymentReceipt", "expectedSitesDeploymentReceiptHash", "sitesResourceReceiptRaw", "expectedSitesResourceReceiptHash", "sitesArchiveBytes", "sitesProviderLogRaw", "expectedSitesProviderLogSha256", "expectedD1Ledger", "expectedD1SourceHash", "expectedD1SchemaDefinitionHash", "expectedD1SchemaObjectCount", "outputPath", "now", "readers"]) || !(input.sitesArchiveBytes instanceof Uint8Array) || input.sitesArchiveBytes.byteLength < 1 || input.sitesArchiveBytes.byteLength > 1_073_741_824 || typeof input.outputPath !== "string" || input.outputPath.length < 1 || input.outputPath.length > 4_096 || typeof input.now !== "function" || typeof input.expectedD1SourceHash !== "string" || !HASH.test(input.expectedD1SourceHash) || typeof input.expectedD1SchemaDefinitionHash !== "string" || !HASH.test(input.expectedD1SchemaDefinitionHash) || !Number.isSafeInteger(input.expectedD1SchemaObjectCount) || Number(input.expectedD1SchemaObjectCount) < 1 || Number(input.expectedD1SchemaObjectCount) > 1_000) throw new Error("private tester baseline invalid");
  const startedAt = input.now();
  if (!Number.isSafeInteger(startedAt)) throw new Error("private tester baseline invalid");
  const release = parsePrivateTesterRelease(input.release, startedAt), expected = ledger(input.expectedD1Ledger), read = readers(input.readers), verification = deploymentVerification(input.deploymentVerification), deployment=sitesDeploymentReceipt(input.sitesDeploymentReceipt,input.expectedSitesDeploymentReceiptHash,startedAt);
  const manifest = await verifyPrivateTesterDeploymentManifest(input.deploymentManifest, { now: startedAt, trust: verification.trust, lookupKey: verification.lookupKey, nonceStore: verification.nonceStore });
  const signedManifest = canonicalPrivateTesterDeploymentClaims(manifest);
  const beforeRuntime = runtimeHtml(await read.runtime.readHtml(), startedAt);
  const raw = await Promise.all([read.d1.readLedger(), read.d1.readSchema(), read.postgres.readMigrations(), read.postgres.readCatalog(), read.dns.readIdentifiers(), read.oauth.readIdentifiers(), read.secretManager.listVersions(), read.gates.read(), pages("d1-schema", read.d1.readSchemaPage), pages("d1-ledger", read.d1.readLedgerPage)]);
  const afterRuntime = runtimeHtml(await read.runtime.readHtml(), input.now());
  const capturedAt = input.now();
  if (!Number.isSafeInteger(capturedAt) || capturedAt < startedAt) throw new Error("private tester baseline invalid");
  const finalRelease = parsePrivateTesterRelease(input.release, capturedAt);
  if (canonical(finalRelease) !== canonical(release)) throw new Error("private tester baseline invalid");
  const finalManifest = parsePrivateTesterDeploymentManifest(manifest, capturedAt);
  if (canonicalPrivateTesterDeploymentClaims(finalManifest) !== signedManifest || canonicalPrivateTesterDeploymentClaims(manifest) !== signedManifest) throw new Error("private tester baseline invalid");
  const logs = providerLog(input.sitesProviderLogRaw, input.expectedSitesProviderLogSha256, capturedAt);
  const schemaCompletion = raw[8] as ReturnType<typeof completeEvidence>, ledgerCompletion = raw[9] as ReturnType<typeof completeEvidence>;
  if (schemaCompletion.buildId !== ledgerCompletion.buildId) throw new Error("private tester baseline invalid");
  let archiveIdentity: Awaited<ReturnType<typeof readSitesArchiveBytesBuildIdentity>>; try { archiveIdentity = await readSitesArchiveBytesBuildIdentity({ archiveBytes: input.sitesArchiveBytes, commitSha: deployment.commitSha, expectedArchiveSha256: bytesHash(input.sitesArchiveBytes) }); } catch { throw new Error("private tester baseline invalid"); }
  if (archiveIdentity.buildId !== schemaCompletion.buildId) throw new Error("private tester baseline invalid");
  const buildReceipt = createSitesBuildReceipt({ projectId: deployment.projectId, versionId: deployment.versionId, deploymentId: deployment.deploymentId, commitSha: deployment.commitSha, archiveSha256: archiveIdentity.archiveSha256, buildId: archiveIdentity.buildId, beforeHtml: beforeRuntime.html, afterHtml: afterRuntime.html, providerScriptName: logs.scriptName as string, providerScriptVersion: logs.scriptVersionId as string, observedAt: capturedAt });
  let resourceEvidence: ReturnType<typeof parseSitesManagedResourceReceiptV3>; try { resourceEvidence=parseSitesManagedResourceReceiptV3(input.sitesResourceReceiptRaw,input.expectedSitesResourceReceiptHash,capturedAt,{buildReceipt,schemaCompletion,ledgerCompletion}); } catch { throw new Error("private tester baseline invalid"); }
  const resourceReceipt=resourceEvidence.receipt as RecordValue,resourceVersion=resourceReceipt.version as RecordValue,resourceDeployment=resourceReceipt.deployment as RecordValue;
  if (manifest.schemaVersion!==3||manifest.releaseId !== release.releaseId || manifest.live.version !== release.sitesVersion || manifest.live.commitSha !== release.commitSha || deployment.projectId!==manifest.projectId || deployment.versionId!==manifest.live.version || deployment.commitSha!==manifest.live.commitSha || Math.abs(Date.parse(deployment.deployedAt)-manifest.issuedAt)>MAX_AGE_MS||resourceVersion.project_id!==manifest.projectId||resourceVersion.id!==manifest.live.version||(resourceVersion.source as RecordValue).commit_sha!==manifest.live.commitSha||resourceDeployment.id!==deployment.deploymentId||canonical(resourceEvidence.resources)!==canonical(manifest.resources)||beforeRuntime.meta.identity!==afterRuntime.meta.identity||beforeRuntime.meta.rayId===afterRuntime.meta.rayId) throw new Error("private tester baseline invalid");
  const d1LedgerRaw = observation(raw[0], capturedAt), d1SchemaRaw = observation(raw[1], capturedAt), pgMigrationsRaw = observation(raw[2], capturedAt), pgCatalogRaw = observation(raw[3], capturedAt), dnsRaw = observation(raw[4], capturedAt), oauthRaw = observation(raw[5], capturedAt), versionsRaw = observation(raw[6], capturedAt), gatesRaw = observation(raw[7], capturedAt),providerMeta={provider:"openai-sites-control-plane",identity:`project:${manifest.projectId}`,observedAt:Number(resourceReceipt.captured_at)};
  if (d1LedgerRaw.meta.provider !== "sites-runtime" || d1SchemaRaw.meta.provider !== "sites-runtime" || oauthRaw.meta.provider !== "sites-runtime" || gatesRaw.meta.provider !== "sites-runtime" || pgMigrationsRaw.meta.provider !== "cloud-sql" || pgCatalogRaw.meta.provider !== "cloud-sql" || pgMigrationsRaw.meta.identity !== POSTGRES_READER_IDENTITY || pgCatalogRaw.meta.identity !== POSTGRES_READER_IDENTITY) throw new Error("private tester baseline invalid");
  const runtimeRays=[d1LedgerRaw.meta.rayId,d1SchemaRaw.meta.rayId,gatesRaw.meta.rayId,oauthRaw.meta.rayId];if(runtimeRays.some(value=>typeof value!=="string")||new Set(runtimeRays).size!==4||d1SchemaRaw.meta.identity !== d1LedgerRaw.meta.identity || oauthRaw.meta.identity !== d1LedgerRaw.meta.identity || gatesRaw.meta.identity !== d1LedgerRaw.meta.identity) throw new Error("private tester baseline invalid");
  if (beforeRuntime.meta.identity!==d1LedgerRaw.meta.identity || afterRuntime.meta.identity!==d1LedgerRaw.meta.identity || ![beforeRuntime.meta.rayId,afterRuntime.meta.rayId,...runtimeRays].every((ray)=>typeof ray==="string"&&Array.isArray(logs.rays)&&logs.rays.includes(ray))) throw new Error("private tester baseline invalid");
  const applied = d1Applied(d1LedgerRaw.body, expected), schemaBody = d1Schema(d1SchemaRaw.body, input.expectedD1SchemaDefinitionHash, Number(input.expectedD1SchemaObjectCount)), migrations = ledger(exactRecord(pgMigrationsRaw.body, ["ledger"]) ? pgMigrationsRaw.body.ledger : undefined), catalog = pgCatalog(pgCatalogRaw.body), resources = manifest.resources, dnsBody = dns(dnsRaw.body), oauthBody = oauth(oauthRaw.body), secretVersions = versions(versionsRaw.body), gateBody = gates(gatesRaw.body);
  const observations = { d1Ledger: d1LedgerRaw.meta, d1Schema: d1SchemaRaw.meta, postgresMigrations: pgMigrationsRaw.meta, postgresCatalog: pgCatalogRaw.meta, sitesResourceReceipt:providerMeta, dns: dnsRaw.meta, oauth: oauthRaw.meta, secretManager: versionsRaw.meta, gates: gatesRaw.meta };
  const baseline: PrivateTesterBaseline = { version: 1, reviewRequired:true, capturedAt, release, sites: { projectId: manifest.projectId, current: manifest.live, rollback: manifest.rollback, resources, deployment, buildReceipt }, d1: { appliedMigrations: applied, appliedLedgerHash: hash(applied), reviewedSourceHash: input.expectedD1SourceHash, schemaHash: hash(schemaBody.objects), schemaObjectCount: schemaBody.objects.length, sourceSchemaDefinitionHash: schemaBody.definitionHash, sourceSchemaObjectCount: schemaBody.sourceObjects.length, providerInternalSchemaHash: hash(schemaBody.providerInternalObjects), providerInternalSchemaObjectCount: schemaBody.providerInternalObjects.length }, postgres: { migrationsHash: hash(migrations), catalogHash: hash(catalog) }, dns: dnsBody, oauth: oauthBody, bindings: { bindings: resources }, secretVersions, gates: gateBody, observations };
  validatePrivateTesterBaselineCandidate(baseline,capturedAt);
  await writeFile(input.outputPath, `${canonical(baseline)}\n`, { flag: "wx" }); return baseline;
}

function envId(environment: NodeJS.ProcessEnv, name: string, pattern = ID): string { const value = environment[name]; if (!value || !pattern.test(value)) throw new Error("private tester baseline configuration missing"); return value; }
async function metadata(path: string, fetcher: typeof fetch): Promise<string> { const response = await fetcher(`http://metadata.google.internal${path}`, { headers: { "metadata-flavor": "Google" }, signal: AbortSignal.timeout(5_000) }); const value = await response.text(); if (!response.ok || value.length < 3 || value.length > 16_384) throw new Error("private tester baseline identity unavailable"); return value; }
async function token(fetcher: typeof fetch): Promise<string> { const value = JSON.parse(await metadata("/computeMetadata/v1/instance/service-accounts/default/token", fetcher)) as { access_token?: unknown; expires_in?: unknown }, expiresIn = value.expires_in; if (typeof value.access_token !== "string" || value.access_token.length < 20 || !Number.isSafeInteger(expiresIn) || Number(expiresIn) < 60 || Number(expiresIn) > 3_600) throw new Error("private tester baseline identity unavailable"); return value.access_token; }
async function gatewayToken(fetcher: typeof fetch): Promise<string> { const value = await metadata(`/computeMetadata/v1/instance/service-accounts/default/identity?audience=${encodeURIComponent(SITES_GATEWAY_ORIGIN)}&format=standard`, fetcher); if (value.split(".").length !== 3) throw new Error("private tester baseline identity unavailable"); return value; }
async function json(url: string, bearer: string, fetcher: typeof fetch): Promise<RecordValue> { const response = await fetcher(url, { headers: { authorization: `Bearer ${bearer}`, accept: "application/json" }, redirect: "error", signal: AbortSignal.timeout(10_000) }); const raw = await response.text(); if (!response.ok || new TextEncoder().encode(raw).byteLength > MAX_READER_JSON_BYTES) throw new Error("private tester baseline reader unavailable"); try { const value = JSON.parse(raw); if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(); return value as RecordValue; } catch { throw new Error("private tester baseline reader unavailable"); } }
function stamp(provider: string, identity: string, body: unknown, now: () => number): Observed { return { provider, identity, observedAt: now(), body }; }
function sitesGateway(subject: string, expectedRelease: PrivateTesterRelease, fetcher: typeof fetch, now: () => number) { const principal=`service:${subject}`,endpoint=new URL(SITES_GATEWAY_ORIGIN);return async(kind:string,cursor:string|null=null):Promise<Observed>=>{const path=new URL(`/api/internal/private-tester-baseline/${encodeURIComponent(kind)}`,endpoint);if(cursor!==null)path.searchParams.set("cursor",cursor);const response=await fetcher(path,{headers:{authorization:`Bearer ${await gatewayToken(fetcher)}`,accept:"application/json"},redirect:"error",signal:AbortSignal.timeout(10_000)}),rayId=response.headers.get("cf-ray")??"",raw=await response.text(),completedAt=now();let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error("private tester baseline reader unavailable")}if(!response.ok||!text(rayId,/^[a-f0-9]{16}-[A-Z]{3}$/)||!exactRecord(value,["issuer","audience","subject","principal","observedAt","release","body"])||value.issuer!==GOOGLE_ISSUER||value.audience!==SITES_GATEWAY_ORIGIN||value.subject!==subject||value.principal!==principal||canonical(value.release)!==canonical(expectedRelease)||!Number.isSafeInteger(completedAt)||!Number.isSafeInteger(value.observedAt)||Number(value.observedAt)<completedAt-MAX_AGE_MS||Number(value.observedAt)>completedAt+MAX_FUTURE_MS)throw new Error("private tester baseline reader unavailable");return{provider:"sites-runtime",identity:principal,observedAt:Number(value.observedAt),rayId,body:value.body}};}
function postgresConnection(environment: NodeJS.ProcessEnv): string { const raw = environment.PRIVATE_TESTER_BASELINE_DATABASE_URL ?? "", marker = environment.CLOUD_SQL_IAM_CONNECTOR ?? "", instance = environment.CLOUD_SQL_INSTANCE_CONNECTION_NAME ?? "", expected = environment.CLOUD_SQL_PROXY_ARGS_CHECKSUM ?? "", template = readFileSync(new URL("../infra/production/cloud-sql-auth-proxy.args", import.meta.url), "utf8"), artifact = template.replace("${CLOUD_SQL_INSTANCE_CONNECTION_NAME}", instance), checksum = createHash("sha256")["up\u0064ate"](artifact).digest("hex"); let url: URL; try { url = new URL(raw); } catch { throw new Error("private tester baseline configuration missing"); } if (marker !== "cloud-sql-auth-proxy" || instance !== "nearnight:us-central1:nearyou-production" || expected !== checksum || !artifact.includes("--auto-iam-authn") || !artifact.endsWith(`${instance}\n`) || !["postgres:", "postgresql:"].includes(url.protocol) || url.password || url.hostname !== "127.0.0.1" || url.port !== "5432" || url.searchParams.get("sslmode") !== "disable") throw new Error("private tester baseline configuration missing"); return raw; }
function postgresReaders(environment: NodeJS.ProcessEnv) { const connectionString = postgresConnection(environment), expectedUser = envId(environment, "NEARYOU_PRIVATE_TESTER_BASELINE_DATABASE_USER", /^nearyou-pt-baseline@nearnight\.iam$/); const query = async <T extends RecordValue>(sql: string) => { const name = "pg", { Pool } = await import(name) as typeof import("pg"), pool = new Pool({ connectionString, ssl: { rejectUnauthorized: false } }); try { const statement = sql.trim().replace(/;$/, ""), rows = (await pool.query<T>(statement)).rows, completion = (await pool.query<{ observed_at: string; session_identity: string; current_identity: string; database_name: string; principal: string; effective: boolean }>("SELECT floor(extract(epoch from clock_timestamp())*1000)::bigint::text AS observed_at,session_user::text AS session_identity,current_user::text AS current_identity,a.database_name,a.principal,a.effective FROM nearyou.assert_private_tester_baseline_verifier() a")).rows[0], observedAt = Number(completion?.observed_at); if (!Number.isSafeInteger(observedAt) || rows.length < 1 || completion?.session_identity !== expectedUser || completion.current_identity !== expectedUser || completion.database_name !== "nearyou" || completion.effective !== true || completion.principal !== "service:nearyou-private-tester-baseline-verifier" || expectedUser !== POSTGRES_READER_USER) throw new Error("private tester baseline reader unavailable"); return { observedAt, identity: `database:${completion.session_identity}`, rows }; } finally { await pool.end(); } };
  return { readMigrations: async (): Promise<Observed> => { const result = await query<{ id: string; checksum: string }>("SELECT id,checksum FROM nearyou.schema_migrations ORDER BY id"); return { provider: "cloud-sql", identity: result.identity, observedAt: result.observedAt, body: { ledger: result.rows } }; }, readCatalog: async (): Promise<Observed> => { const result = await query<{ kind: string; identity: string; definition: string }>(LIVE_CATALOG_QUERY); return { provider: "cloud-sql", identity: result.identity, observedAt: result.observedAt, body: { schema: "nearyou", relations: result.rows.map((row) => ({ name: row.identity, kind: row.kind, checksum: hash(row.definition) })) } }; } };
}
export function createAuthenticatedProductionReaders(environment: NodeJS.ProcessEnv = process.env, dependencies: { fetch?: typeof fetch; now?: () => number } = {}, expectedReleaseRaw: unknown): Readers {
  const fetcher = dependencies.fetch ?? fetch, now = dependencies.now ?? Date.now, project = envId(environment, "PRIVATE_TESTER_GCP_PROJECT", /^[a-z][a-z0-9-]{2,62}$/), dnsZone = envId(environment, "PRIVATE_TESTER_DNS_ZONE", NAME), subject = envId(environment, "PRIVATE_TESTER_READER_SUBJECT", /^[1-9][0-9]{10,30}$/), identity = `service:${subject}`; let expectedRelease: PrivateTesterRelease; try { expectedRelease = parsePrivateTesterRelease(expectedReleaseRaw, now()); } catch { throw new Error("private tester baseline configuration missing"); } const sites = sitesGateway(subject, expectedRelease, fetcher, now), postgres = postgresReaders(environment) ;
  const google = async (host: string, path: string) => stamp("google", identity, await json(`https://${host}${path}`, await token(fetcher), fetcher), now);
  const pages = async (host: string, path: string, key: string) => { const values: unknown[] = [], tokens = new Set<string>(); let pageToken = ""; for (let page = 0; page < 100; page += 1) { const separator = path.includes("?") ? "&" : "?", value = await google(host, `${path}${pageToken ? `${separator}pageToken=${encodeURIComponent(pageToken)}` : ""}`), body = value.body as RecordValue, items = body[key]; if (!Array.isArray(items) || items.length > 1_000) throw new Error("private tester baseline reader unavailable"); values.push(...items); const next = body.nextPageToken; if (next === undefined) return { meta: { provider: value.provider, identity: value.identity, observedAt: value.observedAt }, values }; if (!text(next, /^[A-Za-z0-9_-]{1,512}$/) || tokens.has(next)) throw new Error("private tester baseline reader unavailable"); tokens.add(next); pageToken = next; } throw new Error("private tester baseline reader unavailable"); };
  const runtime = async (): Promise<Observed> => { const response = await fetcher(SITES_GATEWAY_ORIGIN, { headers: { authorization: `Bearer ${await gatewayToken(fetcher)}`, accept: "text/html" }, redirect: "error", signal: AbortSignal.timeout(10_000) }), raw = await response.text(), observedAt = now(), rayId = response.headers.get("cf-ray") ?? ""; if (!response.ok || !text(rayId, /^[a-f0-9]{16}-[A-Z]{3}$/) || !Number.isSafeInteger(observedAt) || new TextEncoder().encode(raw).byteLength < 1 || new TextEncoder().encode(raw).byteLength > MAX_READER_JSON_BYTES) throw new Error("private tester baseline reader unavailable"); return { provider: "sites-runtime", identity, observedAt, rayId, body: { html: raw } }; };
  return {
    d1: { readLedger: async () => sites("d1-ledger"), readSchema: async () => sites("d1-schema"), readLedgerPage: async (cursor) => (await sites("d1-ledger-page", cursor)).body, readSchemaPage: async (cursor) => (await sites("d1-schema-page", cursor)).body },
    runtime: { readHtml: runtime },
    postgres, gates: { read: async () => sites("gates") },
    secretManager: { listVersions: async () => { const inventories = await Promise.all(REVIEWED_SECRETS.map(async (secret) => ({ secret, value: await pages("secretmanager.googleapis.com", `/v1/projects/${encodeURIComponent(project)}/secrets/${encodeURIComponent(secret)}/versions?filter=state%3DENABLED&pageSize=1000`, "versions") }))), listed = inventories.flatMap(({ secret, value }) => value.values.map((item) => item && typeof item === "object" && !Array.isArray(item) && (item as RecordValue).state === "ENABLED" && (item as RecordValue).name?.toString().startsWith(`projects/${project}/secrets/${secret}/versions/`) ? (item as RecordValue).name : undefined)), completedAt = now(); if (!Number.isSafeInteger(completedAt)) throw new Error("private tester baseline reader unavailable"); return { provider: "google", identity, observedAt: completedAt, body: { versions: listed } }; } },
    dns: { readIdentifiers: async () => { const value = await pages("dns.googleapis.com", `/dns/v1/projects/${encodeURIComponent(project)}/managedZones/${encodeURIComponent(dnsZone)}/rrsets?maxResults=1000`, "rrsets"), rows = value.values.map((item) => item && typeof item === "object" && !Array.isArray(item) && typeof (item as RecordValue).name === "string" && typeof (item as RecordValue).type === "string" && /^(?:A|AAAA|CNAME|MX|NS|SOA|TXT)$/.test(String((item as RecordValue).type)) && Array.isArray((item as RecordValue).rrdatas) ? { name: String((item as RecordValue).name).replace(/\.$/, ""), recordId: hash({ name: (item as RecordValue).name, type: (item as RecordValue).type, rrdatas: (item as RecordValue).rrdatas }), type: (item as RecordValue).type } : undefined); return { ...value.meta, body: { records: rows } }; } },
    oauth: { readIdentifiers: async () => sites("oauth") },
  };
}
async function readDeploymentManifestFile(inputPath: string): Promise<PrivateTesterDeploymentEnvelope> {
  if (!inputPath || inputPath.length > 4_096) throw new Error("private tester baseline configuration missing");
  let handle;
  try { handle = await open(inputPath, constants.O_RDONLY | constants.O_NOFOLLOW); } catch { throw new Error("private tester baseline configuration missing"); }
  try {
    const metadata = await handle.stat();
    if (!metadata.isFile() || metadata.size < 2 || metadata.size > MAX_MANIFEST_BYTES) throw new Error("private tester baseline configuration missing");
    const buffer = Buffer.alloc(MAX_MANIFEST_BYTES + 1); let length = 0;
    while (length < buffer.byteLength) { const result = await handle.read(buffer, length, buffer.byteLength - length, length); if (result.bytesRead === 0) break; length += result.bytesRead; }
    if (length > MAX_MANIFEST_BYTES || length !== metadata.size) throw new Error("private tester baseline configuration missing");
    const raw = buffer.subarray(0, length).toString("utf8"); let value: unknown;
    try { value = JSON.parse(raw); } catch { throw new Error("private tester baseline configuration missing"); }
    if (!exactRecord(value, ["claims", "signature"]) || typeof value.signature !== "string" || raw !== `{"claims":${canonicalPrivateTesterDeploymentClaims(value.claims)},"signature":${JSON.stringify(value.signature)}}\n`) throw new Error("private tester baseline configuration missing");
    return value as unknown as PrivateTesterDeploymentEnvelope;
  } finally { await handle.close(); }
}
async function readBoundedNoFollow(inputPath:string,maxBytes:number):Promise<string>{if(!inputPath||inputPath.length>4_096)throw new Error("private tester baseline configuration missing");let handle;try{handle=await open(inputPath,constants.O_RDONLY|constants.O_NOFOLLOW);const stat=await handle.stat();if(!stat.isFile()||stat.size<2||stat.size>maxBytes)throw new Error();const raw=await handle.readFile("utf8");if(Buffer.byteLength(raw)!==stat.size)throw new Error();return raw}catch{throw new Error("private tester baseline configuration missing")}finally{await handle?.close()}}
async function readBoundedBytesNoFollow(inputPath:string,maxBytes:number):Promise<Uint8Array>{if(!inputPath||inputPath.length>4_096)throw new Error("private tester baseline configuration missing");let handle;try{handle=await open(inputPath,constants.O_RDONLY|constants.O_NOFOLLOW);const stat=await handle.stat();if(!stat.isFile()||stat.size<1||stat.size>maxBytes)throw new Error();const raw=await handle.readFile();if(raw.byteLength!==stat.size)throw new Error();return raw}catch{throw new Error("private tester baseline configuration missing")}finally{await handle?.close()}}
async function main(): Promise<void> {
  const [releasePath, manifestPath, receiptPath,resourceReceiptPath, archivePath, providerLogPath, outputPath] = process.argv.slice(2);
  if (!releasePath || !manifestPath || !receiptPath ||!resourceReceiptPath|| !archivePath || !providerLogPath || !outputPath || process.argv.slice(2).length !== 7) throw new Error("private tester baseline configuration missing");
  const [releaseRaw, receiptRaw,sitesResourceReceiptRaw,sitesArchiveBytes,sitesProviderLogRaw, deploymentManifest, reviewed] = await Promise.all([readFile(releasePath, "utf8"), readFile(receiptPath, "utf8"),readBoundedNoFollow(resourceReceiptPath,1_048_576),readBoundedBytesNoFollow(archivePath,1_073_741_824),readBoundedNoFollow(providerLogPath,1_048_576), readDeploymentManifestFile(manifestPath), verifyPrivateTesterD1LiveState()]);
  const release = JSON.parse(releaseRaw), sitesDeploymentReceipt = JSON.parse(receiptRaw), expectedSitesDeploymentReceiptHash = envId(process.env, "SITES_DEPLOYMENT_RECEIPT_SHA256", HASH),expectedSitesResourceReceiptHash=envId(process.env,"SITES_RESOURCE_RECEIPT_SHA256",HASH),expectedSitesProviderLogSha256=envId(process.env,"SITES_PROVIDER_LOG_SHA256",HASH), project = envId(process.env, "KMS_PROJECT", /^[a-z][a-z0-9-]{2,62}$/), location = envId(process.env, "KMS_LOCATION", /^[A-Za-z0-9_-]{1,255}$/), keyRing = envId(process.env, "KMS_KEY_RING", /^[A-Za-z0-9_-]{1,255}$/), key = envId(process.env, "KMS_KEY", /^[A-Za-z0-9_-]{1,255}$/), principal = envId(process.env, "EVIDENCE_PRINCIPAL", /^[A-Za-z0-9_:/.@-]{3,200}$/), keyId = envId(process.env, "EVIDENCE_KEY_ID", /^[A-Za-z0-9_:/.@-]{3,200}$/), trustRaw = process.env.EVIDENCE_TRUST_JSON;
  if (!trustRaw || new TextEncoder().encode(trustRaw).byteLength > 65_536) throw new Error("private tester baseline configuration missing");
  let trust: unknown; try { trust = JSON.parse(trustRaw); } catch { throw new Error("private tester baseline configuration missing"); }
  let accessTokenValue: string | undefined; const accessToken = async () => accessTokenValue ??= await token(fetch);
  const publicKeys = new CloudKmsPublicKeyClient({ project, location, keyRing, key, principal, keyId, accessToken }), name = "pg", { Pool } = await import(name) as typeof import("pg"), pool = new Pool({ connectionString: postgresConnection(process.env), ssl: { rejectUnauthorized: false } }), nonceStore = new PostgresPrivateTesterDeploymentManifestNonceStore(pool);
  try {
    await capturePrivateTesterBaseline({ release, deploymentManifest, deploymentVerification: { trust, lookupKey: (lookupPrincipal, lookupKeyId, version) => publicKeys.lookup(lookupPrincipal, lookupKeyId, version), nonceStore: { consumeDeploymentManifestNonce: (nonce) => nonceStore.consumeDeploymentManifestNonce(nonce) } }, sitesDeploymentReceipt, expectedSitesDeploymentReceiptHash, sitesResourceReceiptRaw, expectedSitesResourceReceiptHash, sitesArchiveBytes, sitesProviderLogRaw, expectedSitesProviderLogSha256, expectedD1Ledger: reviewed.sources, expectedD1SourceHash: reviewed.sourceHash, expectedD1SchemaDefinitionHash: reviewed.schemaDefinitionHash, expectedD1SchemaObjectCount: reviewed.schemaObjectCount, outputPath, now: Date.now, readers: createAuthenticatedProductionReaders(process.env, { now: Date.now }, release) });
  } finally { await pool.end(); }
}
if (import.meta.url === `file://${process.argv[1]}`) main().catch(() => { process.stderr.write("private tester baseline failed\n"); process.exitCode = 1; });
