const PROJECT="nearnight",DISPOSABLE_INSTANCE="nearyou-evidence-20260820",CONFIRMATION=`DISPOSABLE_ROLE_ASSIGNMENT_${PROJECT}_${DISPOSABLE_INSTANCE}`,OPERATION=/^op_[a-f0-9]{64}$/;
type PlanInput={project:string;instance:string;disposable:boolean;confirmation:string;operationId:string};
type Runner=(command:string,args:string[])=>Promise<string>;
export function cloudSqlRoleAssignmentPlan(input:PlanInput){
  if(input.project!==PROJECT||input.instance!==DISPOSABLE_INSTANCE||input.disposable!==true||input.confirmation!==CONFIRMATION||!OPERATION.test(input.operationId))throw new Error("cloud sql role assignment configuration invalid");
  const assignments=[
    {databaseUser:"nf-rdy-controller@nearnight.iam",serviceAccountEmail:"nf-rdy-controller@nearnight.iam.gserviceaccount.com",cloudRunService:"nf-rdy-controller",userType:"CLOUD_IAM_SERVICE_ACCOUNT",databaseRole:"nearyou_rollout_controller"},
    {databaseUser:"nf-rdy-kill@nearnight.iam",serviceAccountEmail:"nf-rdy-kill@nearnight.iam.gserviceaccount.com",cloudRunService:"nf-rdy-kill",userType:"CLOUD_IAM_SERVICE_ACCOUNT",databaseRole:"nearyou_rollout_controller"},
    {databaseUser:"nf-rdy-decision@nearnight.iam",serviceAccountEmail:"nf-rdy-decision@nearnight.iam.gserviceaccount.com",cloudRunService:"nf-rdy-decision",userType:"CLOUD_IAM_SERVICE_ACCOUNT",databaseRole:"nearyou_private_tester_decision"},
    {databaseUser:"nearyou-pt-baseline@nearnight.iam",serviceAccountEmail:"",cloudRunService:"",userType:"CLOUD_IAM_SERVICE_ACCOUNT",databaseRole:"nearyou_private_tester_baseline_verifier"},
  ] as const;
  return{version:1 as const,project:input.project,instance:input.instance,operationId:input.operationId,disposable:true as const,confirmation:input.confirmation,requiresMigrationHead:"0014_release_policy_evidence_read" as const,exactRolesOnly:true as const,assignments:assignments.map(item=>({...item,command:["gcloud","sql","users","assign-roles",item.databaseUser,`--project=${input.project}`,`--instance=${input.instance}`,`--type=${item.userType}`,`--database-roles=${item.databaseRole}`,"--quiet"],readback:["gcloud","sql","users","list",`--project=${input.project}`,`--instance=${input.instance}`,`--filter=name=${item.databaseUser}`,"--format=json(name,type,databaseRoles)"]}))};
}
export function validateCloudSqlRoleAssignmentReadback(plan:ReturnType<typeof cloudSqlRoleAssignmentPlan>,readback:unknown){
  if(!Array.isArray(readback)||readback.length<plan.assignments.length)throw new Error("cloud sql role assignment readback invalid");
  for(const expected of plan.assignments){const row=readback.find(value=>value&&typeof value==="object"&&(value as {name?:unknown}).name===expected.databaseUser) as {name?:unknown;type?:unknown;databaseRoles?:unknown}|undefined;if(!row||row.type!==expected.userType||!Array.isArray(row.databaseRoles)||row.databaseRoles.length!==1||row.databaseRoles[0]!==expected.databaseRole)throw new Error("cloud sql role assignment readback invalid")}
  return{version:1,project:plan.project,instance:plan.instance,operationId:plan.operationId,disposable:true as const,migrationHead:plan.requiresMigrationHead,exactRolesOnly:true,assignments:plan.assignments.map(({databaseUser,serviceAccountEmail,cloudRunService,userType,databaseRole})=>({databaseUser,serviceAccountEmail,cloudRunService,userType,databaseRole})),reviewRequired:true as const};
}
export async function executeCloudSqlRoleAssignment(plan:ReturnType<typeof cloudSqlRoleAssignmentPlan>,run:Runner){for(const assignment of plan.assignments.filter(item=>item.cloudRunService)){const observed=(await run("gcloud",["run","services","describe",assignment.cloudRunService,`--project=${plan.project}`,"--region=us-central1","--format=value(spec.template.spec.serviceAccountName)"])).trim();if(observed!==assignment.serviceAccountEmail)throw new Error("cloud run service identity readback invalid")}const listArgs=["sql","users","list",`--project=${plan.project}`,`--instance=${plan.instance}`,"--format=json(name,type,databaseRoles)"],initialText=await run("gcloud",listArgs);let initial:unknown;try{initial=JSON.parse(initialText)}catch{throw new Error("cloud sql user preflight invalid")}if(!Array.isArray(initial))throw new Error("cloud sql user preflight invalid");for(const assignment of plan.assignments){const row=initial.find(value=>value&&typeof value==="object"&&(value as{name?:unknown}).name===assignment.databaseUser)as{type?:unknown}|undefined;if(row&&row.type!==assignment.userType)throw new Error("cloud sql user preflight invalid");if(!row)await run("gcloud",["sql","users","create",assignment.databaseUser,`--project=${plan.project}`,`--instance=${plan.instance}`,`--type=${assignment.userType}`,"--quiet"])}for(const assignment of plan.assignments){const[command,...args]=assignment.command;await run(command,args)}const output=await run("gcloud",listArgs);let readback:unknown;try{readback=JSON.parse(output)}catch{throw new Error("cloud sql role assignment readback invalid")}return validateCloudSqlRoleAssignmentReadback(plan,readback)}
async function cli(){const{execFile}=await import("node:child_process"),{promisify}=await import("node:util"),{writeFile}=await import("node:fs/promises"),{createHash}=await import("node:crypto"),output=process.argv[2];if(!output)throw new Error("cloud sql role assignment output missing");const seed=process.env.NEARYOU_CLOUD_SQL_ROLE_OPERATION_SEED??"",plan=cloudSqlRoleAssignmentPlan({project:process.env.NEARYOU_CLOUD_SQL_ROLE_PROJECT??"",instance:process.env.NEARYOU_CLOUD_SQL_ROLE_INSTANCE??"",disposable:process.env.NEARYOU_CLOUD_SQL_ROLE_DISPOSABLE==="true",confirmation:process.env.NEARYOU_CLOUD_SQL_ROLE_CONFIRMATION??"",operationId:`op_${createHash("sha256").update(seed).digest("hex")}`}),execute=promisify(execFile),receipt=await executeCloudSqlRoleAssignment(plan,async(command,args)=>(await execute(command,args,{maxBuffer:1024*1024})).stdout);await writeFile(output,`${JSON.stringify(receipt)}\n`,{flag:"wx",mode:0o600})}
if(process.argv[1]?.endsWith("cloud-sql-role-assignment-plan.ts"))cli().catch(error=>{console.error(error instanceof Error?error.message:"cloud sql role assignment failed");process.exitCode=1});
