import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
const schema = await import(new URL("../db/schema.ts", import.meta.url).href) as typeof import("../db/schema");
import { getTableConfig } from "drizzle-orm/sqlite-core";

const explicitKeys: Record<string, string[]> = {
  legacy_evidence_retention: ["household_id", "consent_id"],
  legacy_export_consents: ["household_id", "export_id", "consent_id"],
  legacy_memory_tags: ["household_id", "memory_id", "tag_id"],
  legacy_query_sources: ["household_id", "query_receipt_id", "rank"],
  legacy_rate_limits: ["household_id", "user_id", "operation"],
};
// Cross-system delivery bookkeeping is operational evidence, not historical user-domain state.
const nonDomainTables = new Set(["operational_outcome_outbox", "canary_entitlement_audit"]);
const entries = [] as Array<{ exportName: string; table: string; columns: string[]; primaryKey: string[]; scope: { kind: "tenant"; column: "household_id" } | { kind: "global" } }>;

for (const [exportName, value] of Object.entries(schema)) {
  try {
    const config = getTableConfig(value as never);
    if (!config.name || !config.columns.length || nonDomainTables.has(config.name)) continue;
    const declared = [...config.columns.filter(column => column.primary).map(column => column.name), ...config.primaryKeys.flatMap(key => key.columns.map(column => column.name))];
    const primaryKey = [...new Set(declared.length ? declared : explicitKeys[config.name] ?? [])];
    if (!primaryKey.length) throw new Error(`missing inventory key ${config.name}`);
    const columns = config.columns.map(column => column.name);
    entries.push({ exportName, table: config.name, columns, primaryKey, scope: columns.includes("household_id") ? { kind: "tenant", column: "household_id" } : { kind: "global" } });
  } catch (error) {
    if (error instanceof Error && error.message.startsWith("missing inventory")) throw error;
  }
}
entries.sort((left, right) => left.table < right.table ? -1 : left.table > right.table ? 1 : 0);
const canonical = JSON.stringify(entries), checksum = createHash("sha256").update(canonical).digest("hex");
const output = `// Generated by scripts/generate-d1-domain-registry.ts. Do not edit.\nexport const D1_DOMAIN_REGISTRY_VERSION=1 as const;\nexport const D1_DOMAIN_REGISTRY_CHECKSUM=${JSON.stringify(checksum)} as const;\nexport const D1_DOMAIN_REGISTRY=${JSON.stringify(entries, null, 2)} as const;\n`;
const triggerSql = entries.flatMap(entry => ["INSERT", "UPDATE", "DELETE"].map(kind => `CREATE TRIGGER cutover_inventory_fence_${entry.table}_${kind.toLowerCase()} BEFORE ${kind} ON "${entry.table}" WHEN EXISTS(SELECT 1 FROM cutover_maintenance_fence WHERE singleton=1 AND active=1) BEGIN SELECT RAISE(ABORT,'cutover maintenance fence active'); END;`)).join("\n") + "\n";
const registryUrl = new URL("../lib/d1-domain-registry.generated.ts", import.meta.url), triggerUrl = new URL("../drizzle/0018_cutover_inventory_fence.generated.sql", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(registryUrl, "utf8") !== output || readFileSync(triggerUrl, "utf8") !== triggerSql) throw new Error("D1 domain registry artifacts are stale");
} else {
  writeFileSync(registryUrl, output);
  writeFileSync(triggerUrl, triggerSql);
}
