import {createHash} from "node:crypto";
import {DatabaseSync} from "node:sqlite";
import {readFileSync,writeFileSync} from "node:fs";
import {SITES_D1_PHASE_A_ARTIFACT} from "../lib/sites-d1-phase-a-artifact.generated";
import {SITES_D1_PHASE_A_BOOTSTRAP} from "../lib/sites-d1-phase-a-operation";
import {SITES_D1_PHASE_B_ARTIFACT} from "../lib/sites-d1-phase-b-artifact.generated";
const root=new URL("../",import.meta.url),canonical=(v:unknown)=>JSON.stringify(v),sha=(v:string|Buffer)=>createHash("sha256").update(v).digest("hex");
const provider=new Set(["index\0sqlite_autoindex___appgarden_migrations_1\0__appgarden_migrations","table\0__appgarden_migrations\0__appgarden_migrations","table\0_cf_KV\0_cf_KV","table\0sqlite_sequence\0sqlite_sequence","table\0sqlite_stat1\0sqlite_stat1"]);
const split=(source:string,id:string)=>{const primary=source.split(/\s*-->\s*statement-breakpoint\s*/g).map(x=>x.trim()).filter(Boolean);if(id.startsWith("0015_")&&primary.length===1)return source.split(/;\s*(?=CREATE\s)/i).map(x=>`${x.trim()};`).filter(x=>x!==";");return primary};
const bootstrap=[
 "CREATE TABLE nearyou_d1_phase_c_operations(phase TEXT PRIMARY KEY NOT NULL,operation_id TEXT NOT NULL UNIQUE,release_id TEXT NOT NULL,manifest_sha256 TEXT NOT NULL,phase_b_operation_id TEXT NOT NULL,phase_b_manifest_sha256 TEXT NOT NULL,status TEXT DEFAULT 'running' NOT NULL CHECK(status IN('running','complete')),created_at INTEGER NOT NULL,completed_at INTEGER)",
 "CREATE TABLE nearyou_d1_phase_c_migrations(migration_id TEXT PRIMARY KEY NOT NULL,operation_id TEXT NOT NULL,source_sha256 TEXT NOT NULL,schema_sha256 TEXT NOT NULL,object_count INTEGER NOT NULL,applied_at INTEGER NOT NULL,FOREIGN KEY(operation_id) REFERENCES nearyou_d1_phase_c_operations(operation_id))",
 "CREATE TRIGGER nearyou_d1_phase_c_operations_update_guard BEFORE UPDATE ON nearyou_d1_phase_c_operations WHEN NOT(OLD.status='running' AND NEW.status='complete' AND OLD.phase IS NEW.phase AND OLD.operation_id IS NEW.operation_id AND OLD.release_id IS NEW.release_id AND OLD.manifest_sha256 IS NEW.manifest_sha256 AND OLD.phase_b_operation_id IS NEW.phase_b_operation_id AND OLD.phase_b_manifest_sha256 IS NEW.phase_b_manifest_sha256 AND OLD.created_at IS NEW.created_at AND OLD.completed_at IS NULL AND NEW.completed_at IS NOT NULL) BEGIN SELECT RAISE(ABORT,'phase_c_operation_immutable'); END",
 "CREATE TRIGGER nearyou_d1_phase_c_migrations_update_guard BEFORE UPDATE ON nearyou_d1_phase_c_migrations BEGIN SELECT RAISE(ABORT,'phase_c_migration_immutable'); END",
 "CREATE TRIGGER nearyou_d1_phase_c_operations_delete_guard BEFORE DELETE ON nearyou_d1_phase_c_operations BEGIN SELECT RAISE(ABORT,'phase_c_operation_immutable'); END",
 "CREATE TRIGGER nearyou_d1_phase_c_migrations_delete_guard BEFORE DELETE ON nearyou_d1_phase_c_migrations BEGIN SELECT RAISE(ABORT,'phase_c_migration_immutable'); END",
] as const;
const schemaPath=process.env.D1_PHASE_A_SCHEMA_EVIDENCE;if(!schemaPath)throw new Error("Phase C schema evidence missing");const raw=JSON.parse(readFileSync(schemaPath,"utf8")) as {body:{objects:{type:string;name:string;tableName:string;sql:string|null}[]}};
const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=OFF");for(const type of["table","index","trigger","view"])for(const x of raw.body.objects.filter(x=>x.type===type&&x.sql&&!provider.has(`${x.type}\0${x.name}\0${x.tableName}`)))db.exec(x.sql!);for(const x of SITES_D1_PHASE_A_BOOTSTRAP)db.exec(x);for(const m of SITES_D1_PHASE_A_ARTIFACT.migrations)for(const x of m.statements)db.exec(x);for(const x of SITES_D1_PHASE_B_ARTIFACT.bootstrap)db.exec(x);for(const m of SITES_D1_PHASE_B_ARTIFACT.migrations)for(const x of m.statements)db.exec(x);
const definitions=()=>db.prepare("SELECT type,name,tbl_name AS tableName,sql FROM sqlite_schema WHERE type IN ('table','index','trigger','view') ORDER BY type,name,tbl_name").all().map(x=>({...x})).filter(x=>!provider.has(`${x.type}\0${x.name}\0${x.tableName}`)),checkpoint=()=>{const x=definitions();return{objectCount:x.length,definitionsSha256:sha(canonical(x))}};
const phaseBPredecessor=SITES_D1_PHASE_B_ARTIFACT.schemaCheckpoints.at(-1)!;if(canonical(checkpoint())!==canonical({objectCount:phaseBPredecessor.objectCount,definitionsSha256:phaseBPredecessor.definitionsSha256}))throw new Error("Phase C predecessor mismatch");const schemaCheckpoints=[{head:"0012",...checkpoint()}];for(const x of bootstrap)db.exec(x);schemaCheckpoints.push({head:"0012+phase-c-operation",...checkpoint()});
const ids=["0013_nearstory_parent_beta","0014_nearlegacy_archive","0015_platform_release_foundation","0016_marketing_waitlist"] as const,migrations=ids.map(id=>{const statements=split(readFileSync(new URL(`drizzle/${id}.sql`,root),"utf8"),id),sql=`${statements.join("\n--> statement-breakpoint\n")}\n`;for(const x of statements)db.exec(x);schemaCheckpoints.push({head:id.slice(0,4),...checkpoint()});return{id,sql,sha256:sha(sql),statements}});
if(db.prepare("PRAGMA foreign_key_check").all().length)throw new Error("Phase C foreign key check failed");
const artifact={version:1,phaseBReceipt:{operationId:"d1-phase-b:rel_20260818_private_01",manifestSha256:"dfcbf89e178c1cb405a58cc5139a4bd8ee1053a0ef1bf3c850dbd1889b36bab8"},phaseBPredecessor,bootstrap,migrations,schemaCheckpoints,dataDependencyAudit:[{migrationId:ids[0],classification:"constant-new-table-seed",writeStatementOrdinals:[24]},{migrationId:ids[1],classification:"constant-new-table-seed",writeStatementOrdinals:[2]},{migrationId:ids[2],classification:"ddl-only",writeStatementOrdinals:[]},{migrationId:ids[3],classification:"ddl-only",writeStatementOrdinals:[]}]};
const output=`// Generated by scripts/generate-sites-d1-phase-c-artifact.ts from exact Phase B. Do not edit.\nexport const SITES_D1_PHASE_C_ARTIFACT=${canonical(artifact)} as const;\n`,target=new URL("lib/sites-d1-phase-c-artifact.generated.ts",root);if(process.argv.includes("--check")){if(readFileSync(target,"utf8")!==output)throw new Error("Sites D1 Phase C artifact stale")}else writeFileSync(target,output);
