import {createHash} from "node:crypto";
import {DatabaseSync} from "node:sqlite";
import {readFileSync,readdirSync,writeFileSync} from "node:fs";
import {SITES_D1_OPERATION_BOOTSTRAP,splitD1Migration} from "../lib/sites-d1-forward-operation";

const root=new URL("../",import.meta.url);
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const canonical=(value:unknown)=>JSON.stringify(value);
const prefixFiles=readdirSync(new URL("drizzle",root)).filter(file=>/^00(?:0[0-9]|1[0-6])_.*\.sql$/.test(file)).sort();
const sourceFiles=readdirSync(new URL("drizzle",root)).filter(file=>/^00(?:1[7-9]|2[0-5])_.*\.sql$/.test(file)).sort();
const parseDb=new DatabaseSync(":memory:");
for(const file of prefixFiles)parseDb.exec(readFileSync(new URL(`drizzle/${file}`,root),"utf8"));

function completeStatements(sql:string){
 const statements:string[]=[];let buffer="";
 for(const line of sql.split(/\r?\n/)){
  if(/^\s*-->\s*statement-breakpoint\s*$/.test(line))continue;
  buffer+=`${line}\n`;
  if(!buffer.trimEnd().endsWith(";"))continue;
  try{parseDb.prepare(buffer);const statement=buffer.trim();if(statement){parseDb.exec(statement);statements.push(statement)}buffer=""}
  catch(error){const message=error instanceof Error?error.message:"";if(message==="incomplete input"||message==="statement has been finalized")continue;throw error}
 }
 if(buffer.trim())throw new Error("incomplete migration source");
 return statements;
}

const normalizedSources=sourceFiles.map(file=>{
 const url=new URL(`drizzle/${file}`,root),original=readFileSync(url,"utf8"),statements=completeStatements(original),sql=`${statements.join("\n--> statement-breakpoint\n")}\n`;
 if(process.argv.includes("--normalize-breakpoints"))writeFileSync(url,sql);
 else if(original!==sql)throw new Error(`migration breakpoints stale: ${file}`);
 return{id:file.replace(/\.sql$/, ""),sql};
});
const pending=readFileSync(new URL("docs/pending/0026_canary_entitlements.sql.disabled",root),"utf8").trim();
const source0026=`${pending}\n--> statement-breakpoint\nCREATE TRIGGER canary_entitlement_audit_update_guard BEFORE UPDATE ON canary_entitlement_audit BEGIN SELECT RAISE(ABORT,'canary entitlement audit immutable'); END;\n--> statement-breakpoint\nCREATE TRIGGER canary_entitlement_audit_delete_guard BEFORE DELETE ON canary_entitlement_audit BEGIN SELECT RAISE(ABORT,'canary entitlement audit immutable'); END;`;
const migrations=[...normalizedSources,{id:"0026_canary_entitlements",sql:source0026}].map(value=>({...value,sha256:hash(value.sql),statements:splitD1Migration(value.sql)}));

const db=new DatabaseSync(":memory:");
for(const file of prefixFiles)db.exec(readFileSync(new URL(`drizzle/${file}`,root),"utf8"));
db.exec("CREATE TABLE d1_migrations(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,applied_at TEXT NOT NULL)");
for(const [index,file] of prefixFiles.entries())db.prepare("INSERT INTO d1_migrations VALUES(?,?,CURRENT_TIMESTAMP)").run(index+1,file.replace(/\.sql$/, ""));
const providerNames=new Set(["sqlite_autoindex_d1_migrations_1","_cf_METADATA","d1_migrations","sqlite_sequence","sqlite_stat1"]);
const providerObjects=[{type:"index",name:"sqlite_autoindex_d1_migrations_1",tableName:"d1_migrations"},{type:"table",name:"_cf_METADATA",tableName:"_cf_METADATA"},{type:"table",name:"d1_migrations",tableName:"d1_migrations"},{type:"table",name:"sqlite_sequence",tableName:"sqlite_sequence"},{type:"table",name:"sqlite_stat1",tableName:"sqlite_stat1"}];
const checkpoints:Array<{head:string;objectCount:number;definitionsSha256:string;providerObjects:typeof providerObjects}>=[];
const capture=(head:string)=>{const rows=db.prepare("SELECT type,name,tbl_name AS tableName,sql FROM sqlite_schema WHERE type IN ('table','index','trigger','view') ORDER BY type,name,tbl_name").all().filter(row=>!providerNames.has(String(row.name)));checkpoints.push({head,objectCount:rows.length,definitionsSha256:hash(canonical(rows)),providerObjects})};
capture("0016");for(const sql of SITES_D1_OPERATION_BOOTSTRAP)db.exec(sql);capture("0016+operation");
for(const migration of migrations){for(const statement of migration.statements)db.exec(statement);db.prepare("INSERT INTO d1_migrations(name,applied_at) VALUES(?,CURRENT_TIMESTAMP)").run(migration.id);capture(migration.id.slice(0,4))}
const artifact={version:1,migrations:migrations.map(({id,sha256,sql,statements})=>({id,sha256,sql,statements})),schemaCheckpoints:checkpoints};
const output=`// Generated by scripts/generate-sites-d1-forward-artifact.ts. Do not edit.\nexport const SITES_D1_FORWARD_ARTIFACT=${JSON.stringify(artifact)} as const;\n`;
const target=new URL("lib/sites-d1-forward-artifact.generated.ts",root);
if(process.argv.includes("--check")){if(readFileSync(target,"utf8")!==output)throw new Error("Sites D1 forward artifact stale")}else writeFileSync(target,output);
