import{readFile,readdir}from"node:fs/promises";import{registerRolloutController,type AdminPg}from"./register-rollout-controller";import{registerPrivateTesterBaselineVerifier}from"./register-private-tester-baseline-verifier";import{LIVE_CATALOG_QUERY}from"./postgres-catalog";
const encoder=new TextEncoder(),HASH=/^[a-f0-9]{64}$/,RELEASE=/^rel_[A-Za-z0-9_-]{8,100}$/;
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,"0")).join("");const digest=async(v:string)=>hex(await crypto.subtle.digest("SHA-256",encoder.encode(v)));
type Options={databaseUrlFile?:string;release:string;schemaChecksum:string;catalogChecksum:string};export type MigrationFile={id:string;sql:string;checksum:string};
export function parseMigrationArgs(args:string[]):Options{const values=new Map<string,string>(),allowed=new Set(["--database-url-file","--release","--schema-checksum","--catalog-checksum"]);let mode=false;for(let i=0;i<args.length;i++){const key=args[i]!;if(key==="--register-rollout-controller"){if(mode)throw new Error("migration arguments invalid");mode=true;continue}if(!allowed.has(key)||values.has(key)||i+1>=args.length||args[i+1]!.startsWith("--"))throw new Error("migration arguments invalid");values.set(key,args[++i]!)}const release=values.get("--release"),schemaChecksum=values.get("--schema-checksum"),catalogChecksum=values.get("--catalog-checksum");if(!mode||!release||!RELEASE.test(release)||!schemaChecksum||!HASH.test(schemaChecksum)||!catalogChecksum||!HASH.test(catalogChecksum))throw new Error("migration arguments invalid");return{databaseUrlFile:values.get("--database-url-file"),release,schemaChecksum,catalogChecksum}}
export async function loadPostgresMigrations(directory=new URL("../postgres/migrations/",import.meta.url)){const names=(await readdir(directory)).filter(name=>/^\d{4}_[a-z0-9_]+\.sql$/.test(name)).sort();return Promise.all(names.map(async name=>{const sql=await readFile(new URL(name,directory),"utf8");return{id:name.slice(0,-4),sql,checksum:await digest(sql)}}))}
const body=(sql:string)=>sql.replace(/^\s*BEGIN;\s*/i,"").replace(/\s*COMMIT;\s*$/i,"");
const BASE_MIGRATION_ROLES=["nearyou_app","nearyou_billing_worker","nearyou_cutover_policy_owner","nearyou_cutover_runner","nearyou_job_worker","nearyou_migration","nearyou_policy_owner","nearyou_release_key_manager","nearyou_release_maintenance","nearyou_release_policy_owner","nearyou_release_verifier","nearyou_rollout_controller"] as const;
const PRECREATED_MIGRATION_ROLES=new Set<string>(BASE_MIGRATION_ROLES.filter(role=>role!=="nearyou_rollout_controller"));
type MigrationTx={query<T=Record<string,unknown>>(sql:string,args?:unknown[]):Promise<{rows:T[]}>};
async function grantTemporaryMigrationRoles(tx:MigrationTx,includeBaselineVerifier:boolean){const roles=[...BASE_MIGRATION_ROLES,...(includeBaselineVerifier?["nearyou_private_tester_baseline_verifier"]:[])],prior=new Map<string,{admin_option:boolean;inherit_option:boolean;set_option:boolean}|null>();for(const role of roles){const membership=(await tx.query<{admin_option:boolean;inherit_option:boolean;set_option:boolean}>("SELECT m.admin_option,m.inherit_option,m.set_option FROM pg_auth_members m JOIN pg_roles r ON r.oid=m.roleid WHERE r.rolname=$1 AND m.member=(SELECT oid FROM pg_roles WHERE rolname=current_user)",[role])).rows[0]??null;prior.set(role,membership);if(PRECREATED_MIGRATION_ROLES.has(role)){await tx.query(`DO $role$ BEGIN CREATE ROLE ${role} NOLOGIN NOINHERIT; EXCEPTION WHEN duplicate_object THEN NULL; END $role$`,[]);await tx.query(`GRANT ${role} TO CURRENT_USER WITH ADMIN FALSE, INHERIT FALSE, SET TRUE`,[])}}return async()=>{for(const role of roles.reverse()){const membership=prior.get(role);if(!membership)await tx.query(`REVOKE ${role} FROM CURRENT_USER`,[]);else await tx.query(`GRANT ${role} TO CURRENT_USER WITH ADMIN ${membership.admin_option?"TRUE":"FALSE"}, INHERIT ${membership.inherit_option?"TRUE":"FALSE"}, SET ${membership.set_option?"TRUE":"FALSE"}`,[])}}}
const LEGACY_MIGRATION_CHECKSUMS=new Map([
  ["0001_nearyou_tenant_foundation","ae9a5e8f26190063382d76eae25565a6a991523edf6ceefa1abd74b1fd88a194"],
  ["0002_release_evidence_trust","7ec295cb252f9d8cf54d951e899a59ddb834a1204de951a7d967eeeaf67c11f8"],
  ["0003_cutover_runtime","ed449236853519c58fabbd13eca2587c515447bdff81b3a6153d9afe0436aede"],
  ["0004_product_readiness_evidence","481c48d0b1ca224decdf5b049325ec44c048b7dcc90572c24a66dd2d1e5301c9"],
]);
export function acceptsMigrationLedger(files:MigrationFile[],ledger:{id:string;checksum:string}[]){return ledger.length===files.length&&ledger.every((row,index)=>row.id===files[index]?.id&&(row.checksum===files[index]?.checksum||row.checksum===LEGACY_MIGRATION_CHECKSUMS.get(row.id)))}
export async function applyPostgresMigrations(pg:AdminPg,files:MigrationFile[],expected:string){if(!files.length||!files.some(f=>f.id.startsWith("0004_"))||files.some((f,i)=>!/^\d{4}_[a-z0-9_]+$/.test(f.id)||!HASH.test(f.checksum)||i>0&&f.id<=files[i-1]!.id))throw new Error("migration set invalid");const migrationLedgerChecksum=await digest(files.map(f=>`${f.id}:${f.checksum}`).join("\n"));if(migrationLedgerChecksum!==expected)throw new Error("migration schema checksum mismatch");await pg.transaction(async tx=>{await tx.query("SELECT pg_advisory_xact_lock(hashtext('nearyou-postgres-migrations'))",[]);await tx.query("CREATE SCHEMA IF NOT EXISTS nearyou",[]);await tx.query("CREATE TABLE IF NOT EXISTS nearyou.schema_migrations(id text PRIMARY KEY,checksum text NOT NULL CHECK(checksum~'^[a-f0-9]{64}$'),applied_at timestamptz NOT NULL DEFAULT statement_timestamp())",[]);const restoreMigrationRoles=await grantTemporaryMigrationRoles(tx,files.some(file=>file.id==="0007_private_tester_deployment_manifest"));for(const file of files){const prior=(await tx.query<{checksum:string}>("SELECT checksum FROM nearyou.schema_migrations WHERE id=$1 FOR UPDATE",[file.id])).rows[0];if(prior){if(prior.checksum!==file.checksum&&prior.checksum!==LEGACY_MIGRATION_CHECKSUMS.get(file.id))throw new Error("migration ledger conflict");continue}const sql=body(file.sql);try{await tx.query(sql,[])}catch(error){const detail=typeof error==="object"&&error!==null?error as{position?:unknown;routine?:unknown}:{},position=typeof detail.position==="string"&&/^[1-9][0-9]{0,8}$/.test(detail.position)&&Number(detail.position)<=sql.length?`:position-${detail.position}`:"",routine=typeof detail.routine==="string"&&/^[a-z_]{1,80}$/.test(detail.routine)?`:routine-${detail.routine}`:"";throw new Error(`migration execution failed:${file.id}${position}${routine}`,{cause:error})}await tx.query("INSERT INTO nearyou.schema_migrations(id,checksum) VALUES($1,$2)",[file.id,file.checksum])}await restoreMigrationRoles()});return{appliedMigrationIds:files.map(f=>f.id),migrationLedgerChecksum,liveSchemaChecksum:migrationLedgerChecksum,liveRlsChecksum:await digest(files.filter(f=>/policy|row level|force rls/i.test(f.sql)).map(f=>`${f.id}:${f.checksum}`).join("\n"))}}
export async function assertMigrationBootstrapAuthority(pg:AdminPg){return pg.transaction(async tx=>{const row=(await tx.query<{allowed:boolean;database_user:string}>("SELECT (rolcreaterole AND (rolsuper OR pg_has_role(current_user,'cloudsqlsuperuser','USAGE'))) AS allowed,current_user::text AS database_user FROM pg_roles WHERE rolname=current_user",[])).rows[0];if(!row?.allowed||!/migration|postgres|admin/i.test(row.database_user))throw new Error("migration admin privilege invalid");return row.database_user})}
export async function attestLiveCatalog(pg:AdminPg,expected:string){return pg.transaction(async tx=>{const privilege=(await tx.query<{allowed:boolean;database_user:string}>("SELECT (rolcreaterole AND (rolsuper OR pg_has_role(current_user,'cloudsqlsuperuser','USAGE'))) AS allowed,current_user::text AS database_user FROM pg_roles WHERE rolname=current_user",[])).rows[0];if(!privilege?.allowed||!/migration|postgres|admin/i.test(privilege.database_user))throw new Error("migration admin privilege invalid");const rows=(await tx.query<{kind:string;identity:string;definition:string}>(LIVE_CATALOG_QUERY,[])).rows;/* old inline query retained only in patch history
SELECT 'schema' kind,n.nspname identity,concat_ws('|',pg_get_userbyid(n.nspowner),n.nspacl) definition FROM pg_namespace n WHERE n.nspname='nearyou'
UNION ALL SELECT 'table',n.nspname||'.'||c.relname,concat_ws('|',pg_get_userbyid(c.relowner),c.relrowsecurity,c.relforcerowsecurity,c.relacl) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nearyou' AND c.relkind IN('r','p')
UNION ALL SELECT 'column' kind,n.nspname||'.'||c.relname||'.'||a.attnum identity,format('%s|%s|%s',a.attname,pg_catalog.format_type(a.atttypid,a.atttypmod),a.attnotnull) definition FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nearyou' AND a.attnum>0 AND NOT a.attisdropped
UNION ALL SELECT 'constraint',n.nspname||'.'||c.relname||'.'||x.conname,pg_get_constraintdef(x.oid,true) FROM pg_constraint x JOIN pg_class c ON c.oid=x.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nearyou'
UNION ALL SELECT 'index',schemaname||'.'||tablename||'.'||indexname,indexdef FROM pg_indexes WHERE schemaname='nearyou'
UNION ALL SELECT 'trigger',n.nspname||'.'||c.relname||'.'||t.tgname,concat_ws('|',t.tgenabled,pg_get_triggerdef(t.oid,true)) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nearyou' AND NOT t.tgisinternal
UNION ALL SELECT 'policy',schemaname||'.'||tablename||'.'||policyname,concat_ws('|',cmd,qual,with_check) FROM pg_policies WHERE schemaname='nearyou'
UNION ALL SELECT 'function',n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')',concat_ws('|',p.prosecdef,pg_get_userbyid(p.proowner),p.proconfig,p.proacl,pg_get_functiondef(p.oid)) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='nearyou'
UNION ALL SELECT 'sequence',n.nspname||'.'||c.relname,concat_ws('|',pg_get_userbyid(c.relowner),c.relacl) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nearyou' AND c.relkind='S'
UNION ALL SELECT 'extension',e.extname,concat_ws('|',e.extversion,n.nspname) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace
UNION ALL SELECT 'role',rolname,concat_ws('|',rolsuper,rolcreaterole,rolcreatedb,rolcanlogin,rolbypassrls) FROM pg_roles WHERE rolname LIKE 'nearyou%'
UNION ALL SELECT 'membership',member.rolname||'->'||role.rolname,concat_ws('|',admin.rolname,m.admin_option,m.inherit_option,m.set_option) FROM pg_auth_members m JOIN pg_roles role ON role.oid=m.roleid JOIN pg_roles member ON member.oid=m.member LEFT JOIN pg_roles admin ON admin.oid=m.grantor WHERE role.rolname LIKE 'nearyou%' OR member.rolname LIKE 'nearyou%'
) observed ORDER BY kind COLLATE "C",identity COLLATE "C",definition COLLATE "C"*/if(!rows.length)throw new Error("migration catalog empty");const canonical=JSON.stringify(rows),liveCatalogChecksum=await digest(canonical);if(liveCatalogChecksum!==expected)throw new Error("migration catalog mismatch");const liveRlsChecksum=await digest(JSON.stringify(rows.filter(row=>row.kind==="policy"||row.kind==="function")));return{liveCatalogChecksum,liveRlsChecksum,catalogRows:rows.length,adminDatabaseUser:privilege.database_user,catalogMismatches:0}})}
type Deps={connect(url:string):Promise<{pg:AdminPg;close():Promise<void>}>;readSecret(path:string):Promise<string>;evidenceSink(evidence:string):Promise<void>;now():number;migrations?:MigrationFile[]};
export async function runMigrationCli(args:string[],environment:Record<string,string|undefined>,provided?:Deps){const options=parseMigrationArgs(args),user=environment.NEARYOU_READINESS_DATABASE_USER,principal=environment.NEARYOU_READINESS_OIDC_PRINCIPAL,verifierUser=environment.NEARYOU_PRIVATE_TESTER_BASELINE_DATABASE_USER,verifierPrincipal=environment.NEARYOU_PRIVATE_TESTER_BASELINE_OIDC_PRINCIPAL,envUrl=environment.READINESS_CONTROL_DATABASE_URL;if(!user||!principal||!verifierUser||!verifierPrincipal||Boolean(options.databaseUrlFile)===Boolean(envUrl))throw new Error("migration controller configuration missing");const runtime=provided??{readSecret:async path=>{const value=await readFile(path,"utf8");if(encoder.encode(value).byteLength>8192)throw new Error("migration secret invalid");return value.trim()},connect:async(connectionString:string)=>{const moduleName="pg",{Pool}=await import(moduleName)as{Pool:new(input:{connectionString:string})=>{connect():Promise<{query<T>(sql:string,args?:unknown[]):Promise<{rows:T[]}>;release():void}>;end():Promise<void>}};const pool=new Pool({connectionString}),client=await pool.connect(),pg:AdminPg={transaction:async run=>{await client.query("BEGIN");try{const result=await run({query:(sql,params)=>client.query(sql,params)});await client.query("COMMIT");return result}catch(error){await client.query("ROLLBACK");throw error}}};return{pg,close:async()=>{client.release();await pool.end()}}},evidenceSink:async evidence=>{process.stdout.write(`${evidence}\n`)},now:()=>Date.now()};const url=envUrl??await runtime.readSecret(options.databaseUrlFile!);if(!/^postgres(?:ql)?:\/\//.test(url)||encoder.encode(url).byteLength>8192)throw new Error("migration secret invalid");const connection=await runtime.connect(url);try{await assertMigrationBootstrapAuthority(connection.pg);const migration=await applyPostgresMigrations(connection.pg,provided?.migrations??await loadPostgresMigrations(),options.schemaChecksum),mapping=await registerRolloutController(connection.pg,user,principal),verifierMapping=await registerPrivateTesterBaselineVerifier(connection.pg,verifierUser,verifierPrincipal),catalog=await attestLiveCatalog(connection.pg,options.catalogChecksum),verifiedAt=runtime.now(),artifactPayload={databaseUser:user,principal,verifierDatabaseUser:verifierUser,verifierPrincipal,release:options.release,schemaChecksum:options.schemaChecksum,verifiedAt,membership:true,mapping:true,verifierMembership:true,verifierMapping:true,...migration,...catalog},artifact=await digest(JSON.stringify(artifactPayload)),evidence=JSON.stringify({version:1,controllerMappingVerified:mapping.controllerMappingVerified,baselineVerifierMappingVerified:verifierMapping.baselineVerifierMappingVerified,artifact,artifactPayload});if(encoder.encode(evidence).byteLength>8192)throw new Error("migration evidence invalid");await runtime.evidenceSink(evidence);return JSON.parse(evidence)}finally{await connection.close()}}
if(import.meta.url===`file://${process.argv[1]}`)runMigrationCli(process.argv.slice(2),process.env).catch(()=>{process.stderr.write("migration registration failed\n");process.exitCode=1});
