import { createHash } from "node:crypto";
import { constants } from "node:fs";
import { open, writeFile } from "node:fs/promises";
import { parsePrivateTesterRelease } from "../lib/private-tester-release";

const HASH=/^[a-f0-9]{64}$/,RAY=/^[a-f0-9]{16}-[A-Z]{3}$/,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,VERSION=/^appgprj_[a-f0-9]{32}~appgver_[A-Za-z0-9_-]{3,160}$/,COMMIT=/^[a-f0-9]{40}$/;
const PRODUCTION_PROJECT="nearnight",DEPLOYMENT=/^appgdep_[A-Za-z0-9_-]{8,152}$/,SERVICE=/^service:[1-9][0-9]{10,30}$/;
const REVIEWED_SECRETS=["nearyou-prod-app","nearyou-prod-legacy","nearyou-prod-pad","nearyou-prod-migration-admin"];
type Value=Record<string,unknown>;
const exact=(value:unknown,keys:readonly string[]):value is Value=>!!value&&typeof value==="object"&&!Array.isArray(value)&&JSON.stringify(Object.keys(value).sort())===JSON.stringify([...keys].sort());
const sha=(value:string)=>createHash("sha256").update(value).digest("hex"),canonicalHash=(value:unknown)=>sha(JSON.stringify(value));
function invalid():never{throw new Error("private tester baseline promotion invalid")}
async function readExact(path:string){let handle;try{handle=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW);const stat=await handle.stat();if(!stat.isFile()||stat.size<2||stat.size>4_000_000)invalid();const raw=await handle.readFile("utf8");if(Buffer.byteLength(raw)!==stat.size)invalid();return{raw,value:JSON.parse(raw)as unknown}}catch{invalid()}finally{await handle?.close()}}
function hashField(value:unknown){if(typeof value!=="string"||!HASH.test(value))invalid()}
export function validatePrivateTesterBaselineCandidate(value:unknown,nowMs:number){if(!Number.isSafeInteger(nowMs)||!exact(value,["version","reviewRequired","capturedAt","release","sites","d1","postgres","dns","oauth","bindings","secretVersions","gates","observations"])||value.version!==1||value.reviewRequired!==true||!Number.isSafeInteger(value.capturedAt))invalid();const capturedAt=Number(value.capturedAt);if(capturedAt>nowMs||capturedAt<nowMs-300_000)invalid();let release;try{release=parsePrivateTesterRelease(value.release,capturedAt)}catch{invalid()}
 const sites=value.sites,deployedAt=Date.parse(String((sites as Value)?.deployment&&((sites as Value).deployment as Value).deployedAt));
 if(!exact(sites,["projectId","current","rollback","resources","deployment","buildReceipt"])||typeof sites.projectId!=="string"||!/^appgprj_[a-f0-9]{32}$/.test(sites.projectId)||!exact(sites.current,["version","commitSha"])||!exact(sites.rollback,["version","commitSha"])||!VERSION.test(String(sites.current.version))||!VERSION.test(String(sites.rollback.version))||!String(sites.current.version).startsWith(`${sites.projectId}~`)||!String(sites.rollback.version).startsWith(`${sites.projectId}~`)||sites.current.version!==release!.sitesVersion||sites.current.commitSha!==release!.commitSha||!COMMIT.test(String(sites.current.commitSha))||!COMMIT.test(String(sites.rollback.commitSha))||!Array.isArray(sites.resources)||sites.resources.length!==2||!exact(sites.deployment,["version","provider","projectId","deploymentId","versionId","commitSha","deployedAt"])||sites.deployment.version!==1||sites.deployment.provider!=="openai-sites-control-plane"||sites.deployment.projectId!==sites.projectId||sites.deployment.versionId!==sites.current.version||sites.deployment.commitSha!==sites.current.commitSha||!DEPLOYMENT.test(String(sites.deployment.deploymentId))||!Number.isFinite(deployedAt)||deployedAt>capturedAt||deployedAt<capturedAt-300_000||deployedAt<Date.parse(release!.startsAt)-300_000)invalid();
 const build=sites.buildReceipt;
 if(!exact(build,["version","projectId","versionId","deploymentId","commitSha","archiveSha256","runtimeSha256","buildId","providerScriptName","providerScriptVersion","observedAt"])||build.version!==1||build.projectId!==sites.projectId||build.versionId!==sites.current.version||build.deploymentId!==sites.deployment.deploymentId||build.commitSha!==sites.current.commitSha||!UUID.test(String(build.buildId))||!UUID.test(String(build.providerScriptVersion))||build.providerScriptName!==`site---${String(sites.projectId).slice(8)}`||!Number.isSafeInteger(build.observedAt)||Number(build.observedAt)>capturedAt||Number(build.observedAt)<capturedAt-300_000)invalid();hashField(build.archiveSha256);hashField(build.runtimeSha256);
 const audio=sites.resources[0],database=sites.resources[1];
 if(!exact(audio,["provider","binding","kind","physicalId","archiveSha256","deploymentId","buildId"])||!exact(database,["provider","binding","kind","physicalId","buildId","schemaDigest","schemaObjectCount","migrationDigest","migrationCount"])||audio.provider!=="sites-managed"||audio.binding!=="AUDIO"||audio.kind!=="r2"||audio.physicalId!=="unknown-managed"||audio.archiveSha256!==build.archiveSha256||audio.deploymentId!==sites.deployment.deploymentId||audio.buildId!==build.buildId||database.provider!=="sites-managed"||database.binding!=="DB"||database.kind!=="d1"||database.physicalId!=="unknown-managed"||database.buildId!==build.buildId||!Number.isSafeInteger(database.schemaObjectCount)||Number(database.schemaObjectCount)<1||!Number.isSafeInteger(database.migrationCount)||Number(database.migrationCount)<1)invalid();hashField(database.schemaDigest);hashField(database.migrationDigest);
 const d1=value.d1;if(!exact(d1,["appliedMigrations","appliedLedgerHash","reviewedSourceHash","schemaHash","schemaObjectCount","sourceSchemaDefinitionHash","sourceSchemaObjectCount","providerInternalSchemaHash","providerInternalSchemaObjectCount"])||!Array.isArray(d1.appliedMigrations)||!d1.appliedMigrations.length)invalid();for(const [index,row]of d1.appliedMigrations.entries()){if(!exact(row,["sequence","name","appliedAt"])||row.sequence!==index+1||typeof row.name!=="string"||!/^[0-9]{4}_[a-z0-9_]+\.sql$/.test(row.name)||typeof row.appliedAt!=="string"||!/^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]{1,6})?$/.test(row.appliedAt))invalid()}for(const key of["appliedLedgerHash","reviewedSourceHash","schemaHash","sourceSchemaDefinitionHash","providerInternalSchemaHash"])hashField(d1[key]);if(d1.appliedLedgerHash!==canonicalHash(d1.appliedMigrations)||!Number.isSafeInteger(d1.schemaObjectCount)||!Number.isSafeInteger(d1.sourceSchemaObjectCount)||!Number.isSafeInteger(d1.providerInternalSchemaObjectCount)||Number(d1.schemaObjectCount)!==Number(d1.sourceSchemaObjectCount)+Number(d1.providerInternalSchemaObjectCount)||Number(d1.providerInternalSchemaObjectCount)<0||Number(d1.providerInternalSchemaObjectCount)>5)invalid();
 const postgres=value.postgres;if(!exact(postgres,["migrationsHash","catalogHash"]))invalid();hashField(postgres.migrationsHash);hashField(postgres.catalogHash);const dns=value.dns;if(!exact(dns,["records"])||!Array.isArray(dns.records)||!dns.records.length)invalid();for(const row of dns.records)if(!exact(row,["name","recordId","type"])||typeof row.name!=="string"||!/^(?:[a-z0-9-]+\.)+[a-z]{2,63}$/.test(row.name)||typeof row.recordId!=="string"||!/^[A-Za-z][A-Za-z0-9_.:/@-]{2,511}$/.test(row.recordId)||typeof row.type!=="string"||!/^(?:A|AAAA|CNAME|MX|NS|SOA|TXT)$/.test(row.type))invalid();const secretVersions=value.secretVersions,oauth=value.oauth,client="619793096923-2hspnuckl0j99p3jrfb6qd21aatb0pep.apps.googleusercontent.com";if(!exact(oauth,["issuer","audience","clientId","providerAcceptedRedirectUri","proof"])||oauth.issuer!=="https://accounts.google.com"||oauth.audience!==client||oauth.clientId!==client||oauth.providerAcceptedRedirectUri!=="https://nearyoustill.com/api/auth/callback/google"||oauth.proof!=="interaction_required")invalid();if(!exact(value.bindings,["bindings"])||JSON.stringify(value.bindings.bindings)!==JSON.stringify(sites.resources)||!Array.isArray(secretVersions)||secretVersions.length!==REVIEWED_SECRETS.length||new Set(secretVersions).size!==secretVersions.length||REVIEWED_SECRETS.some(secret=>!secretVersions.some(item=>typeof item==="string"&&new RegExp(`^projects/${PRODUCTION_PROJECT}/secrets/${secret}/versions/[1-9][0-9]*$`).test(item)))||!exact(value.gates,["nearfamily","nearstory","scheduler"])||value.gates.nearfamily!==false||value.gates.nearstory!==false||value.gates.scheduler!==false)invalid();
 const observations=value.observations,keys=["d1Ledger","d1Schema","postgresMigrations","postgresCatalog","sitesResourceReceipt","dns","oauth","secretManager","gates"],runtimeKeys=["d1Ledger","d1Schema","oauth","gates"];if(!exact(observations,keys))invalid();for(const key of keys){const row=observations[key],runtime=runtimeKeys.includes(key);if(!exact(row,runtime?["provider","identity","observedAt","rayId"]:["provider","identity","observedAt"])||typeof row.provider!=="string"||typeof row.identity!=="string"||!Number.isSafeInteger(row.observedAt)||Number(row.observedAt)>capturedAt||Number(row.observedAt)<capturedAt-300_000||(runtime&&(!RAY.test(String(row.rayId))||row.provider!=="sites-runtime"||!SERVICE.test(String(row.identity))))||(["postgresMigrations","postgresCatalog"].includes(key)&&(row.provider!=="cloud-sql"||row.identity!=="database:nearyou-pt-baseline@nearnight.iam"))||(key==="sitesResourceReceipt"&&(row.provider!=="openai-sites-control-plane"||row.identity!==`project:${sites.projectId}`))||(["dns","secretManager"].includes(key)&&(row.provider!=="google"||row.identity!==(observations.d1Ledger as Value).identity)))invalid()}if(runtimeKeys.some(key=>(observations[key]as Value).identity!==(observations.d1Ledger as Value).identity))invalid();return value}

export async function promotePrivateTesterBaseline(input:{candidatePath:string;logReceiptPath:string;outputPath:string;expectedLogReceiptSha256:string;now():number}){if(!exact(input,["candidatePath","logReceiptPath","outputPath","expectedLogReceiptSha256","now"])||!HASH.test(input.expectedLogReceiptSha256))invalid();const now=input.now(),candidateFile=await readExact(input.candidatePath),baseline=validatePrivateTesterBaselineCandidate(candidateFile.value,now),receiptFile=await readExact(input.logReceiptPath),receipt=receiptFile.value,build=((baseline.sites as Value).buildReceipt as Value);if(sha(receiptFile.raw)!==input.expectedLogReceiptSha256||!exact(receipt,["version","provider","candidateSha256","scriptName","scriptVersionId","capturedAt","observations"])||receipt.version!==1||receipt.provider!=="sites-worker-logs"||receipt.candidateSha256!==sha(candidateFile.raw)||receipt.scriptName!==build.providerScriptName||receipt.scriptVersionId!==build.providerScriptVersion||!UUID.test(String(receipt.scriptVersionId))||!Number.isSafeInteger(receipt.capturedAt)||Number(receipt.capturedAt)<Number(baseline.capturedAt)||Number(receipt.capturedAt)-Number(baseline.capturedAt)>300_000||Number(receipt.capturedAt)>now||now-Number(receipt.capturedAt)>300_000||!Array.isArray(receipt.observations)||receipt.observations.length!==4)invalid();const kinds=["d1Ledger","d1Schema","gates","oauth"],seen=new Set<string>();for(const[index,row]of receipt.observations.entries()){if(!exact(row,["kind","rayId","scriptVersionId","observedAt"])||row.kind!==kinds[index]||!RAY.test(String(row.rayId))||seen.has(String(row.rayId))||row.scriptVersionId!==receipt.scriptVersionId||!Number.isSafeInteger(row.observedAt)||Number(row.observedAt)>Number(receipt.capturedAt)||Number(row.observedAt)<Number(baseline.capturedAt)-300_000||Math.abs(Number(row.observedAt)-Number((baseline.observations as Value)[String(row.kind)] && ((baseline.observations as Value)[String(row.kind)]as Value).observedAt))>30_000||row.rayId!==((baseline.observations as Value)[String(row.kind)]as Value).rayId)invalid();seen.add(String(row.rayId))}const final={...baseline,reviewRequired:false,sites:{...(baseline.sites as Value),logReceiptSha256:sha(receiptFile.raw)}};await writeFile(input.outputPath,`${JSON.stringify(final)}\n`,{flag:"wx"});return final}
if(import.meta.url===`file://${process.argv[1]}`){const[candidatePath,logReceiptPath,outputPath]=process.argv.slice(2),expectedLogReceiptSha256=process.env.SITES_WORKER_LOG_RECEIPT_SHA256??"";promotePrivateTesterBaseline({candidatePath:candidatePath??"",logReceiptPath:logReceiptPath??"",outputPath:outputPath??"",expectedLogReceiptSha256,now:Date.now}).catch(()=>{process.stderr.write("private tester baseline promotion failed\n");process.exitCode=1})}
