import{readFile}from"node:fs/promises";
import{registerRolloutController,type AdminPg}from"./register-rollout-controller";
const INSTANCE="nearnight:us-central1:nearyou-evidence-20260820",CONTROLLER="nf-rdy-controller@nearnight.iam",KILL="nf-rdy-kill@nearnight.iam",DECISION="nf-rdy-decision@nearnight.iam",CONTROLLER_PRINCIPAL="service:nearyou_readiness_controller",KILL_PRINCIPAL="service:nearyou_readiness_controller_kill";
type Pg={query<T>(sql:string,args?:unknown[]):Promise<{rows:T[]}>};
type Connection=Pg&{transaction<T>(run:(tx:Pg)=>Promise<T>):Promise<T>;close():Promise<void>};
type Dependencies={connect?(url:string):Promise<Connection>};
type Acl={controller_role:boolean;controller_cross_lane:boolean;kill_role:boolean;kill_cross_lane:boolean;decision_role:boolean;decision_cross_lane:boolean};
function connectionFailure(error:unknown){const code=typeof error==="object"&&error!==null&&"code" in error&&typeof error.code==="string"?error.code:"",stage=({"28P01":"credentials","3D000":"database",ECONNREFUSED:"refused",ETIMEDOUT:"timeout",ENETUNREACH:"network",EHOSTUNREACH:"network",ENOTFOUND:"dns"}as Record<string,string>)[code];return new Error(`disposable gateway database connection failed${stage?`:${stage}`:""}`)}
async function connect(url:string):Promise<Connection>{const moduleName="pg",{Pool}=await import(moduleName)as unknown as{Pool:new(input:{connectionString:string})=>{connect():Promise<{query<T>(sql:string,args?:unknown[]):Promise<{rows:T[]}>;release():void}>;end():Promise<void>}},pool=new Pool({connectionString:url}),client=await pool.connect();return{query:(sql,args=[])=>client.query(sql,args),transaction:async run=>{await client.query("BEGIN");try{const result=await run({query:(sql,args=[])=>client.query(sql,args)});await client.query("COMMIT");return result}catch(error){await client.query("ROLLBACK");throw error}},close:async()=>{client.release();await pool.end()}}}
export async function verifyDisposableGatewayDatabase(input:{instance:string;disposable:boolean;databaseUrl:string},dependencies:Dependencies={}){if(input.instance!==INSTANCE||input.disposable!==true||!/^postgres(?:ql)?:\/\//.test(input.databaseUrl))throw new Error("disposable gateway database configuration invalid");let db:Connection;try{db=await(dependencies.connect??connect)(input.databaseUrl)}catch(error){throw connectionFailure(error)}try{let target:{database_name:string;server_version:number;migration_head:string}|undefined;try{target=(await db.query<{database_name:string;server_version:number;migration_head:string}>("SELECT current_database()::text AS database_name,current_setting('server_version_num')::integer AS server_version,(SELECT id FROM nearyou.schema_migrations ORDER BY id COLLATE \"C\" DESC LIMIT 1) AS migration_head",[])).rows[0]}catch{throw new Error("disposable gateway database migration read failed")}if(!target||target.database_name!=="nearyou"||target.server_version<160000||target.server_version>=170000||target.migration_head!=="0014_release_policy_evidence_read")throw new Error("disposable gateway database migration invalid");const controller=await registerRolloutController(db as AdminPg,CONTROLLER,CONTROLLER_PRINCIPAL),kill=await registerRolloutController(db as AdminPg,KILL,KILL_PRINCIPAL);let acl:Acl|undefined;try{acl=(await db.query<Acl>("SELECT pg_has_role($1,'nearyou_rollout_controller','USAGE') AS controller_role,pg_has_role($1,'nearyou_private_tester_decision','USAGE') AS controller_cross_lane,pg_has_role($2,'nearyou_rollout_controller','USAGE') AS kill_role,pg_has_role($2,'nearyou_private_tester_decision','USAGE') AS kill_cross_lane,pg_has_role($3,'nearyou_private_tester_decision','USAGE') AS decision_role,pg_has_role($3,'nearyou_rollout_controller','USAGE') AS decision_cross_lane",[CONTROLLER,KILL,DECISION])).rows[0]}catch{throw new Error("disposable gateway database ACL read failed")}if(!controller.controllerMappingVerified||!kill.controllerMappingVerified||!acl||!acl.controller_role||acl.controller_cross_lane||!acl.kill_role||acl.kill_cross_lane||!acl.decision_role||acl.decision_cross_lane)throw new Error("disposable gateway database ACL invalid");return{version:1,disposable:true as const,instance:INSTANCE,migrationHead:target.migration_head,controller:{databaseUser:CONTROLLER,principal:CONTROLLER_PRINCIPAL,mapped:true},kill:{databaseUser:KILL,principal:KILL_PRINCIPAL,mapped:true},decision:{databaseUser:DECISION},laneIsolation:true as const}}finally{await db.close()}}
async function cli(){const path=process.argv[2];if(!path)throw new Error("disposable gateway database secret path missing");const databaseUrl=(await readFile(path,"utf8")).trim(),receipt=await verifyDisposableGatewayDatabase({instance:process.env.NEARYOU_GATEWAY_DATABASE_INSTANCE??"",disposable:process.env.NEARYOU_GATEWAY_DATABASE_DISPOSABLE==="true",databaseUrl});process.stdout.write(`${JSON.stringify(receipt)}\n`)}
if(process.argv[1]?.endsWith("verify-disposable-gateway-database.ts"))cli().catch(error=>{const message=error instanceof Error&&/^(?:disposable gateway database|controller registration failed:)[A-Za-z0-9 _:-]+$/.test(error.message)?error.message:"Disposable gateway database verification failed";console.error(message);process.exitCode=1});
