import { env } from "cloudflare:workers";
import { apiV1Failure, badRequest, requireHouseholdContext } from "@/lib/api-v1-context";
import { assertTrustedMutationOrigin, jsonNoStore } from "@/lib/http";
import { putPrivateLegacyStream } from "@/lib/nearlegacy-media";
import { enforceLegacyRateLimit, legacyHash, legacyInternalId, legacyUuid } from "@/lib/nearlegacy-route";
import { nearLegacyReady, requireLegacyEntitlement } from "../production";

type Bucket=Parameters<typeof putPrivateLegacyStream>[0]; const bucket=()=> (env as unknown as {AUDIO:Bucket}).AUDIO;
export async function POST(request:Request){try{
  assertTrustedMutationOrigin(request);if(!await nearLegacyReady())return jsonNoStore({error:"NearLegacy is not available."},{status:404});const {householdId,user,role}=await requireHouseholdContext(request,"archive:read");const limited=await enforceLegacyRateLimit(env.DB,householdId,user.userId,"recording_upload",6,60_000);if(limited)return limited;if(!await requireLegacyEntitlement(householdId))return jsonNoStore({error:"NearLegacy is required."},{status:403});if(role!=='contributor'&&role!=='owner')return jsonNoStore({error:"Only a contributor recording themself may add archive audio."},{status:403});
  const key=request.headers.get("idempotency-key")||"";let id:string;try{id=await legacyInternalId("recording",householdId,key);}catch(error){return badRequest(error);}const contributorId=legacyUuid(request.headers.get("x-nearyou-contributor-id"),"contributorId"),recordingConsentId=legacyUuid(request.headers.get("x-nearyou-recording-consent-id"),"recordingConsentId"),transcriptionConsentId=legacyUuid(request.headers.get("x-nearyou-transcription-consent-id"),"transcriptionConsentId");const interviewRaw=request.headers.get("x-nearyou-interview-id"),interviewId=interviewRaw?legacyUuid(interviewRaw,"interviewId"):null;const durationMs=Number(request.headers.get("x-nearyou-duration-ms")),byteSize=Number(request.headers.get("content-length")),checksum=(request.headers.get("x-content-sha256")||"").toLowerCase(),contentType=(request.headers.get("content-type")||"").toLowerCase();if(!Number.isSafeInteger(durationMs)||durationMs<1000||durationMs>7200000||!Number.isSafeInteger(byteSize)||byteSize<10000||byteSize>50000000||!/^[0-9a-f]{64}$/.test(checksum)||!['audio/webm','audio/mp4','audio/mpeg'].includes(contentType)||!request.body)return badRequest(new Error("A bounded audio body, duration, and SHA-256 are required."));const processorUrl=process.env.NEARYOU_LEGACY_MEDIA_PROCESSOR_URL?.trim(),processorToken=process.env.NEARYOU_LEGACY_MEDIA_PROCESSOR_TOKEN?.trim();if(!processorUrl?.startsWith("https://")||!processorToken||processorToken.length<32)return jsonNoStore({error:"Recording verification is temporarily unavailable."},{status:503});const [processorBody,storageBody]=request.body.tee();
  const self=await env.DB.prepare("SELECT id FROM contributors WHERE id=? AND household_id=? AND adult_user_id=? AND status='active'").bind(contributorId,householdId,user.userId).all();if(!self.results?.length)return jsonNoStore({error:"Contributors may upload only their own recordings."},{status:403});
  const scoped=await env.DB.prepare("SELECT id,kind,version,audience,purpose FROM legacy_consents WHERE id IN (?,?) AND household_id=? AND contributor_id=? AND status='active' AND (expires_at IS NULL OR expires_at>?)").bind(recordingConsentId,transcriptionConsentId,householdId,contributorId,Date.now()).all();const byId=new Map((scoped.results||[]).map((row)=>[String((row as Record<string,unknown>).id),row as Record<string,unknown>]));const recordingScope=byId.get(recordingConsentId),transcriptionScope=byId.get(transcriptionConsentId);if(recordingScope?.kind!=='recording'||transcriptionScope?.kind!=='transcription'||recordingScope.version!=='legacy-consent-v1'||transcriptionScope.version!=='legacy-consent-v1'||recordingScope.audience!=='household'||transcriptionScope.audience!=='household'||recordingScope.purpose!=='private_archive'||transcriptionScope.purpose!=='private_archive')return jsonNoStore({error:"Active recording and transcription consent from this contributor are required."},{status:403});
  const now=Date.now(),extension=contentType==='audio/mp4'?'m4a':contentType==='audio/mpeg'?'mp3':'webm',storageKey=`legacy/${householdId}/recording/${id}.${extension}`,requestHash=await legacyHash(JSON.stringify({contributorId,recordingConsentId,transcriptionConsentId,interviewId,durationMs,byteSize,checksum,contentType})),mediaId=await legacyInternalId("recording-media",householdId,key),jobId=await legacyInternalId("recording-job",householdId,key),reservationId=await legacyInternalId("recording-usage",householdId,key),spendId=await legacyInternalId("recording-spend",householdId,key),bindingId=await legacyInternalId("recording-binding",householdId,key);
  await env.DB.prepare("INSERT OR IGNORE INTO legacy_upload_operations (id,household_id,requested_by_user_id,kind,request_hash,storage_key,checksum,byte_size,status,target_id,created_at,updated_at) VALUES (?,?,?,'recording',?,?,?,?, 'staged',?,?,?)").bind(id,householdId,user.userId,requestHash,storageKey,checksum,byteSize,id,now,now).run();const op=await env.DB.prepare("SELECT request_hash,status FROM legacy_upload_operations WHERE id=? AND household_id=?").bind(id,householdId).all();const existing=op.results?.[0] as Record<string,unknown>|undefined;if(!existing||existing.request_hash!==requestHash)return jsonNoStore({error:"That idempotency key belongs to another recording."},{status:409});if(existing.status==='committed')return jsonNoStore({recording:{id,status:"ready"},duplicate:true});if(existing.status==='cleanup_required'||existing.status==='deleted')return jsonNoStore({error:"This upload attempt was safely closed. Start a new recording with a new idempotency key.",code:"upload_closed"},{status:409});
  const entitlement=await env.DB.prepare("SELECT id FROM entitlements WHERE household_id=? AND plan_id IN ('nearlegacy','archive_builder') AND status IN ('active','grace') AND valid_from<=? AND (valid_until IS NULL OR valid_until>?) ORDER BY updated_at DESC LIMIT 1").bind(householdId,now,now).all();if(!entitlement.results?.length){await env.DB.prepare("UPDATE legacy_upload_operations SET status='deleted',updated_at=? WHERE id=? AND household_id=? AND status='staged'").bind(now,id,householdId).run();throw new Error("legacy_entitlement_missing");}const quantity=Math.max(1,Math.ceil(durationMs/60000)),weight=quantity*1000;
  try{await env.DB.batch([
    env.DB.prepare("INSERT OR IGNORE INTO media_assets (id,household_id,owner_user_id,kind,status,storage_key,content_type,byte_size,checksum,private,created_at,updated_at) VALUES (?,?,?,'recording','processing',?,?,?,?,1,?,?)").bind(mediaId,householdId,user.userId,storageKey,contentType,byteSize,checksum,now,now),
    env.DB.prepare("INSERT OR IGNORE INTO household_storage_reservations (id,household_id,media_asset_id,byte_size,status,created_at,updated_at) VALUES (?,?,?,?,'reserved',?,?)").bind(`storage:${mediaId}`,householdId,mediaId,byteSize,now,now),
    env.DB.prepare("INSERT OR IGNORE INTO usage_reservations (id,household_id,user_id,entitlement_id,operation,quantity,weight_milliunits,idempotency_key,request_hash,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,? ,?,'reserved',?,?)").bind(reservationId,householdId,user.userId,entitlement.results[0].id,'archive_transcription',quantity,weight,`legacy-transcription:${key}`,requestHash,now,now),
    env.DB.prepare("INSERT OR IGNORE INTO provider_spend_reservations (id,household_id,user_id,provider,operation,idempotency_key,estimated_microcents,status,expires_at,created_at,updated_at) VALUES (?,?,?,'elevenlabs','archive_transcription',?,?,'in_flight',?,?,?)").bind(spendId,householdId,user.userId,`legacy-transcription:${key}`,quantity*250000,now+300000,now,now),
  ]);}catch(error){await env.DB.prepare("UPDATE legacy_upload_operations SET status='deleted',updated_at=? WHERE id=? AND household_id=? AND status='staged'").bind(Date.now(),id,householdId).run();throw error;}
  if(existing.status==='staged'){try{const verified=await fetch(processorUrl,{method:"POST",headers:{authorization:`Bearer ${processorToken}`,"content-type":contentType,"x-nearyou-household-id":householdId,"x-nearyou-user-id":user.userId,"x-nearyou-contributor-id":contributorId,"x-nearyou-media-kind":"recording","x-content-sha256":checksum},body:processorBody,signal:AbortSignal.timeout(120000)});if(!verified.ok)throw new Error("recording_probe_rejected");const probe=await verified.json().catch(()=>null) as Record<string,unknown>|null;if(!probe||probe.checksum!==checksum||probe.byteSize!==byteSize||probe.contentType!==contentType||!Number.isSafeInteger(probe.durationMs)||Math.abs(Number(probe.durationMs)-durationMs)>500||typeof probe.processorReceiptId!=="string"||probe.processorReceiptId.length<8||probe.processorReceiptId.length>200)throw new Error("recording_probe_mismatch");await putPrivateLegacyStream(bucket(),storageKey,storageBody,byteSize,contentType,checksum);}catch(error){const failed=Date.now();await env.DB.batch([env.DB.prepare("UPDATE media_assets SET status='deleted',deleted_at=?,updated_at=? WHERE id=? AND household_id=? AND status='processing'").bind(failed,failed,mediaId,householdId),env.DB.prepare("UPDATE usage_reservations SET status='released',finalized_at=?,updated_at=? WHERE id=? AND household_id=? AND status='reserved'").bind(failed,failed,reservationId,householdId),env.DB.prepare("UPDATE provider_spend_reservations SET status='released',updated_at=? WHERE id=? AND household_id=? AND status='in_flight'").bind(failed,spendId,householdId),env.DB.prepare("UPDATE legacy_upload_operations SET status='cleanup_required',updated_at=? WHERE id=? AND household_id=? AND status='staged'").bind(failed,id,householdId)]);throw error;}await env.DB.prepare("UPDATE legacy_upload_operations SET status='stored',updated_at=? WHERE id=? AND household_id=? AND status='staged'").bind(Date.now(),id,householdId).run();}
  try{await env.DB.batch([
    env.DB.prepare("INSERT OR IGNORE INTO task2c_media_integrity (media_asset_id,byte_size,checksum,verified_at) VALUES (?,?,?,?)").bind(mediaId,byteSize,checksum,now),
    env.DB.prepare("INSERT OR IGNORE INTO jobs (id,household_id,requested_by_user_id,type,status,idempotency_key,request_hash,input,progress_percent,progress_stage,reservation_id,created_at,updated_at) VALUES (?,?,?,'archive_transcription','queued',?,?,?,0,'queued',?,?,?)").bind(jobId,householdId,user.userId,`legacy-transcription:${key}`,requestHash,JSON.stringify({recordingId:id}),reservationId,now,now),
    env.DB.prepare("INSERT OR IGNORE INTO legacy_recordings (id,household_id,interview_id,contributor_id,consent_id,media_asset_id,transcription_job_id,recorded_at,duration_ms,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'processing',?,?)").bind(id,householdId,interviewId,contributorId,recordingConsentId,mediaId,jobId,now,durationMs,now,now),
    env.DB.prepare("INSERT OR IGNORE INTO legacy_job_bindings (id,household_id,job_id,contributor_id,recording_id,consent_id,reservation_id,provider_spend_reservation_id,operation,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'transcription','active',?,?)").bind(bindingId,householdId,jobId,contributorId,id,transcriptionConsentId,reservationId,spendId,now,now),
    env.DB.prepare("UPDATE media_assets SET status='ready',updated_at=? WHERE id=? AND household_id=? AND status='processing'").bind(now,mediaId,householdId),
    env.DB.prepare("UPDATE legacy_recordings SET status='ready',updated_at=? WHERE id=? AND household_id=? AND status='processing'").bind(now,id,householdId),
    env.DB.prepare("UPDATE legacy_upload_operations SET status='committed',updated_at=? WHERE id=? AND household_id=? AND status='stored'").bind(now,id,householdId),
  ]);}catch(error){const state=await env.DB.prepare("SELECT status FROM legacy_upload_operations WHERE id=? AND household_id=?").bind(id,householdId).all();if((state.results?.[0] as Record<string,unknown>|undefined)?.status==='committed')return jsonNoStore({recording:{id,status:"ready",transcriptionStatus:"queued"},jobId,duplicate:true},{status:202});const failed=Date.now();await env.DB.batch([env.DB.prepare("UPDATE legacy_upload_operations SET status='cleanup_required',updated_at=? WHERE id=? AND household_id=? AND status='stored'").bind(failed,id,householdId),env.DB.prepare("UPDATE media_assets SET status='deleted',deleted_at=?,updated_at=? WHERE id=? AND household_id=? AND status='processing'").bind(failed,failed,mediaId,householdId),env.DB.prepare("UPDATE usage_reservations SET status='released',finalized_at=?,updated_at=? WHERE id=? AND household_id=? AND status='reserved'").bind(failed,failed,reservationId,householdId),env.DB.prepare("UPDATE provider_spend_reservations SET status='released',updated_at=? WHERE id=? AND household_id=? AND status='in_flight'").bind(failed,spendId,householdId)]);throw error;}return jsonNoStore({recording:{id,status:"ready",transcriptionStatus:"queued"},jobId},{status:202});
}catch(error){return apiV1Failure(error,"Archive recording could not be queued.");}}
