import type { Metadata } from "next";
import { Link } from "@/components/Link";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { ProductFamily } from "@/components/ProductFamily";
import { getAppUser, signInPath } from "@/lib/auth";
import { featureFlagsFromEnv, nearSleepProductionEnabled } from "@/lib/nearyou-foundation";

export const metadata: Metadata = { title: "Pricing", description: "Simple NearSleep plans with predictable generation limits and unlimited replays." };
export const dynamic = "force-dynamic";

export default async function PricingPage() {
  const user = await getAppUser();
  if (nearSleepProductionEnabled(featureFlagsFromEnv(process.env))) {
    const checkoutButton = (plan: "nearyou_plus" | "nearyou_family" | "nearlegacy" | "archive_builder" | "archive_care", interval: "month" | "year" | "one_time", label: string) => user
      ? <form action="/api/billing/checkout" method="post" style={{ marginTop: 20 }}><input type="hidden" name="plan" value={plan} /><input type="hidden" name="interval" value={interval} /><button className="btn btn-primary" type="submit">{label}</button></form>
      : <Link className="btn btn-primary" href={signInPath("/pricing")} style={{ marginTop: 20 }}>Sign in to choose</Link>;
    return <><SiteHeader /><main className="section" style={{ paddingTop: 65 }}><div className="container"><div className="section-head center"><span className="eyebrow">NearSleep by NearYou</span><h1 className="display" style={{ fontSize: "clamp(3.4rem,7vw,6rem)", margin: "12px 0" }}>A plan for your household.</h1><p className="muted">NearSleep Free includes one five-minute creation with a standard non-cloned narrator. Private household voices require a paid plan. Paid allowances refill monthly, including annual subscriptions, with one-cycle narration rollover.</p></div><div className="card-grid two">
      <div className="pricing-card"><div className="pricing-main"><span className="eyebrow">NearYou Plus</span><div className="price">$14.99 <small>/ month</small></div><p className="muted">NearSleep + NearStory, with 60 new narration minutes each month for up to two child profiles and one verified adult voice. Saved audio replays are unlimited.</p>{checkoutButton("nearyou_plus","month", "Start monthly")}{checkoutButton("nearyou_plus","year", "Save with annual")}</div></div>
      <div className="pricing-card"><div className="pricing-main"><span className="eyebrow">NearYou Family</span><div className="price">$24.99 <small>/ month</small></div><p className="muted">120 narration minutes each month for up to five child profiles and two verified adult voices.</p>{checkoutButton("nearyou_family","month", "Start monthly")}{checkoutButton("nearyou_family","year", "Save with annual")}</div></div>
      <div className="pricing-card"><div className="pricing-main"><span className="eyebrow">NearLegacy</span><div className="price">$39.99 <small>/ month</small></div><p className="muted">All modules, five consented adult voices, 180 transcription minutes, 100 GB, and family archive custody.</p>{checkoutButton("nearlegacy","month","Start NearLegacy")}{checkoutButton("nearlegacy","year","Choose annual")}</div></div>
      <div className="pricing-card"><div className="pricing-main"><span className="eyebrow">Archive Builder</span><div className="price">$199 <small>once</small></div><p className="muted">Guided archive creation, 600 interview minutes, organization, export, and the first year of Archive Care.</p>{checkoutButton("archive_builder","one_time","Build an archive")}</div></div>
      <div className="pricing-card"><div className="pricing-main"><span className="eyebrow">Archive Care</span><div className="price">$59 <small>/ year</small></div><p className="muted">Private preservation, playback, grounded search, and export without new generation.</p>{checkoutButton("archive_care","year","Preserve my archive")}</div></div>
    </div><p className="pricing-note center" style={{ marginTop: 24 }}>{user && <>Complete the adult caregiver confirmation in <Link href="/studio">Studio</Link> before starting checkout. </>}Stripe test checkout only during coordinated rollout. Existing continuously subscribed $12 members remain grandfathered; it is not available for new purchase.</p></div></main><ProductFamily source="pricing" /><SiteFooter /></>;
  }
  return <><SiteHeader /><main className="section" style={{ paddingTop: 65 }}><div className="container"><div className="section-head center"><span className="eyebrow">Predictable by design</span><h1 className="display" style={{ fontSize: "clamp(3.4rem,7vw,6rem)", margin: "12px 0" }}>More gentle nights.<br />No surprise bills.</h1><p className="muted">Generation credits control provider costs; saved sessions can be replayed as often as your family needs.</p></div><div className="pricing-card"><div className="pricing-main"><span className="eyebrow">NearSleep Plus</span><div className="price">$12 <small>/ month</small></div><p className="muted">One free personalized bedtime, then 12 new sessions per month.</p>{user ? <form action="/api/billing/checkout" method="post" style={{ marginTop: 20 }}><button className="btn btn-primary" type="submit">Start NearSleep Plus</button></form> : <Link className="btn btn-primary" href={signInPath("/pricing")} style={{ marginTop: 20 }}>Sign in to start Plus</Link>}<p className="pricing-note">Secure test checkout is handled by Stripe. Cancel anytime from Voice & account.</p><Link className="btn btn-secondary btn-small" href="/studio" style={{ marginTop: 12 }}>Create your free bedtime</Link></div><div className="pricing-details"><strong>Plus includes</strong><ul className="check-list"><li>One private parent voice profile</li><li>12 fresh 5–20 minute sessions/month</li><li>Unlimited library replays</li><li>Curated or personalized writing</li><li>Soft rain and noise layers</li><li>Cancel or delete anytime</li></ul><hr style={{ border: 0, borderTop: "1px solid var(--line)", margin: "25px 0" }} /><strong>Why credits?</strong><p className="muted" style={{ fontSize: ".85rem" }}>Audio generation has a real per-character cost. A generous monthly allowance keeps pricing sustainable without exposing parents to usage-based invoices.</p></div></div></div></main><ProductFamily source="pricing" /><SiteFooter /></>;
}
